// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module PLL2026_x64_SQRT_LUT (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x,
        ap_return
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] x;
output  [63:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] ap_return;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] table_mark_V_address0;
reg    table_mark_V_ce0;
wire   [62:0] table_mark_V_q0;
wire   [5:0] table_m_V_address0;
reg    table_m_V_ce0;
wire   [48:0] table_m_V_q0;
wire   [5:0] table_n_V_address0;
reg    table_n_V_ce0;
wire   [54:0] table_n_V_q0;
wire   [0:0] tmp_fu_134_p3;
reg   [0:0] tmp_reg_273;
wire   [31:0] half_list_fu_178_p2;
reg   [31:0] half_list_reg_280;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln986_fu_158_p2;
wire   [31:0] intervalo_begin_1_fu_198_p3;
wire    ap_CS_fsm_state3;
wire   [31:0] intervalo_end_1_fu_205_p3;
wire    ap_CS_fsm_state4;
wire   [63:0] ret_V_fu_223_p2;
reg  signed [63:0] ret_V_reg_316;
wire    ap_CS_fsm_state5;
reg   [48:0] r_V_reg_321;
reg   [54:0] rhs_1_reg_326;
wire    ap_CS_fsm_state6;
wire   [111:0] grp_fu_234_p2;
reg   [111:0] r_V_1_reg_341;
wire    ap_CS_fsm_state10;
reg   [31:0] intervalo_begin_reg_99;
reg   [31:0] intervalo_end_reg_111;
reg   [63:0] ap_phi_mux_y_V_phi_fu_127_p4;
reg   [63:0] y_V_reg_123;
wire    ap_CS_fsm_state11;
wire   [63:0] zext_ln991_fu_184_p1;
wire   [63:0] zext_ln1227_fu_212_p1;
wire   [31:0] sub_ln986_fu_142_p2;
wire   [30:0] tmp_8_fu_148_p4;
wire   [30:0] div1_i_fu_164_p4;
wire   [31:0] div1_i_cast_fu_174_p1;
wire   [63:0] zext_ln1494_fu_189_p1;
wire   [0:0] icmp_ln1494_fu_193_p2;
wire   [63:0] zext_ln1193_fu_219_p1;
wire   [48:0] grp_fu_234_p1;
wire   [102:0] rhs_2_fu_240_p3;
wire   [111:0] zext_ln1192_fu_247_p1;
wire   [111:0] ret_V_5_fu_251_p2;
reg   [63:0] ap_return_preg;
reg   [10:0] ap_NS_fsm;
wire   [111:0] grp_fu_234_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
#0 ap_return_preg = 64'd0;
end

PLL2026_x64_SQRT_LUT_table_mark_V #(
    .DataWidth( 63 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
table_mark_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_mark_V_address0),
    .ce0(table_mark_V_ce0),
    .q0(table_mark_V_q0)
);

PLL2026_x64_SQRT_LUT_table_m_V #(
    .DataWidth( 49 ),
    .AddressRange( 63 ),
    .AddressWidth( 6 ))
table_m_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_m_V_address0),
    .ce0(table_m_V_ce0),
    .q0(table_m_V_q0)
);

PLL2026_x64_SQRT_LUT_table_n_V #(
    .DataWidth( 55 ),
    .AddressRange( 63 ),
    .AddressWidth( 6 ))
table_n_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_n_V_address0),
    .ce0(table_n_V_ce0),
    .q0(table_n_V_q0)
);

PLL2026_x64_mul_64s_49ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 112 ))
mul_64s_49ns_112_5_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_reg_316),
    .din1(grp_fu_234_p1),
    .ce(1'b1),
    .dout(grp_fu_234_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 64'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_return_preg <= ap_phi_mux_y_V_phi_fu_127_p4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_134_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        intervalo_begin_reg_99 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        intervalo_begin_reg_99 <= intervalo_begin_1_fu_198_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_134_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        intervalo_end_reg_111 <= 32'd63;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        intervalo_end_reg_111 <= intervalo_end_1_fu_205_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_134_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        y_V_reg_123 <= 64'd0;
    end else if (((tmp_reg_273 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        y_V_reg_123 <= {{ret_V_5_fu_251_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln986_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        half_list_reg_280 <= half_list_fu_178_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        r_V_1_reg_341 <= grp_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        r_V_reg_321 <= table_m_V_q0;
        ret_V_reg_316 <= ret_V_fu_223_p2;
        rhs_1_reg_326 <= table_n_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        tmp_reg_273 <= x[32'd63];
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_273 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_y_V_phi_fu_127_p4 = {{ret_V_5_fu_251_p2[111:48]}};
    end else begin
        ap_phi_mux_y_V_phi_fu_127_p4 = y_V_reg_123;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_return = ap_phi_mux_y_V_phi_fu_127_p4;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        table_m_V_ce0 = 1'b1;
    end else begin
        table_m_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        table_mark_V_address0 = zext_ln1227_fu_212_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        table_mark_V_address0 = zext_ln991_fu_184_p1;
    end else begin
        table_mark_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2))) begin
        table_mark_V_ce0 = 1'b1;
    end else begin
        table_mark_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        table_n_V_ce0 = 1'b1;
    end else begin
        table_n_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((tmp_fu_134_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((tmp_fu_134_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln986_fu_158_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign div1_i_cast_fu_174_p1 = div1_i_fu_164_p4;

assign div1_i_fu_164_p4 = {{sub_ln986_fu_142_p2[31:1]}};

assign grp_fu_234_p1 = grp_fu_234_p10;

assign grp_fu_234_p10 = r_V_reg_321;

assign half_list_fu_178_p2 = (div1_i_cast_fu_174_p1 + intervalo_begin_reg_99);

assign icmp_ln1494_fu_193_p2 = (($signed(zext_ln1494_fu_189_p1) < $signed(x)) ? 1'b1 : 1'b0);

assign icmp_ln986_fu_158_p2 = (($signed(tmp_8_fu_148_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign intervalo_begin_1_fu_198_p3 = ((icmp_ln1494_fu_193_p2[0:0] == 1'b1) ? half_list_reg_280 : intervalo_begin_reg_99);

assign intervalo_end_1_fu_205_p3 = ((icmp_ln1494_fu_193_p2[0:0] == 1'b1) ? intervalo_end_reg_111 : half_list_reg_280);

assign ret_V_5_fu_251_p2 = (zext_ln1192_fu_247_p1 + r_V_1_reg_341);

assign ret_V_fu_223_p2 = (x - zext_ln1193_fu_219_p1);

assign rhs_2_fu_240_p3 = {{rhs_1_reg_326}, {48'd0}};

assign sub_ln986_fu_142_p2 = (intervalo_end_reg_111 - intervalo_begin_reg_99);

assign table_m_V_address0 = zext_ln1227_fu_212_p1;

assign table_n_V_address0 = zext_ln1227_fu_212_p1;

assign tmp_8_fu_148_p4 = {{sub_ln986_fu_142_p2[31:1]}};

assign tmp_fu_134_p3 = x[32'd63];

assign zext_ln1192_fu_247_p1 = rhs_2_fu_240_p3;

assign zext_ln1193_fu_219_p1 = table_mark_V_q0;

assign zext_ln1227_fu_212_p1 = intervalo_begin_reg_99;

assign zext_ln1494_fu_189_p1 = table_mark_V_q0;

assign zext_ln991_fu_184_p1 = half_list_fu_178_p2;

endmodule //PLL2026_x64_SQRT_LUT
