// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PLL2026_x64_PLL2026_x64,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.154914,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=36,HLS_SYN_DSP=0,HLS_SYN_FF=22490,HLS_SYN_LUT=22801,HLS_VERSION=2020_2}" *)

module PLL2026_x64 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sinc,
        EN1,
        EN2,
        EN3,
        EN4,
        EN5,
        EN6,
        vin_a,
        vin_b,
        vin_c,
        in_1,
        in_2,
        in_3,
        w_out,
        w_out_ap_vld,
        theta_out,
        theta_out_ap_vld,
        pll_alpha_out,
        pll_alpha_out_ap_vld,
        pll_beta_out,
        pll_beta_out_ap_vld,
        amp_vPos_out,
        amp_vPos_out_ap_vld,
        Amp_vneg_out,
        Amp_vneg_out_ap_vld,
        delta_out,
        delta_out_ap_vld,
        v_alfa_in,
        v_alfa_in_ap_vld,
        v_beta_in,
        v_beta_in_ap_vld,
        Amp_vneg_raw_base_out,
        Amp_vneg_raw_base_out_ap_vld,
        q_inv_d_out,
        q_inv_d_out_ap_vld,
        v2_d_limpo_out,
        v2_d_limpo_out_ap_vld,
        in_inv,
        in_inv_ap_vld,
        out_inv,
        out_inv_ap_vld,
        in_atan,
        in_atan_ap_vld,
        out_atan,
        out_atan_ap_vld,
        in_sqrt,
        in_sqrt_ap_vld,
        out_sqrt,
        out_sqrt_ap_vld
);

parameter    ap_ST_fsm_state1 = 74'd1;
parameter    ap_ST_fsm_state2 = 74'd2;
parameter    ap_ST_fsm_state3 = 74'd4;
parameter    ap_ST_fsm_state4 = 74'd8;
parameter    ap_ST_fsm_state5 = 74'd16;
parameter    ap_ST_fsm_state6 = 74'd32;
parameter    ap_ST_fsm_state7 = 74'd64;
parameter    ap_ST_fsm_state8 = 74'd128;
parameter    ap_ST_fsm_state9 = 74'd256;
parameter    ap_ST_fsm_state10 = 74'd512;
parameter    ap_ST_fsm_state11 = 74'd1024;
parameter    ap_ST_fsm_state12 = 74'd2048;
parameter    ap_ST_fsm_state13 = 74'd4096;
parameter    ap_ST_fsm_state14 = 74'd8192;
parameter    ap_ST_fsm_state15 = 74'd16384;
parameter    ap_ST_fsm_state16 = 74'd32768;
parameter    ap_ST_fsm_state17 = 74'd65536;
parameter    ap_ST_fsm_state18 = 74'd131072;
parameter    ap_ST_fsm_state19 = 74'd262144;
parameter    ap_ST_fsm_state20 = 74'd524288;
parameter    ap_ST_fsm_state21 = 74'd1048576;
parameter    ap_ST_fsm_state22 = 74'd2097152;
parameter    ap_ST_fsm_state23 = 74'd4194304;
parameter    ap_ST_fsm_state24 = 74'd8388608;
parameter    ap_ST_fsm_state25 = 74'd16777216;
parameter    ap_ST_fsm_state26 = 74'd33554432;
parameter    ap_ST_fsm_state27 = 74'd67108864;
parameter    ap_ST_fsm_state28 = 74'd134217728;
parameter    ap_ST_fsm_state29 = 74'd268435456;
parameter    ap_ST_fsm_state30 = 74'd536870912;
parameter    ap_ST_fsm_state31 = 74'd1073741824;
parameter    ap_ST_fsm_state32 = 74'd2147483648;
parameter    ap_ST_fsm_state33 = 74'd4294967296;
parameter    ap_ST_fsm_state34 = 74'd8589934592;
parameter    ap_ST_fsm_state35 = 74'd17179869184;
parameter    ap_ST_fsm_state36 = 74'd34359738368;
parameter    ap_ST_fsm_state37 = 74'd68719476736;
parameter    ap_ST_fsm_state38 = 74'd137438953472;
parameter    ap_ST_fsm_state39 = 74'd274877906944;
parameter    ap_ST_fsm_state40 = 74'd549755813888;
parameter    ap_ST_fsm_state41 = 74'd1099511627776;
parameter    ap_ST_fsm_state42 = 74'd2199023255552;
parameter    ap_ST_fsm_state43 = 74'd4398046511104;
parameter    ap_ST_fsm_state44 = 74'd8796093022208;
parameter    ap_ST_fsm_state45 = 74'd17592186044416;
parameter    ap_ST_fsm_state46 = 74'd35184372088832;
parameter    ap_ST_fsm_state47 = 74'd70368744177664;
parameter    ap_ST_fsm_state48 = 74'd140737488355328;
parameter    ap_ST_fsm_state49 = 74'd281474976710656;
parameter    ap_ST_fsm_state50 = 74'd562949953421312;
parameter    ap_ST_fsm_state51 = 74'd1125899906842624;
parameter    ap_ST_fsm_state52 = 74'd2251799813685248;
parameter    ap_ST_fsm_state53 = 74'd4503599627370496;
parameter    ap_ST_fsm_state54 = 74'd9007199254740992;
parameter    ap_ST_fsm_state55 = 74'd18014398509481984;
parameter    ap_ST_fsm_state56 = 74'd36028797018963968;
parameter    ap_ST_fsm_state57 = 74'd72057594037927936;
parameter    ap_ST_fsm_state58 = 74'd144115188075855872;
parameter    ap_ST_fsm_state59 = 74'd288230376151711744;
parameter    ap_ST_fsm_state60 = 74'd576460752303423488;
parameter    ap_ST_fsm_state61 = 74'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 74'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 74'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 74'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 74'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 74'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 74'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 74'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 74'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 74'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 74'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 74'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 74'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 74'd9444732965739290427392;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] sinc;
input  [0:0] EN1;
input  [0:0] EN2;
input  [0:0] EN3;
input  [0:0] EN4;
input  [0:0] EN5;
input  [0:0] EN6;
input  [63:0] vin_a;
input  [63:0] vin_b;
input  [63:0] vin_c;
input  [63:0] in_1;
input  [63:0] in_2;
input  [63:0] in_3;
output  [63:0] w_out;
output   w_out_ap_vld;
output  [63:0] theta_out;
output   theta_out_ap_vld;
output  [63:0] pll_alpha_out;
output   pll_alpha_out_ap_vld;
output  [63:0] pll_beta_out;
output   pll_beta_out_ap_vld;
output  [63:0] amp_vPos_out;
output   amp_vPos_out_ap_vld;
output  [63:0] Amp_vneg_out;
output   Amp_vneg_out_ap_vld;
output  [63:0] delta_out;
output   delta_out_ap_vld;
output  [63:0] v_alfa_in;
output   v_alfa_in_ap_vld;
output  [63:0] v_beta_in;
output   v_beta_in_ap_vld;
output  [63:0] Amp_vneg_raw_base_out;
output   Amp_vneg_raw_base_out_ap_vld;
output  [63:0] q_inv_d_out;
output   q_inv_d_out_ap_vld;
output  [63:0] v2_d_limpo_out;
output   v2_d_limpo_out_ap_vld;
output  [63:0] in_inv;
output   in_inv_ap_vld;
output  [63:0] out_inv;
output   out_inv_ap_vld;
output  [63:0] in_atan;
output   in_atan_ap_vld;
output  [63:0] out_atan;
output   out_atan_ap_vld;
output  [63:0] in_sqrt;
output   in_sqrt_ap_vld;
output  [63:0] out_sqrt;
output   out_sqrt_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg w_out_ap_vld;
reg theta_out_ap_vld;
reg pll_alpha_out_ap_vld;
reg pll_beta_out_ap_vld;
reg amp_vPos_out_ap_vld;
reg Amp_vneg_out_ap_vld;
reg delta_out_ap_vld;
reg v_alfa_in_ap_vld;
reg v_beta_in_ap_vld;
reg Amp_vneg_raw_base_out_ap_vld;
reg q_inv_d_out_ap_vld;
reg v2_d_limpo_out_ap_vld;
reg in_inv_ap_vld;
reg out_inv_ap_vld;
reg in_atan_ap_vld;
reg out_atan_ap_vld;
reg in_sqrt_ap_vld;
reg out_sqrt_ap_vld;

(* fsm_encoding = "none" *) reg   [73:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] aux_sinc_V;
reg   [63:0] theta1_V;
reg   [63:0] delta_V;
reg   [63:0] Amp_vneg_V;
reg   [63:0] v_alfa_V;
reg   [63:0] v_beta_V;
reg   [63:0] amp_vPos_V;
reg   [63:0] v2_d_limpo_V;
reg   [63:0] in_inv_aux_V;
reg   [63:0] in_atan_aux_V;
reg   [63:0] in_sqrt_aux_V;
reg   [63:0] wi_V;
reg   [63:0] v1_q_comp_V;
reg   [63:0] v1_d_comp_V;
reg   [63:0] w_V;
reg   [63:0] q_inv_d_V;
reg   [63:0] Amp_vneg_raw_base_V;
reg   [63:0] pll_alfa_V;
reg   [63:0] pll_beta_V;
reg   [63:0] out_inv_aux_V;
reg   [63:0] out_atan_aux_V;
reg   [63:0] out_sqrt_aux_V;
wire   [49:0] grp_sin_2000_fu_640_ap_return;
reg  signed [49:0] reg_658;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state64;
wire   [49:0] grp_cos_2000_fu_604_ap_return;
reg  signed [49:0] reg_662;
wire   [63:0] grp_INV_LUT_fu_629_ap_return;
reg   [63:0] reg_666;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state71;
reg   [63:0] reg_671;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state72;
reg   [0:0] tmp_10_reg_2136;
reg   [0:0] icmp_ln1494_reg_2126;
wire   [63:0] grp_SQRT_LUT_fu_647_ap_return;
wire    ap_CS_fsm_state55;
wire   [0:0] EN6_read_read_fu_262_p2;
wire   [0:0] EN5_read_read_fu_268_p2;
wire   [0:0] EN4_read_read_fu_274_p2;
wire   [0:0] EN2_read_read_fu_286_p2;
wire   [0:0] EN1_read_read_fu_292_p2;
wire   [0:0] xor_ln870_fu_692_p2;
reg   [0:0] xor_ln870_reg_1699;
reg   [63:0] x_V_reg_1738;
wire   [112:0] ret_V_5_fu_782_p2;
reg  signed [112:0] ret_V_5_reg_1750;
wire   [64:0] ret_V_6_fu_788_p2;
reg  signed [64:0] ret_V_6_reg_1755;
wire    ap_CS_fsm_state2;
wire   [63:0] shl_ln703_fu_812_p2;
reg   [63:0] shl_ln703_reg_1770;
wire    ap_CS_fsm_state5;
reg  signed [63:0] trunc_ln_reg_1777;
reg  signed [63:0] trunc_ln708_1_reg_1783;
wire   [49:0] grp_cos_2000_fu_611_ap_return;
reg  signed [49:0] r_V_12_reg_1789;
wire  signed [111:0] sext_ln1115_fu_850_p1;
reg  signed [111:0] sext_ln1115_reg_1794;
wire    ap_CS_fsm_state7;
wire  signed [111:0] sext_ln1118_2_fu_854_p1;
wire  signed [111:0] sext_ln1115_1_fu_863_p1;
reg  signed [111:0] sext_ln1115_1_reg_1807;
wire  signed [111:0] sext_ln1118_3_fu_867_p1;
wire   [111:0] grp_fu_857_p2;
reg   [111:0] r_V_31_reg_1820;
wire    ap_CS_fsm_state11;
wire   [111:0] grp_fu_870_p2;
reg   [111:0] r_V_32_reg_1826;
wire   [111:0] grp_fu_876_p2;
reg   [111:0] r_V_33_reg_1832;
wire   [111:0] grp_fu_882_p2;
reg   [111:0] r_V_34_reg_1838;
wire  signed [63:0] sub_ln703_fu_928_p2;
reg  signed [63:0] sub_ln703_reg_1844;
wire    ap_CS_fsm_state12;
wire  signed [63:0] r_V_27_fu_938_p2;
reg  signed [63:0] r_V_27_reg_1850;
reg   [63:0] tmp_1_reg_1857;
reg   [63:0] tmp_2_reg_1862;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [151:0] grp_fu_967_p2;
reg   [151:0] r_V_14_reg_1877;
wire    ap_CS_fsm_state17;
reg   [63:0] rhs_4_reg_1882;
wire   [111:0] grp_fu_976_p2;
reg   [111:0] r_V_15_reg_1887;
wire    ap_CS_fsm_state19;
wire  signed [111:0] sext_ln1118_4_fu_1023_p1;
reg  signed [63:0] trunc_ln708_9_reg_1908;
wire   [0:0] icmp_ln1496_fu_1075_p2;
reg   [0:0] icmp_ln1496_reg_1913;
wire    ap_CS_fsm_state20;
wire   [111:0] grp_fu_1026_p2;
reg   [111:0] r_V_11_reg_1923;
wire    ap_CS_fsm_state23;
wire   [111:0] grp_fu_1035_p2;
reg   [111:0] r_V_13_reg_1928;
reg  signed [63:0] r_V_1_reg_1933;
wire    ap_CS_fsm_state24;
wire   [111:0] ret_V_12_fu_1118_p2;
reg   [111:0] ret_V_12_reg_1938;
reg  signed [63:0] x_V_1_reg_1943;
wire   [93:0] grp_fu_1083_p2;
reg   [93:0] r_V_16_reg_1952;
wire   [63:0] select_ln1496_fu_1165_p3;
reg   [63:0] select_ln1496_reg_1957;
wire    ap_CS_fsm_state25;
wire  signed [63:0] sext_ln708_fu_1211_p1;
wire    ap_CS_fsm_state29;
wire   [63:0] sub_ln703_6_fu_1215_p2;
reg   [63:0] sub_ln703_6_reg_1978;
wire    ap_CS_fsm_state32;
wire   [63:0] grp_fu_682_p2;
wire    ap_CS_fsm_state35;
wire    ap_CS_fsm_state37;
wire   [63:0] sub_ln703_4_fu_1220_p2;
reg   [63:0] sub_ln703_4_reg_1993;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state41;
wire  signed [111:0] sext_ln1115_4_fu_1225_p1;
reg  signed [111:0] sext_ln1115_4_reg_2003;
wire    ap_CS_fsm_state42;
reg   [63:0] trunc_ln708_5_reg_2015;
wire    ap_CS_fsm_state46;
wire   [63:0] grp_ATAN_LUT_signed_fu_618_ap_return;
wire    ap_CS_fsm_state47;
wire    ap_CS_fsm_state49;
wire  signed [111:0] sext_ln1115_5_fu_1258_p1;
wire   [111:0] grp_fu_1254_p2;
reg   [111:0] r_V_19_reg_2036;
wire    ap_CS_fsm_state53;
wire   [111:0] grp_fu_1261_p2;
reg   [111:0] r_V_21_reg_2041;
reg   [63:0] trunc_ln708_6_reg_2046;
wire    ap_CS_fsm_state54;
wire   [64:0] ret_V_18_fu_1295_p2;
reg  signed [64:0] ret_V_18_reg_2051;
wire  signed [111:0] sext_ln1115_7_fu_1306_p1;
wire    ap_CS_fsm_state56;
wire   [64:0] ret_V_20_fu_1335_p2;
reg  signed [64:0] ret_V_20_reg_2067;
wire    ap_CS_fsm_state57;
wire   [111:0] grp_fu_1314_p2;
reg   [111:0] mul_ln1118_reg_2077;
wire    ap_CS_fsm_state59;
wire   [152:0] grp_fu_1322_p2;
reg   [152:0] r_V_22_reg_2082;
wire    ap_CS_fsm_state60;
reg   [63:0] trunc_ln708_7_reg_2087;
wire    ap_CS_fsm_state61;
wire   [154:0] grp_fu_1344_p2;
reg   [154:0] r_V_23_reg_2093;
reg  signed [63:0] r_V_24_reg_2098;
wire    ap_CS_fsm_state62;
wire   [63:0] add_ln703_1_fu_1451_p2;
reg   [63:0] add_ln703_1_reg_2104;
wire  signed [111:0] sext_ln1115_6_fu_1455_p1;
wire    ap_CS_fsm_state65;
wire   [0:0] icmp_ln1494_fu_1510_p2;
wire    ap_CS_fsm_state69;
wire   [63:0] add_ln703_2_fu_1515_p2;
reg   [63:0] add_ln703_2_reg_2130;
wire   [0:0] tmp_10_fu_1526_p3;
wire   [63:0] sub_ln703_8_fu_1533_p2;
reg   [63:0] sub_ln703_8_reg_2140;
wire   [63:0] y_V_5_fu_1544_p2;
wire    grp_cos_2000_fu_604_ap_start;
wire    grp_cos_2000_fu_604_ap_done;
wire    grp_cos_2000_fu_604_ap_idle;
wire    grp_cos_2000_fu_604_ap_ready;
reg   [63:0] grp_cos_2000_fu_604_theta_in;
wire    grp_cos_2000_fu_611_ap_start;
wire    grp_cos_2000_fu_611_ap_done;
wire    grp_cos_2000_fu_611_ap_idle;
wire    grp_cos_2000_fu_611_ap_ready;
wire    grp_ATAN_LUT_signed_fu_618_ap_start;
wire    grp_ATAN_LUT_signed_fu_618_ap_done;
wire    grp_ATAN_LUT_signed_fu_618_ap_idle;
wire    grp_ATAN_LUT_signed_fu_618_ap_ready;
reg   [63:0] grp_ATAN_LUT_signed_fu_618_x;
wire    grp_INV_LUT_fu_629_ap_start;
wire    grp_INV_LUT_fu_629_ap_done;
wire    grp_INV_LUT_fu_629_ap_idle;
wire    grp_INV_LUT_fu_629_ap_ready;
reg   [63:0] grp_INV_LUT_fu_629_x;
wire    grp_sin_2000_fu_640_ap_start;
wire    grp_sin_2000_fu_640_ap_done;
wire    grp_sin_2000_fu_640_ap_idle;
wire    grp_sin_2000_fu_640_ap_ready;
reg   [63:0] grp_sin_2000_fu_640_theta_in;
wire    grp_SQRT_LUT_fu_647_ap_start;
wire    grp_SQRT_LUT_fu_647_ap_done;
wire    grp_SQRT_LUT_fu_647_ap_idle;
wire    grp_SQRT_LUT_fu_647_ap_ready;
reg   [63:0] grp_SQRT_LUT_fu_647_x;
reg  signed [63:0] empty_reg_430;
reg   [63:0] lhs_V_10_reg_445;
reg    ap_block_state49_on_subcall_done;
reg   [63:0] lhs_V_13_reg_459;
reg    ap_predicate_op359_call_state55;
reg    ap_block_state55_on_subcall_done;
reg   [63:0] in_inv_aux_V_loc_0_reg_472;
reg   [63:0] in_inv_aux_V_loc_1_reg_484;
reg    ap_predicate_op445_call_state72;
reg    ap_block_state72_on_subcall_done;
reg   [63:0] y_V_6_reg_494;
reg   [63:0] ap_phi_mux_theta1_V_loc_0_phi_fu_506_p4;
reg   [63:0] theta1_V_loc_0_reg_503;
wire    ap_CS_fsm_state74;
reg    ap_block_state74_on_subcall_done;
reg   [63:0] ap_phi_mux_delta_V_loc_0_phi_fu_516_p4;
reg   [63:0] delta_V_loc_0_reg_513;
reg   [63:0] ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_526_p4;
reg   [63:0] Amp_vneg_V_loc_0_reg_523;
reg   [63:0] ap_phi_mux_v_alfa_V_loc_0_phi_fu_536_p4;
reg   [63:0] v_alfa_V_loc_0_reg_533;
reg   [63:0] ap_phi_mux_v_beta_V_loc_0_phi_fu_546_p4;
reg   [63:0] v_beta_V_loc_0_reg_543;
reg   [63:0] ap_phi_mux_amp_vPos_V_loc_0_phi_fu_556_p4;
reg   [63:0] amp_vPos_V_loc_0_reg_553;
reg   [63:0] ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_566_p4;
reg   [63:0] v2_d_limpo_V_loc_0_reg_563;
reg   [63:0] ap_phi_mux_in_inv_aux_V_loc_2_phi_fu_576_p4;
reg   [63:0] in_inv_aux_V_loc_2_reg_573;
wire   [63:0] select_ln317_fu_1566_p3;
reg   [63:0] ap_phi_mux_in_atan_aux_V_loc_0_phi_fu_587_p4;
reg   [63:0] in_atan_aux_V_loc_0_reg_584;
wire   [63:0] select_ln333_fu_1597_p3;
reg   [63:0] ap_phi_mux_in_sqrt_aux_V_loc_0_phi_fu_597_p4;
reg   [63:0] in_sqrt_aux_V_loc_0_reg_594;
reg    grp_cos_2000_fu_604_ap_start_reg;
wire    ap_CS_fsm_state63;
reg    grp_cos_2000_fu_611_ap_start_reg;
reg    grp_ATAN_LUT_signed_fu_618_ap_start_reg;
wire    ap_CS_fsm_state48;
reg    grp_INV_LUT_fu_629_ap_start_reg;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state36;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state70;
wire    ap_CS_fsm_state73;
reg    grp_sin_2000_fu_640_ap_start_reg;
reg    grp_SQRT_LUT_fu_647_ap_start_reg;
reg    ap_block_state6_on_subcall_done;
reg   [63:0] ap_sig_allocacmp_out_inv_aux_V_load;
reg   [63:0] ap_sig_allocacmp_out_atan_aux_V_load;
reg   [63:0] ap_sig_allocacmp_out_sqrt_aux_V_load;
wire  signed [64:0] sext_ln703_1_fu_748_p1;
wire  signed [64:0] sext_ln703_fu_744_p1;
wire   [64:0] ret_V_fu_752_p2;
wire   [111:0] lhs_fu_766_p3;
wire   [111:0] r_V_30_fu_758_p3;
wire  signed [112:0] sext_ln1193_fu_774_p1;
wire  signed [112:0] sext_ln1193_1_fu_778_p1;
wire   [48:0] grp_fu_797_p1;
wire   [48:0] grp_fu_806_p1;
wire   [159:0] grp_fu_797_p2;
wire   [111:0] grp_fu_806_p2;
wire  signed [63:0] grp_fu_857_p0;
wire  signed [49:0] grp_fu_857_p1;
wire  signed [63:0] grp_fu_870_p0;
wire  signed [49:0] grp_fu_870_p1;
wire  signed [49:0] grp_fu_876_p0;
wire  signed [63:0] grp_fu_876_p1;
wire  signed [63:0] grp_fu_882_p0;
wire  signed [49:0] grp_fu_882_p1;
wire   [111:0] ret_V_7_fu_888_p2;
wire   [111:0] ret_V_8_fu_902_p2;
wire   [63:0] trunc_ln708_2_fu_892_p4;
wire   [63:0] trunc_ln708_3_fu_906_p4;
wire   [111:0] ret_V_9_fu_916_p2;
wire   [111:0] ret_V_10_fu_920_p2;
wire   [88:0] grp_fu_967_p1;
wire   [53:0] grp_fu_976_p1;
wire   [159:0] lhs_V_5_fu_986_p3;
wire  signed [159:0] sext_ln703_2_fu_994_p1;
wire   [159:0] ret_V_13_fu_997_p2;
wire  signed [63:0] sext_ln1118_4_fu_1023_p0;
wire  signed [63:0] grp_fu_1026_p0;
wire  signed [63:0] grp_fu_1035_p0;
wire   [63:0] ret_V_22_fu_1041_p2;
wire   [111:0] lhs_V_7_fu_1046_p3;
wire   [111:0] ret_V_15_fu_1054_p2;
wire   [30:0] grp_fu_1083_p1;
wire   [111:0] lhs_V_2_fu_1089_p3;
wire   [111:0] ret_V_11_fu_1096_p2;
wire   [111:0] lhs_V_3_fu_1111_p3;
wire   [111:0] lhs_V_9_fu_1139_p3;
wire  signed [111:0] sext_ln703_3_fu_1146_p1;
wire   [111:0] ret_V_16_fu_1149_p2;
wire   [63:0] trunc_ln708_s_fu_1155_p4;
wire   [45:0] grp_fu_1181_p1;
wire   [108:0] grp_fu_1181_p2;
wire   [60:0] trunc_ln708_4_fu_1201_p4;
wire   [111:0] grp_fu_1232_p2;
wire  signed [63:0] grp_fu_1254_p0;
wire  signed [63:0] grp_fu_1254_p1;
wire  signed [63:0] grp_fu_1261_p0;
wire  signed [63:0] grp_fu_1261_p1;
wire   [111:0] ret_V_17_fu_1267_p2;
wire  signed [63:0] sext_ln703_5_fu_1292_p0;
wire  signed [64:0] sext_ln703_4_fu_1288_p1;
wire  signed [64:0] sext_ln703_5_fu_1292_p1;
wire  signed [49:0] grp_fu_1309_p0;
wire  signed [63:0] grp_fu_1309_p1;
wire  signed [63:0] grp_fu_1314_p0;
wire  signed [49:0] grp_fu_1314_p1;
wire   [88:0] grp_fu_1322_p1;
wire  signed [63:0] sext_ln703_8_fu_1332_p0;
wire  signed [64:0] sext_ln703_7_fu_1328_p1;
wire  signed [64:0] sext_ln703_8_fu_1332_p1;
wire   [90:0] grp_fu_1344_p1;
wire   [111:0] grp_fu_1309_p2;
wire   [111:0] r_V_29_fu_1366_p2;
wire  signed [63:0] lhs_V_12_fu_1387_p1;
wire   [159:0] lhs_V_12_fu_1387_p3;
wire  signed [159:0] sext_ln703_6_fu_1394_p1;
wire   [159:0] ret_V_19_fu_1397_p2;
wire  signed [63:0] lhs_V_15_fu_1419_p1;
wire   [159:0] lhs_V_15_fu_1419_p3;
wire  signed [159:0] sext_ln703_9_fu_1426_p1;
wire   [159:0] ret_V_21_fu_1429_p2;
wire  signed [63:0] grp_fu_1462_p1;
wire  signed [63:0] grp_fu_1472_p1;
wire   [111:0] grp_fu_1462_p2;
wire   [111:0] grp_fu_1472_p2;
wire   [0:0] icmp_ln1494_10_fu_1556_p2;
wire   [63:0] add_ln703_3_fu_1561_p2;
wire   [0:0] icmp_ln1494_11_fu_1587_p2;
wire   [63:0] add_ln703_4_fu_1592_p2;
reg    grp_fu_797_ce;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_fu_806_ce;
reg    grp_fu_976_ce;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire   [0:0] tmp_9_fu_1187_p3;
wire   [0:0] tmp_fu_1194_p3;
reg    grp_fu_1254_ce;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state51;
wire    ap_CS_fsm_state52;
reg    grp_fu_1261_ce;
reg    grp_fu_1309_ce;
wire    ap_CS_fsm_state58;
reg    grp_fu_1314_ce;
reg   [73:0] ap_NS_fsm;
reg    ap_block_state64_on_subcall_done;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 74'd1;
#0 aux_sinc_V = 1'd0;
#0 theta1_V = 64'd0;
#0 delta_V = 64'd0;
#0 Amp_vneg_V = 64'd0;
#0 v_alfa_V = 64'd0;
#0 v_beta_V = 64'd0;
#0 amp_vPos_V = 64'd0;
#0 v2_d_limpo_V = 64'd0;
#0 in_inv_aux_V = 64'd0;
#0 in_atan_aux_V = 64'd0;
#0 in_sqrt_aux_V = 64'd0;
#0 wi_V = 64'd0;
#0 v1_q_comp_V = 64'd0;
#0 v1_d_comp_V = 64'd0;
#0 w_V = 64'd0;
#0 q_inv_d_V = 64'd0;
#0 Amp_vneg_raw_base_V = 64'd0;
#0 pll_alfa_V = 64'd0;
#0 pll_beta_V = 64'd0;
#0 out_inv_aux_V = 64'd0;
#0 out_atan_aux_V = 64'd0;
#0 out_sqrt_aux_V = 64'd0;
#0 grp_cos_2000_fu_604_ap_start_reg = 1'b0;
#0 grp_cos_2000_fu_611_ap_start_reg = 1'b0;
#0 grp_ATAN_LUT_signed_fu_618_ap_start_reg = 1'b0;
#0 grp_INV_LUT_fu_629_ap_start_reg = 1'b0;
#0 grp_sin_2000_fu_640_ap_start_reg = 1'b0;
#0 grp_SQRT_LUT_fu_647_ap_start_reg = 1'b0;
end

PLL2026_x64_cos_2000 grp_cos_2000_fu_604(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cos_2000_fu_604_ap_start),
    .ap_done(grp_cos_2000_fu_604_ap_done),
    .ap_idle(grp_cos_2000_fu_604_ap_idle),
    .ap_ready(grp_cos_2000_fu_604_ap_ready),
    .theta_in(grp_cos_2000_fu_604_theta_in),
    .ap_return(grp_cos_2000_fu_604_ap_return)
);

PLL2026_x64_cos_2000 grp_cos_2000_fu_611(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cos_2000_fu_611_ap_start),
    .ap_done(grp_cos_2000_fu_611_ap_done),
    .ap_idle(grp_cos_2000_fu_611_ap_idle),
    .ap_ready(grp_cos_2000_fu_611_ap_ready),
    .theta_in(shl_ln703_reg_1770),
    .ap_return(grp_cos_2000_fu_611_ap_return)
);

PLL2026_x64_ATAN_LUT_signed grp_ATAN_LUT_signed_fu_618(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ATAN_LUT_signed_fu_618_ap_start),
    .ap_done(grp_ATAN_LUT_signed_fu_618_ap_done),
    .ap_idle(grp_ATAN_LUT_signed_fu_618_ap_idle),
    .ap_ready(grp_ATAN_LUT_signed_fu_618_ap_ready),
    .x(grp_ATAN_LUT_signed_fu_618_x),
    .ap_return(grp_ATAN_LUT_signed_fu_618_ap_return)
);

PLL2026_x64_INV_LUT grp_INV_LUT_fu_629(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_INV_LUT_fu_629_ap_start),
    .ap_done(grp_INV_LUT_fu_629_ap_done),
    .ap_idle(grp_INV_LUT_fu_629_ap_idle),
    .ap_ready(grp_INV_LUT_fu_629_ap_ready),
    .x(grp_INV_LUT_fu_629_x),
    .ap_return(grp_INV_LUT_fu_629_ap_return)
);

PLL2026_x64_sin_2000 grp_sin_2000_fu_640(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_640_ap_start),
    .ap_done(grp_sin_2000_fu_640_ap_done),
    .ap_idle(grp_sin_2000_fu_640_ap_idle),
    .ap_ready(grp_sin_2000_fu_640_ap_ready),
    .theta_in(grp_sin_2000_fu_640_theta_in),
    .ap_return(grp_sin_2000_fu_640_ap_return)
);

PLL2026_x64_SQRT_LUT grp_SQRT_LUT_fu_647(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_SQRT_LUT_fu_647_ap_start),
    .ap_done(grp_SQRT_LUT_fu_647_ap_done),
    .ap_idle(grp_SQRT_LUT_fu_647_ap_idle),
    .ap_ready(grp_SQRT_LUT_fu_647_ap_ready),
    .x(grp_SQRT_LUT_fu_647_x),
    .ap_return(grp_SQRT_LUT_fu_647_ap_return)
);

PLL2026_x64_mul_113s_49ns_160_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 113 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 160 ))
mul_113s_49ns_160_5_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_5_reg_1750),
    .din1(grp_fu_797_p1),
    .ce(grp_fu_797_ce),
    .dout(grp_fu_797_p2)
);

PLL2026_x64_mul_65s_49ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 112 ))
mul_65s_49ns_112_5_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_6_reg_1755),
    .din1(grp_fu_806_p1),
    .ce(grp_fu_806_ce),
    .dout(grp_fu_806_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_857_p0),
    .din1(grp_fu_857_p1),
    .ce(1'b1),
    .dout(grp_fu_857_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_870_p0),
    .din1(grp_fu_870_p1),
    .ce(1'b1),
    .dout(grp_fu_870_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_876_p0),
    .din1(grp_fu_876_p1),
    .ce(1'b1),
    .dout(grp_fu_876_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_882_p0),
    .din1(grp_fu_882_p1),
    .ce(1'b1),
    .dout(grp_fu_882_p2)
);

PLL2026_x64_mul_64s_89ns_152_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 89 ),
    .dout_WIDTH( 152 ))
mul_64s_89ns_152_5_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln703_reg_1844),
    .din1(grp_fu_967_p1),
    .ce(1'b1),
    .dout(grp_fu_967_p2)
);

PLL2026_x64_mul_64s_54ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 112 ))
mul_64s_54ns_112_5_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln703_reg_1844),
    .din1(grp_fu_976_p1),
    .ce(grp_fu_976_ce),
    .dout(grp_fu_976_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1026_p0),
    .din1(reg_658),
    .ce(1'b1),
    .dout(grp_fu_1026_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1035_p0),
    .din1(r_V_12_reg_1789),
    .ce(1'b1),
    .dout(grp_fu_1035_p2)
);

PLL2026_x64_mul_64s_31ns_94_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 94 ))
mul_64s_31ns_94_5_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln708_9_reg_1908),
    .din1(grp_fu_1083_p1),
    .ce(1'b1),
    .dout(grp_fu_1083_p2)
);

PLL2026_x64_mul_64s_46ns_109_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 46 ),
    .dout_WIDTH( 109 ))
mul_64s_46ns_109_5_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(x_V_1_reg_1943),
    .din1(grp_fu_1181_p1),
    .ce(1'b1),
    .dout(grp_fu_1181_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_1_reg_1933),
    .din1(empty_reg_430),
    .ce(1'b1),
    .dout(grp_fu_1232_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1254_p0),
    .din1(grp_fu_1254_p1),
    .ce(grp_fu_1254_ce),
    .dout(grp_fu_1254_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1261_p0),
    .din1(grp_fu_1261_p1),
    .ce(grp_fu_1261_ce),
    .dout(grp_fu_1261_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1309_p0),
    .din1(grp_fu_1309_p1),
    .ce(grp_fu_1309_ce),
    .dout(grp_fu_1309_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1314_p0),
    .din1(grp_fu_1314_p1),
    .ce(grp_fu_1314_ce),
    .dout(grp_fu_1314_p2)
);

PLL2026_x64_mul_65s_89ns_153_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 89 ),
    .dout_WIDTH( 153 ))
mul_65s_89ns_153_5_1_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_18_reg_2051),
    .din1(grp_fu_1322_p1),
    .ce(1'b1),
    .dout(grp_fu_1322_p2)
);

PLL2026_x64_mul_65s_91ns_155_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 91 ),
    .dout_WIDTH( 155 ))
mul_65s_91ns_155_5_1_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_20_reg_2067),
    .din1(grp_fu_1344_p1),
    .ce(1'b1),
    .dout(grp_fu_1344_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_658),
    .din1(grp_fu_1462_p1),
    .ce(1'b1),
    .dout(grp_fu_1462_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_662),
    .din1(grp_fu_1472_p1),
    .ce(1'b1),
    .dout(grp_fu_1472_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ATAN_LUT_signed_fu_618_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state48) | ((1'd1 == EN5_read_read_fu_268_p2) & (1'b1 == ap_CS_fsm_state46) & (1'd0 == EN2_read_read_fu_286_p2)) | ((1'b0 == ap_block_state72_on_subcall_done) & (1'b1 == ap_CS_fsm_state72)))) begin
            grp_ATAN_LUT_signed_fu_618_ap_start_reg <= 1'b1;
        end else if ((grp_ATAN_LUT_signed_fu_618_ap_ready == 1'b1)) begin
            grp_ATAN_LUT_signed_fu_618_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_INV_LUT_fu_629_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state30))) begin
            grp_INV_LUT_fu_629_ap_start_reg <= 1'b1;
        end else if ((grp_INV_LUT_fu_629_ap_ready == 1'b1)) begin
            grp_INV_LUT_fu_629_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_SQRT_LUT_fu_647_ap_start_reg <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_state72_on_subcall_done) & (1'b1 == ap_CS_fsm_state72)) | ((1'd1 == EN3) & (1'b1 == ap_CS_fsm_state54)) | ((1'd1 == EN6) & (1'b1 == ap_CS_fsm_state54) & (1'd0 == EN3)))) begin
            grp_SQRT_LUT_fu_647_ap_start_reg <= 1'b1;
        end else if ((grp_SQRT_LUT_fu_647_ap_ready == 1'b1)) begin
            grp_SQRT_LUT_fu_647_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cos_2000_fu_604_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_cos_2000_fu_604_ap_start_reg <= 1'b1;
        end else if ((grp_cos_2000_fu_604_ap_ready == 1'b1)) begin
            grp_cos_2000_fu_604_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cos_2000_fu_611_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_cos_2000_fu_611_ap_start_reg <= 1'b1;
        end else if ((grp_cos_2000_fu_611_ap_ready == 1'b1)) begin
            grp_cos_2000_fu_611_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_640_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_sin_2000_fu_640_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_640_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_640_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        Amp_vneg_V_loc_0_reg_523 <= Amp_vneg_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        Amp_vneg_V_loc_0_reg_523 <= r_V_24_reg_2098;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        amp_vPos_V_loc_0_reg_553 <= amp_vPos_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        amp_vPos_V_loc_0_reg_553 <= r_V_27_reg_1850;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        delta_V_loc_0_reg_513 <= delta_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        delta_V_loc_0_reg_513 <= trunc_ln708_7_reg_2087;
    end
end

always @ (posedge ap_clk) begin
    if ((((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37)) | ((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31)))) begin
        empty_reg_430 <= grp_INV_LUT_fu_629_ap_return;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state35))) begin
        empty_reg_430 <= grp_fu_682_p2;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        empty_reg_430 <= sext_ln708_fu_1211_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_atan_aux_V_loc_0_reg_584 <= in_atan_aux_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        in_atan_aux_V_loc_0_reg_584 <= select_ln317_fu_1566_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        if ((icmp_ln1494_fu_1510_p2 == 1'd1)) begin
            in_inv_aux_V <= 64'd2814749767106;
        end else if ((icmp_ln1494_fu_1510_p2 == 1'd0)) begin
            in_inv_aux_V <= add_ln703_2_fu_1515_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        if (((tmp_10_fu_1526_p3 == 1'd0) & (icmp_ln1494_fu_1510_p2 == 1'd0))) begin
            in_inv_aux_V_loc_0_reg_472 <= add_ln703_2_fu_1515_p2;
        end else if ((icmp_ln1494_fu_1510_p2 == 1'd1)) begin
            in_inv_aux_V_loc_0_reg_472 <= 64'd2814749767106;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state72_on_subcall_done) & (1'b1 == ap_CS_fsm_state72))) begin
        if (((icmp_ln1494_reg_2126 == 1'd0) & (tmp_10_reg_2136 == 1'd1))) begin
            in_inv_aux_V_loc_1_reg_484 <= add_ln703_2_reg_2130;
        end else if (((icmp_ln1494_reg_2126 == 1'd1) | (tmp_10_reg_2136 == 1'd0))) begin
            in_inv_aux_V_loc_1_reg_484 <= in_inv_aux_V_loc_0_reg_472;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_inv_aux_V_loc_2_reg_573 <= in_inv_aux_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        in_inv_aux_V_loc_2_reg_573 <= in_inv_aux_V_loc_1_reg_484;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        in_sqrt_aux_V_loc_0_reg_594 <= in_sqrt_aux_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        in_sqrt_aux_V_loc_0_reg_594 <= select_ln333_fu_1597_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state46) & (1'd0 == EN2_read_read_fu_286_p2) & (1'd0 == EN5_read_read_fu_268_p2))) begin
        lhs_V_10_reg_445 <= 64'd0;
    end else if ((((1'b0 == ap_block_state49_on_subcall_done) & (1'd1 == EN2) & (1'b1 == ap_CS_fsm_state49)) | ((grp_ATAN_LUT_signed_fu_618_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state47)))) begin
        lhs_V_10_reg_445 <= grp_ATAN_LUT_signed_fu_618_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state54) & (1'd0 == EN6_read_read_fu_262_p2) & (1'd0 == EN3))) begin
        lhs_V_13_reg_459 <= 64'd0;
    end else if ((((1'b0 == ap_block_state55_on_subcall_done) & (1'd1 == EN3) & (1'b1 == ap_CS_fsm_state55)) | ((1'b0 == ap_block_state55_on_subcall_done) & (1'd1 == EN6) & (1'b1 == ap_CS_fsm_state55) & (1'd0 == EN3)))) begin
        lhs_V_13_reg_459 <= grp_SQRT_LUT_fu_647_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        theta1_V_loc_0_reg_503 <= theta1_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        theta1_V_loc_0_reg_503 <= select_ln1496_reg_1957;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v2_d_limpo_V_loc_0_reg_563 <= v2_d_limpo_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        v2_d_limpo_V_loc_0_reg_563 <= x_V_1_reg_1943;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v_alfa_V_loc_0_reg_533 <= v_alfa_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        v_alfa_V_loc_0_reg_533 <= trunc_ln_reg_1777;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v_beta_V_loc_0_reg_543 <= v_beta_V;
    end else if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        v_beta_V_loc_0_reg_543 <= trunc_ln708_1_reg_1783;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state72_on_subcall_done) & (1'b1 == ap_CS_fsm_state72))) begin
        if (((icmp_ln1494_reg_2126 == 1'd0) & (tmp_10_reg_2136 == 1'd1))) begin
            y_V_6_reg_494 <= y_V_5_fu_1544_p2;
        end else if (((icmp_ln1494_reg_2126 == 1'd1) | (tmp_10_reg_2136 == 1'd0))) begin
            y_V_6_reg_494 <= grp_INV_LUT_fu_629_ap_return;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state62)) begin
        Amp_vneg_V <= {{ret_V_21_fu_1429_p2[159:96]}};
        add_ln703_1_reg_2104 <= add_ln703_1_fu_1451_p2;
        r_V_24_reg_2098 <= {{ret_V_21_fu_1429_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        Amp_vneg_raw_base_V <= {{ret_V_17_fu_1267_p2[111:48]}};
        trunc_ln708_6_reg_2046 <= {{ret_V_17_fu_1267_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1494_fu_1510_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state69))) begin
        add_ln703_2_reg_2130 <= add_ln703_2_fu_1515_p2;
        tmp_10_reg_2136 <= in_inv_aux_V[32'd63];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state55_on_subcall_done) & (1'b1 == ap_CS_fsm_state55))) begin
        amp_vPos_V <= r_V_27_reg_1850;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        aux_sinc_V <= sinc;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        delta_V <= {{ret_V_19_fu_1397_p2[159:96]}};
        r_V_23_reg_2093 <= grp_fu_1344_p2;
        trunc_ln708_7_reg_2087 <= {{ret_V_19_fu_1397_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        icmp_ln1494_reg_2126 <= icmp_ln1494_fu_1510_p2;
        v1_d_comp_V <= {{grp_fu_1472_p2[111:48]}};
        v1_q_comp_V <= {{grp_fu_1462_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        icmp_ln1496_reg_1913 <= icmp_ln1496_fu_1075_p2;
        trunc_ln708_9_reg_1908 <= {{ret_V_15_fu_1054_p2[111:48]}};
        w_V <= {{ret_V_15_fu_1054_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        in_atan_aux_V <= select_ln317_fu_1566_p3;
        in_sqrt_aux_V <= select_ln333_fu_1597_p3;
        out_atan_aux_V <= grp_ATAN_LUT_signed_fu_618_ap_return;
        out_inv_aux_V <= y_V_6_reg_494;
        out_sqrt_aux_V <= grp_SQRT_LUT_fu_647_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        mul_ln1118_reg_2077 <= grp_fu_1314_p2;
        pll_alfa_V <= {{grp_fu_1309_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state60)) begin
        pll_beta_V <= {{r_V_29_fu_1366_p2[111:48]}};
        r_V_22_reg_2082 <= grp_fu_1322_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state46)) begin
        q_inv_d_V <= {{grp_fu_1232_p2[111:48]}};
        trunc_ln708_5_reg_2015 <= {{grp_fu_1232_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        r_V_11_reg_1923 <= grp_fu_1026_p2;
        r_V_13_reg_1928 <= grp_fu_1035_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_V_12_reg_1789 <= grp_cos_2000_fu_611_ap_return;
        trunc_ln708_1_reg_1783 <= {{grp_fu_806_p2[111:48]}};
        trunc_ln_reg_1777 <= {{grp_fu_797_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        r_V_14_reg_1877 <= grp_fu_967_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        r_V_15_reg_1887 <= grp_fu_976_p2;
        rhs_4_reg_1882 <= {{ret_V_13_fu_997_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1496_reg_1913 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        r_V_16_reg_1952 <= grp_fu_1083_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state53)) begin
        r_V_19_reg_2036 <= grp_fu_1254_p2;
        r_V_21_reg_2041 <= grp_fu_1261_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        r_V_1_reg_1933 <= {{ret_V_11_fu_1096_p2[111:48]}};
        ret_V_12_reg_1938 <= ret_V_12_fu_1118_p2;
        v2_d_limpo_V <= {{ret_V_12_fu_1118_p2[111:48]}};
        x_V_1_reg_1943 <= {{ret_V_12_fu_1118_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        r_V_27_reg_1850 <= r_V_27_fu_938_p2;
        sub_ln703_reg_1844 <= sub_ln703_fu_928_p2;
        tmp_1_reg_1857 <= {{ret_V_9_fu_916_p2[111:48]}};
        tmp_2_reg_1862 <= {{ret_V_10_fu_920_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        r_V_31_reg_1820 <= grp_fu_857_p2;
        r_V_32_reg_1826 <= grp_fu_870_p2;
        r_V_33_reg_1832 <= grp_fu_876_p2;
        r_V_34_reg_1838 <= grp_fu_882_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_658 <= grp_sin_2000_fu_640_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_662 <= grp_cos_2000_fu_604_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state71) | (1'b1 == ap_CS_fsm_state31))) begin
        reg_666 <= grp_INV_LUT_fu_629_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state34) | ((1'b1 == ap_CS_fsm_state72) & ((icmp_ln1494_reg_2126 == 1'd1) | (tmp_10_reg_2136 == 1'd0))))) begin
        reg_671 <= grp_INV_LUT_fu_629_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        ret_V_18_reg_2051 <= ret_V_18_fu_1295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        ret_V_20_reg_2067 <= ret_V_20_fu_1335_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((xor_ln870_fu_692_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ret_V_5_reg_1750[112 : 47] <= ret_V_5_fu_782_p2[112 : 47];
        ret_V_6_reg_1755 <= ret_V_6_fu_788_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        select_ln1496_reg_1957 <= select_ln1496_fu_1165_p3;
        theta1_V <= select_ln1496_fu_1165_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sext_ln1115_1_reg_1807 <= sext_ln1115_1_fu_863_p1;
        sext_ln1115_reg_1794 <= sext_ln1115_fu_850_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        sext_ln1115_4_reg_2003 <= sext_ln1115_4_fu_1225_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shl_ln703_reg_1770[63 : 1] <= shl_ln703_fu_812_p2[63 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        sub_ln703_4_reg_1993 <= sub_ln703_4_fu_1220_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        sub_ln703_6_reg_1978 <= sub_ln703_6_fu_1215_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_10_fu_1526_p3 == 1'd1) & (icmp_ln1494_fu_1510_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state69))) begin
        sub_ln703_8_reg_2140 <= sub_ln703_8_fu_1533_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
        v_alfa_V <= {{grp_fu_797_p2[159:96]}};
        v_beta_V <= {{grp_fu_806_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sin_2000_fu_640_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
        wi_V <= {{ret_V_13_fu_997_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        x_V_reg_1738 <= in_inv_aux_V;
        xor_ln870_reg_1699 <= xor_ln870_fu_692_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        Amp_vneg_out_ap_vld = 1'b1;
    end else begin
        Amp_vneg_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        Amp_vneg_raw_base_out_ap_vld = 1'b1;
    end else begin
        Amp_vneg_raw_base_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        amp_vPos_out_ap_vld = 1'b1;
    end else begin
        amp_vPos_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_526_p4 = r_V_24_reg_2098;
    end else begin
        ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_526_p4 = Amp_vneg_V_loc_0_reg_523;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_amp_vPos_V_loc_0_phi_fu_556_p4 = r_V_27_reg_1850;
    end else begin
        ap_phi_mux_amp_vPos_V_loc_0_phi_fu_556_p4 = amp_vPos_V_loc_0_reg_553;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_delta_V_loc_0_phi_fu_516_p4 = trunc_ln708_7_reg_2087;
    end else begin
        ap_phi_mux_delta_V_loc_0_phi_fu_516_p4 = delta_V_loc_0_reg_513;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_in_atan_aux_V_loc_0_phi_fu_587_p4 = select_ln317_fu_1566_p3;
    end else begin
        ap_phi_mux_in_atan_aux_V_loc_0_phi_fu_587_p4 = in_atan_aux_V_loc_0_reg_584;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_in_inv_aux_V_loc_2_phi_fu_576_p4 = in_inv_aux_V_loc_1_reg_484;
    end else begin
        ap_phi_mux_in_inv_aux_V_loc_2_phi_fu_576_p4 = in_inv_aux_V_loc_2_reg_573;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_in_sqrt_aux_V_loc_0_phi_fu_597_p4 = select_ln333_fu_1597_p3;
    end else begin
        ap_phi_mux_in_sqrt_aux_V_loc_0_phi_fu_597_p4 = in_sqrt_aux_V_loc_0_reg_594;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_theta1_V_loc_0_phi_fu_506_p4 = select_ln1496_reg_1957;
    end else begin
        ap_phi_mux_theta1_V_loc_0_phi_fu_506_p4 = theta1_V_loc_0_reg_503;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_566_p4 = x_V_1_reg_1943;
    end else begin
        ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_566_p4 = v2_d_limpo_V_loc_0_reg_563;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_v_alfa_V_loc_0_phi_fu_536_p4 = trunc_ln_reg_1777;
    end else begin
        ap_phi_mux_v_alfa_V_loc_0_phi_fu_536_p4 = v_alfa_V_loc_0_reg_533;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_phi_mux_v_beta_V_loc_0_phi_fu_546_p4 = trunc_ln708_1_reg_1783;
    end else begin
        ap_phi_mux_v_beta_V_loc_0_phi_fu_546_p4 = v_beta_V_loc_0_reg_543;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_sig_allocacmp_out_atan_aux_V_load = grp_ATAN_LUT_signed_fu_618_ap_return;
    end else begin
        ap_sig_allocacmp_out_atan_aux_V_load = out_atan_aux_V;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_sig_allocacmp_out_inv_aux_V_load = y_V_6_reg_494;
    end else begin
        ap_sig_allocacmp_out_inv_aux_V_load = out_inv_aux_V;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        ap_sig_allocacmp_out_sqrt_aux_V_load = grp_SQRT_LUT_fu_647_ap_return;
    end else begin
        ap_sig_allocacmp_out_sqrt_aux_V_load = out_sqrt_aux_V;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        delta_out_ap_vld = 1'b1;
    end else begin
        delta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        grp_ATAN_LUT_signed_fu_618_x = in_atan_aux_V;
    end else if (((1'd1 == EN2) & (1'b1 == ap_CS_fsm_state49))) begin
        grp_ATAN_LUT_signed_fu_618_x = trunc_ln708_5_reg_2015;
    end else if ((1'b1 == ap_CS_fsm_state47)) begin
        grp_ATAN_LUT_signed_fu_618_x = in_2;
    end else begin
        grp_ATAN_LUT_signed_fu_618_x = 'bx;
    end
end

always @ (*) begin
    if (((ap_predicate_op445_call_state72 == 1'b1) & (1'b1 == ap_CS_fsm_state72))) begin
        grp_INV_LUT_fu_629_x = x_V_reg_1738;
    end else if ((1'b1 == ap_CS_fsm_state71)) begin
        grp_INV_LUT_fu_629_x = sub_ln703_8_reg_2140;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_INV_LUT_fu_629_x = sub_ln703_4_reg_1993;
    end else if ((1'b1 == ap_CS_fsm_state37)) begin
        grp_INV_LUT_fu_629_x = x_V_1_reg_1943;
    end else if ((1'b1 == ap_CS_fsm_state34)) begin
        grp_INV_LUT_fu_629_x = sub_ln703_6_reg_1978;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_INV_LUT_fu_629_x = in_1;
    end else begin
        grp_INV_LUT_fu_629_x = 'bx;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1699 == 1'd1) & (1'b1 == ap_CS_fsm_state74))) begin
        grp_SQRT_LUT_fu_647_x = in_sqrt_aux_V;
    end else if (((1'd1 == EN3) & (1'b1 == ap_CS_fsm_state55))) begin
        grp_SQRT_LUT_fu_647_x = trunc_ln708_6_reg_2046;
    end else if (((ap_predicate_op359_call_state55 == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        grp_SQRT_LUT_fu_647_x = in_3;
    end else begin
        grp_SQRT_LUT_fu_647_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        grp_cos_2000_fu_604_theta_in = add_ln703_1_reg_2104;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_cos_2000_fu_604_theta_in = theta1_V;
    end else begin
        grp_cos_2000_fu_604_theta_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | ((1'b0 == ap_block_state49_on_subcall_done) & (1'b1 == ap_CS_fsm_state49)))) begin
        grp_fu_1254_ce = 1'b1;
    end else begin
        grp_fu_1254_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | ((1'b0 == ap_block_state49_on_subcall_done) & (1'b1 == ap_CS_fsm_state49)))) begin
        grp_fu_1261_ce = 1'b1;
    end else begin
        grp_fu_1261_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state58) | ((1'b0 == ap_block_state55_on_subcall_done) & (1'b1 == ap_CS_fsm_state55)))) begin
        grp_fu_1309_ce = 1'b1;
    end else begin
        grp_fu_1309_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state58) | ((1'b0 == ap_block_state55_on_subcall_done) & (1'b1 == ap_CS_fsm_state55)))) begin
        grp_fu_1314_ce = 1'b1;
    end else begin
        grp_fu_1314_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_797_ce = 1'b1;
    end else begin
        grp_fu_797_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6)))) begin
        grp_fu_806_ce = 1'b1;
    end else begin
        grp_fu_806_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | ((grp_sin_2000_fu_640_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18)))) begin
        grp_fu_976_ce = 1'b1;
    end else begin
        grp_fu_976_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        grp_sin_2000_fu_640_theta_in = add_ln703_1_reg_2104;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        grp_sin_2000_fu_640_theta_in = shl_ln703_reg_1770;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_sin_2000_fu_640_theta_in = theta1_V;
    end else begin
        grp_sin_2000_fu_640_theta_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        in_atan_ap_vld = 1'b1;
    end else begin
        in_atan_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        in_inv_ap_vld = 1'b1;
    end else begin
        in_inv_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        in_sqrt_ap_vld = 1'b1;
    end else begin
        in_sqrt_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        out_atan_ap_vld = 1'b1;
    end else begin
        out_atan_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        out_inv_ap_vld = 1'b1;
    end else begin
        out_inv_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        out_sqrt_ap_vld = 1'b1;
    end else begin
        out_sqrt_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        pll_alpha_out_ap_vld = 1'b1;
    end else begin
        pll_alpha_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        pll_beta_out_ap_vld = 1'b1;
    end else begin
        pll_beta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        q_inv_d_out_ap_vld = 1'b1;
    end else begin
        q_inv_d_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        theta_out_ap_vld = 1'b1;
    end else begin
        theta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        v2_d_limpo_out_ap_vld = 1'b1;
    end else begin
        v2_d_limpo_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        v_alfa_in_ap_vld = 1'b1;
    end else begin
        v_alfa_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        v_beta_in_ap_vld = 1'b1;
    end else begin
        v_beta_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
        w_out_ap_vld = 1'b1;
    end else begin
        w_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else if (((ap_start == 1'b1) & (xor_ln870_fu_692_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b0 == ap_block_state6_on_subcall_done) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            if (((grp_sin_2000_fu_640_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state18))) begin
                ap_NS_fsm = ap_ST_fsm_state19;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state18;
            end
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((1'd1 == EN1_read_read_fu_292_p2) & (1'b1 == ap_CS_fsm_state25) & (tmp_fu_1194_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else if (((1'd1 == EN1_read_read_fu_292_p2) & (1'b1 == ap_CS_fsm_state25) & (tmp_fu_1194_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else if (((1'd1 == EN4_read_read_fu_274_p2) & (1'b1 == ap_CS_fsm_state25) & (1'd0 == EN1_read_read_fu_292_p2) & (tmp_9_fu_1187_p3 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end else if (((1'd1 == EN4_read_read_fu_274_p2) & (1'b1 == ap_CS_fsm_state25) & (1'd0 == EN1_read_read_fu_292_p2) & (tmp_9_fu_1187_p3 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state31))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            if (((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state34))) begin
                ap_NS_fsm = ap_ST_fsm_state35;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state34;
            end
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state37))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state37;
            end
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state40))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            if (((1'b1 == ap_CS_fsm_state46) & (1'd0 == EN2_read_read_fu_286_p2) & (1'd0 == EN5_read_read_fu_268_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else if (((1'd1 == EN5_read_read_fu_268_p2) & (1'b1 == ap_CS_fsm_state46) & (1'd0 == EN2_read_read_fu_286_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        ap_ST_fsm_state47 : begin
            if (((grp_ATAN_LUT_signed_fu_618_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state47))) begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            if (((1'b0 == ap_block_state49_on_subcall_done) & (1'b1 == ap_CS_fsm_state49))) begin
                ap_NS_fsm = ap_ST_fsm_state50;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state49;
            end
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            if (((1'b0 == ap_block_state55_on_subcall_done) & (1'b1 == ap_CS_fsm_state55))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            if (((1'b0 == ap_block_state64_on_subcall_done) & (1'b1 == ap_CS_fsm_state64))) begin
                ap_NS_fsm = ap_ST_fsm_state65;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            if (((1'b1 == ap_CS_fsm_state69) & ((tmp_10_fu_1526_p3 == 1'd0) | (icmp_ln1494_fu_1510_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state70;
            end
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            if (((grp_INV_LUT_fu_629_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state71))) begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state71;
            end
        end
        ap_ST_fsm_state72 : begin
            if (((1'b0 == ap_block_state72_on_subcall_done) & (1'b1 == ap_CS_fsm_state72))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state74 : begin
            if (((1'b0 == ap_block_state74_on_subcall_done) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Amp_vneg_out = ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_526_p4;

assign Amp_vneg_raw_base_out = Amp_vneg_raw_base_V;

assign EN1_read_read_fu_292_p2 = EN1;

assign EN2_read_read_fu_286_p2 = EN2;

assign EN4_read_read_fu_274_p2 = EN4;

assign EN5_read_read_fu_268_p2 = EN5;

assign EN6_read_read_fu_262_p2 = EN6;

assign add_ln703_1_fu_1451_p2 = (trunc_ln708_7_reg_2087 + shl_ln703_reg_1770);

assign add_ln703_2_fu_1515_p2 = (in_inv_aux_V + 64'd28147497671065);

assign add_ln703_3_fu_1561_p2 = (in_atan_aux_V + 64'd28147497671065);

assign add_ln703_4_fu_1592_p2 = (in_sqrt_aux_V + 64'd28147497671065);

assign amp_vPos_out = ap_phi_mux_amp_vPos_V_loc_0_phi_fu_556_p4;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

always @ (*) begin
    ap_block_state49_on_subcall_done = ((grp_ATAN_LUT_signed_fu_618_ap_done == 1'b0) & (1'd1 == EN2));
end

always @ (*) begin
    ap_block_state55_on_subcall_done = (((ap_predicate_op359_call_state55 == 1'b1) & (grp_SQRT_LUT_fu_647_ap_done == 1'b0)) | ((grp_SQRT_LUT_fu_647_ap_done == 1'b0) & (1'd1 == EN3)));
end

always @ (*) begin
    ap_block_state64_on_subcall_done = ((grp_sin_2000_fu_640_ap_done == 1'b0) | (grp_cos_2000_fu_604_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_sin_2000_fu_640_ap_done == 1'b0) | (grp_cos_2000_fu_611_ap_done == 1'b0) | (grp_cos_2000_fu_604_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state72_on_subcall_done = ((ap_predicate_op445_call_state72 == 1'b1) & (grp_INV_LUT_fu_629_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state74_on_subcall_done = (((grp_SQRT_LUT_fu_647_ap_done == 1'b0) & (xor_ln870_reg_1699 == 1'd1)) | ((grp_ATAN_LUT_signed_fu_618_ap_done == 1'b0) & (xor_ln870_reg_1699 == 1'd1)));
end

always @ (*) begin
    ap_predicate_op359_call_state55 = ((1'd1 == EN6) & (1'd0 == EN3));
end

always @ (*) begin
    ap_predicate_op445_call_state72 = ((icmp_ln1494_reg_2126 == 1'd1) | (tmp_10_reg_2136 == 1'd0));
end

assign delta_out = ap_phi_mux_delta_V_loc_0_phi_fu_516_p4;

assign grp_ATAN_LUT_signed_fu_618_ap_start = grp_ATAN_LUT_signed_fu_618_ap_start_reg;

assign grp_INV_LUT_fu_629_ap_start = grp_INV_LUT_fu_629_ap_start_reg;

assign grp_SQRT_LUT_fu_647_ap_start = grp_SQRT_LUT_fu_647_ap_start_reg;

assign grp_cos_2000_fu_604_ap_start = grp_cos_2000_fu_604_ap_start_reg;

assign grp_cos_2000_fu_611_ap_start = grp_cos_2000_fu_611_ap_start_reg;

assign grp_fu_1026_p0 = sext_ln1118_4_fu_1023_p1;

assign grp_fu_1035_p0 = sext_ln1118_4_fu_1023_p1;

assign grp_fu_1083_p1 = 94'd562949953;

assign grp_fu_1181_p1 = 109'd28147497671065;

assign grp_fu_1254_p0 = sext_ln1115_4_reg_2003;

assign grp_fu_1254_p1 = sext_ln1115_4_reg_2003;

assign grp_fu_1261_p0 = sext_ln1115_5_fu_1258_p1;

assign grp_fu_1261_p1 = sext_ln1115_5_fu_1258_p1;

assign grp_fu_1309_p0 = sext_ln1115_1_reg_1807;

assign grp_fu_1309_p1 = sext_ln1115_7_fu_1306_p1;

assign grp_fu_1314_p0 = sext_ln1115_7_fu_1306_p1;

assign grp_fu_1314_p1 = sext_ln1115_reg_1794;

assign grp_fu_1322_p1 = 153'd298682249638991202482701120;

assign grp_fu_1344_p1 = 155'd1194732167682462933788702720;

assign grp_fu_1462_p1 = sext_ln1115_6_fu_1455_p1;

assign grp_fu_1472_p1 = sext_ln1115_6_fu_1455_p1;

assign grp_fu_682_p2 = (64'd0 - reg_671);

assign grp_fu_797_p1 = 160'd187649984473770;

assign grp_fu_806_p1 = 112'd162509653574040;

assign grp_fu_857_p0 = sext_ln1118_2_fu_854_p1;

assign grp_fu_857_p1 = sext_ln1115_fu_850_p1;

assign grp_fu_870_p0 = sext_ln1118_3_fu_867_p1;

assign grp_fu_870_p1 = sext_ln1115_1_fu_863_p1;

assign grp_fu_876_p0 = sext_ln1115_1_fu_863_p1;

assign grp_fu_876_p1 = sext_ln1118_2_fu_854_p1;

assign grp_fu_882_p0 = sext_ln1118_3_fu_867_p1;

assign grp_fu_882_p1 = sext_ln1115_fu_850_p1;

assign grp_fu_967_p1 = 152'd158456324909939889799168000;

assign grp_fu_976_p1 = 112'd5629499534213120;

assign grp_sin_2000_fu_640_ap_start = grp_sin_2000_fu_640_ap_start_reg;

assign icmp_ln1494_10_fu_1556_p2 = (($signed(in_atan_aux_V) > $signed(64'd2814749767106560000)) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_1587_p2 = (($signed(in_sqrt_aux_V) > $signed(64'd2814749767106560000)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_1510_p2 = (($signed(in_inv_aux_V) > $signed(64'd281474976710656000)) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_1075_p2 = (($signed(theta1_V) < $signed(64'd1768559438007110)) ? 1'b1 : 1'b0);

assign in_atan = ap_phi_mux_in_atan_aux_V_loc_0_phi_fu_587_p4;

assign in_inv = ap_phi_mux_in_inv_aux_V_loc_2_phi_fu_576_p4;

assign in_sqrt = ap_phi_mux_in_sqrt_aux_V_loc_0_phi_fu_597_p4;

assign lhs_V_12_fu_1387_p1 = delta_V;

assign lhs_V_12_fu_1387_p3 = {{lhs_V_12_fu_1387_p1}, {96'd0}};

assign lhs_V_15_fu_1419_p1 = Amp_vneg_V;

assign lhs_V_15_fu_1419_p3 = {{lhs_V_15_fu_1419_p1}, {96'd0}};

assign lhs_V_2_fu_1089_p3 = {{tmp_1_reg_1857}, {48'd0}};

assign lhs_V_3_fu_1111_p3 = {{tmp_2_reg_1862}, {48'd0}};

assign lhs_V_5_fu_986_p3 = {{wi_V}, {96'd0}};

assign lhs_V_7_fu_1046_p3 = {{ret_V_22_fu_1041_p2}, {48'd0}};

assign lhs_V_9_fu_1139_p3 = {{theta1_V}, {48'd0}};

assign lhs_fu_766_p3 = {{vin_a}, {48'd0}};

assign out_atan = ap_sig_allocacmp_out_atan_aux_V_load;

assign out_inv = ap_sig_allocacmp_out_inv_aux_V_load;

assign out_sqrt = ap_sig_allocacmp_out_sqrt_aux_V_load;

assign pll_alpha_out = pll_alfa_V;

assign pll_beta_out = pll_beta_V;

assign q_inv_d_out = q_inv_d_V;

assign r_V_27_fu_938_p2 = (v1_d_comp_V + trunc_ln708_3_fu_906_p4);

assign r_V_29_fu_1366_p2 = (112'd0 - mul_ln1118_reg_2077);

assign r_V_30_fu_758_p3 = {{ret_V_fu_752_p2}, {47'd0}};

assign ret_V_10_fu_920_p2 = (r_V_34_reg_1838 + r_V_33_reg_1832);

assign ret_V_11_fu_1096_p2 = (lhs_V_2_fu_1089_p3 - r_V_11_reg_1923);

assign ret_V_12_fu_1118_p2 = (lhs_V_3_fu_1111_p3 + r_V_13_reg_1928);

assign ret_V_13_fu_997_p2 = ($signed(lhs_V_5_fu_986_p3) + $signed(sext_ln703_2_fu_994_p1));

assign ret_V_15_fu_1054_p2 = (lhs_V_7_fu_1046_p3 + r_V_15_reg_1887);

assign ret_V_16_fu_1149_p2 = ($signed(lhs_V_9_fu_1139_p3) + $signed(sext_ln703_3_fu_1146_p1));

assign ret_V_17_fu_1267_p2 = (r_V_21_reg_2041 + r_V_19_reg_2036);

assign ret_V_18_fu_1295_p2 = ($signed(sext_ln703_4_fu_1288_p1) - $signed(sext_ln703_5_fu_1292_p1));

assign ret_V_19_fu_1397_p2 = ($signed(lhs_V_12_fu_1387_p3) + $signed(sext_ln703_6_fu_1394_p1));

assign ret_V_20_fu_1335_p2 = ($signed(sext_ln703_7_fu_1328_p1) - $signed(sext_ln703_8_fu_1332_p1));

assign ret_V_21_fu_1429_p2 = ($signed(lhs_V_15_fu_1419_p3) + $signed(sext_ln703_9_fu_1426_p1));

assign ret_V_22_fu_1041_p2 = (rhs_4_reg_1882 + 64'd84442493013196800);

assign ret_V_5_fu_782_p2 = ($signed(sext_ln1193_fu_774_p1) - $signed(sext_ln1193_1_fu_778_p1));

assign ret_V_6_fu_788_p2 = ($signed(sext_ln703_fu_744_p1) - $signed(sext_ln703_1_fu_748_p1));

assign ret_V_7_fu_888_p2 = (r_V_32_reg_1826 + r_V_31_reg_1820);

assign ret_V_8_fu_902_p2 = (r_V_33_reg_1832 - r_V_34_reg_1838);

assign ret_V_9_fu_916_p2 = (r_V_31_reg_1820 - r_V_32_reg_1826);

assign ret_V_fu_752_p2 = ($signed(sext_ln703_1_fu_748_p1) + $signed(sext_ln703_fu_744_p1));

assign select_ln1496_fu_1165_p3 = ((icmp_ln1496_reg_1913[0:0] == 1'b1) ? trunc_ln708_s_fu_1155_p4 : 64'd0);

assign select_ln317_fu_1566_p3 = ((icmp_ln1494_10_fu_1556_p2[0:0] == 1'b1) ? 64'd56294995342131 : add_ln703_3_fu_1561_p2);

assign select_ln333_fu_1597_p3 = ((icmp_ln1494_11_fu_1587_p2[0:0] == 1'b1) ? 64'd56294995342131 : add_ln703_4_fu_1592_p2);

assign sext_ln1115_1_fu_863_p1 = reg_658;

assign sext_ln1115_4_fu_1225_p1 = r_V_1_reg_1933;

assign sext_ln1115_5_fu_1258_p1 = x_V_1_reg_1943;

assign sext_ln1115_6_fu_1455_p1 = r_V_24_reg_2098;

assign sext_ln1115_7_fu_1306_p1 = r_V_27_reg_1850;

assign sext_ln1115_fu_850_p1 = reg_662;

assign sext_ln1118_2_fu_854_p1 = trunc_ln_reg_1777;

assign sext_ln1118_3_fu_867_p1 = trunc_ln708_1_reg_1783;

assign sext_ln1118_4_fu_1023_p0 = amp_vPos_V;

assign sext_ln1118_4_fu_1023_p1 = sext_ln1118_4_fu_1023_p0;

assign sext_ln1193_1_fu_778_p1 = $signed(r_V_30_fu_758_p3);

assign sext_ln1193_fu_774_p1 = $signed(lhs_fu_766_p3);

assign sext_ln703_1_fu_748_p1 = $signed(vin_c);

assign sext_ln703_2_fu_994_p1 = $signed(r_V_14_reg_1877);

assign sext_ln703_3_fu_1146_p1 = $signed(r_V_16_reg_1952);

assign sext_ln703_4_fu_1288_p1 = $signed(lhs_V_10_reg_445);

assign sext_ln703_5_fu_1292_p0 = delta_V;

assign sext_ln703_5_fu_1292_p1 = sext_ln703_5_fu_1292_p0;

assign sext_ln703_6_fu_1394_p1 = $signed(r_V_22_reg_2082);

assign sext_ln703_7_fu_1328_p1 = $signed(lhs_V_13_reg_459);

assign sext_ln703_8_fu_1332_p0 = Amp_vneg_V;

assign sext_ln703_8_fu_1332_p1 = sext_ln703_8_fu_1332_p0;

assign sext_ln703_9_fu_1426_p1 = $signed(r_V_23_reg_2093);

assign sext_ln703_fu_744_p1 = $signed(vin_b);

assign sext_ln708_fu_1211_p1 = $signed(trunc_ln708_4_fu_1201_p4);

assign shl_ln703_fu_812_p2 = theta1_V << 64'd1;

assign sub_ln703_4_fu_1220_p2 = ($signed(64'd0) - $signed(x_V_1_reg_1943));

assign sub_ln703_6_fu_1215_p2 = (64'd0 - in_1);

assign sub_ln703_8_fu_1533_p2 = (64'd0 - in_inv_aux_V);

assign sub_ln703_fu_928_p2 = (trunc_ln708_2_fu_892_p4 - v1_q_comp_V);

assign theta_out = ap_phi_mux_theta1_V_loc_0_phi_fu_506_p4;

assign tmp_10_fu_1526_p3 = in_inv_aux_V[32'd63];

assign tmp_9_fu_1187_p3 = in_1[32'd63];

assign tmp_fu_1194_p3 = ret_V_12_reg_1938[32'd111];

assign trunc_ln708_2_fu_892_p4 = {{ret_V_7_fu_888_p2[111:48]}};

assign trunc_ln708_3_fu_906_p4 = {{ret_V_8_fu_902_p2[111:48]}};

assign trunc_ln708_4_fu_1201_p4 = {{grp_fu_1181_p2[108:48]}};

assign trunc_ln708_s_fu_1155_p4 = {{ret_V_16_fu_1149_p2[111:48]}};

assign v2_d_limpo_out = ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_566_p4;

assign v_alfa_in = ap_phi_mux_v_alfa_V_loc_0_phi_fu_536_p4;

assign v_beta_in = ap_phi_mux_v_beta_V_loc_0_phi_fu_546_p4;

assign w_out = w_V;

assign xor_ln870_fu_692_p2 = (sinc ^ aux_sinc_V);

assign y_V_5_fu_1544_p2 = (64'd0 - reg_666);

always @ (posedge ap_clk) begin
    ret_V_5_reg_1750[46:0] <= 47'b00000000000000000000000000000000000000000000000;
    shl_ln703_reg_1770[0] <= 1'b0;
end

endmodule //PLL2026_x64
