#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("sinc", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("opt", 1, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("f", 64, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("A_1p", 64, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("Ang_1p", 64, hls_in, 4, "ap_none", "in_data", 1),
	Port_Property("A_1n", 64, hls_in, 5, "ap_none", "in_data", 1),
	Port_Property("Ang_1n", 64, hls_in, 6, "ap_none", "in_data", 1),
	Port_Property("A_5p", 64, hls_in, 7, "ap_none", "in_data", 1),
	Port_Property("Ang_5p", 64, hls_in, 8, "ap_none", "in_data", 1),
	Port_Property("A_5n", 64, hls_in, 9, "ap_none", "in_data", 1),
	Port_Property("Ang_5n", 64, hls_in, 10, "ap_none", "in_data", 1),
	Port_Property("A_7p", 64, hls_in, 11, "ap_none", "in_data", 1),
	Port_Property("Ang_7p", 64, hls_in, 12, "ap_none", "in_data", 1),
	Port_Property("A_7n", 64, hls_in, 13, "ap_none", "in_data", 1),
	Port_Property("Ang_7n", 64, hls_in, 14, "ap_none", "in_data", 1),
	Port_Property("vout_a", 64, hls_out, 15, "ap_vld", "out_data", 1),
	Port_Property("vout_a_ap_vld", 1, hls_out, 15, "ap_vld", "out_vld", 1),
	Port_Property("vout_b", 64, hls_out, 16, "ap_vld", "out_data", 1),
	Port_Property("vout_b_ap_vld", 1, hls_out, 16, "ap_vld", "out_vld", 1),
	Port_Property("vout_c", 64, hls_out, 17, "ap_vld", "out_data", 1),
	Port_Property("vout_c_ap_vld", 1, hls_out, 17, "ap_vld", "out_vld", 1),
	Port_Property("wtout", 64, hls_out, 18, "ap_vld", "out_data", 1),
	Port_Property("wtout_ap_vld", 1, hls_out, 18, "ap_vld", "out_vld", 1),
	Port_Property("dwtout", 64, hls_out, 19, "ap_vld", "out_data", 1),
	Port_Property("dwtout_ap_vld", 1, hls_out, 19, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "sin_gen_varAmp2_3phi_x64";
