// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="PLL2026_x64_PLL2026_x64,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=36,HLS_SYN_DSP=0,HLS_SYN_FF=21721,HLS_SYN_LUT=22428,HLS_VERSION=2020_2}" *)

module PLL2026_x64 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sinc,
        EN1,
        EN2,
        EN3,
        EN4,
        EN5,
        EN6,
        vin_a,
        vin_b,
        vin_c,
        in_1,
        in_2,
        in_3,
        w_out,
        w_out_ap_vld,
        theta_out,
        theta_out_ap_vld,
        pll_alpha_out,
        pll_alpha_out_ap_vld,
        pll_beta_out,
        pll_beta_out_ap_vld,
        amp_vPos_out,
        amp_vPos_out_ap_vld,
        Amp_vneg_out,
        Amp_vneg_out_ap_vld,
        delta_out,
        delta_out_ap_vld,
        v_alfa_in,
        v_alfa_in_ap_vld,
        v_beta_in,
        v_beta_in_ap_vld,
        Amp_vneg_raw_base_out,
        Amp_vneg_raw_base_out_ap_vld,
        q_inv_d_out,
        q_inv_d_out_ap_vld,
        v2_d_limpo_out,
        v2_d_limpo_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 78'd1;
parameter    ap_ST_fsm_state2 = 78'd2;
parameter    ap_ST_fsm_state3 = 78'd4;
parameter    ap_ST_fsm_state4 = 78'd8;
parameter    ap_ST_fsm_state5 = 78'd16;
parameter    ap_ST_fsm_state6 = 78'd32;
parameter    ap_ST_fsm_state7 = 78'd64;
parameter    ap_ST_fsm_state8 = 78'd128;
parameter    ap_ST_fsm_state9 = 78'd256;
parameter    ap_ST_fsm_state10 = 78'd512;
parameter    ap_ST_fsm_state11 = 78'd1024;
parameter    ap_ST_fsm_state12 = 78'd2048;
parameter    ap_ST_fsm_state13 = 78'd4096;
parameter    ap_ST_fsm_state14 = 78'd8192;
parameter    ap_ST_fsm_state15 = 78'd16384;
parameter    ap_ST_fsm_state16 = 78'd32768;
parameter    ap_ST_fsm_state17 = 78'd65536;
parameter    ap_ST_fsm_state18 = 78'd131072;
parameter    ap_ST_fsm_state19 = 78'd262144;
parameter    ap_ST_fsm_state20 = 78'd524288;
parameter    ap_ST_fsm_state21 = 78'd1048576;
parameter    ap_ST_fsm_state22 = 78'd2097152;
parameter    ap_ST_fsm_state23 = 78'd4194304;
parameter    ap_ST_fsm_state24 = 78'd8388608;
parameter    ap_ST_fsm_state25 = 78'd16777216;
parameter    ap_ST_fsm_state26 = 78'd33554432;
parameter    ap_ST_fsm_state27 = 78'd67108864;
parameter    ap_ST_fsm_state28 = 78'd134217728;
parameter    ap_ST_fsm_state29 = 78'd268435456;
parameter    ap_ST_fsm_state30 = 78'd536870912;
parameter    ap_ST_fsm_state31 = 78'd1073741824;
parameter    ap_ST_fsm_state32 = 78'd2147483648;
parameter    ap_ST_fsm_state33 = 78'd4294967296;
parameter    ap_ST_fsm_state34 = 78'd8589934592;
parameter    ap_ST_fsm_state35 = 78'd17179869184;
parameter    ap_ST_fsm_state36 = 78'd34359738368;
parameter    ap_ST_fsm_state37 = 78'd68719476736;
parameter    ap_ST_fsm_state38 = 78'd137438953472;
parameter    ap_ST_fsm_state39 = 78'd274877906944;
parameter    ap_ST_fsm_state40 = 78'd549755813888;
parameter    ap_ST_fsm_state41 = 78'd1099511627776;
parameter    ap_ST_fsm_state42 = 78'd2199023255552;
parameter    ap_ST_fsm_state43 = 78'd4398046511104;
parameter    ap_ST_fsm_state44 = 78'd8796093022208;
parameter    ap_ST_fsm_state45 = 78'd17592186044416;
parameter    ap_ST_fsm_state46 = 78'd35184372088832;
parameter    ap_ST_fsm_state47 = 78'd70368744177664;
parameter    ap_ST_fsm_state48 = 78'd140737488355328;
parameter    ap_ST_fsm_state49 = 78'd281474976710656;
parameter    ap_ST_fsm_state50 = 78'd562949953421312;
parameter    ap_ST_fsm_state51 = 78'd1125899906842624;
parameter    ap_ST_fsm_state52 = 78'd2251799813685248;
parameter    ap_ST_fsm_state53 = 78'd4503599627370496;
parameter    ap_ST_fsm_state54 = 78'd9007199254740992;
parameter    ap_ST_fsm_state55 = 78'd18014398509481984;
parameter    ap_ST_fsm_state56 = 78'd36028797018963968;
parameter    ap_ST_fsm_state57 = 78'd72057594037927936;
parameter    ap_ST_fsm_state58 = 78'd144115188075855872;
parameter    ap_ST_fsm_state59 = 78'd288230376151711744;
parameter    ap_ST_fsm_state60 = 78'd576460752303423488;
parameter    ap_ST_fsm_state61 = 78'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 78'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 78'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 78'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 78'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 78'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 78'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 78'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 78'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 78'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 78'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 78'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 78'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 78'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 78'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 78'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 78'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 78'd151115727451828646838272;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] sinc;
input  [0:0] EN1;
input  [0:0] EN2;
input  [0:0] EN3;
input  [0:0] EN4;
input  [0:0] EN5;
input  [0:0] EN6;
input  [63:0] vin_a;
input  [63:0] vin_b;
input  [63:0] vin_c;
input  [63:0] in_1;
input  [63:0] in_2;
input  [63:0] in_3;
output  [63:0] w_out;
output   w_out_ap_vld;
output  [63:0] theta_out;
output   theta_out_ap_vld;
output  [63:0] pll_alpha_out;
output   pll_alpha_out_ap_vld;
output  [63:0] pll_beta_out;
output   pll_beta_out_ap_vld;
output  [63:0] amp_vPos_out;
output   amp_vPos_out_ap_vld;
output  [63:0] Amp_vneg_out;
output   Amp_vneg_out_ap_vld;
output  [63:0] delta_out;
output   delta_out_ap_vld;
output  [63:0] v_alfa_in;
output   v_alfa_in_ap_vld;
output  [63:0] v_beta_in;
output   v_beta_in_ap_vld;
output  [63:0] Amp_vneg_raw_base_out;
output   Amp_vneg_raw_base_out_ap_vld;
output  [63:0] q_inv_d_out;
output   q_inv_d_out_ap_vld;
output  [63:0] v2_d_limpo_out;
output   v2_d_limpo_out_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg w_out_ap_vld;
reg theta_out_ap_vld;
reg pll_alpha_out_ap_vld;
reg pll_beta_out_ap_vld;
reg amp_vPos_out_ap_vld;
reg Amp_vneg_out_ap_vld;
reg delta_out_ap_vld;
reg v_alfa_in_ap_vld;
reg v_beta_in_ap_vld;
reg Amp_vneg_raw_base_out_ap_vld;
reg q_inv_d_out_ap_vld;
reg v2_d_limpo_out_ap_vld;

(* fsm_encoding = "none" *) reg   [77:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] aux_sinc_V;
reg   [63:0] theta1_V;
reg   [63:0] delta_V;
reg   [63:0] Amp_vneg_V;
reg   [63:0] v_alfa_V;
reg   [63:0] v_beta_V;
reg   [63:0] amp_vPos_V;
reg   [63:0] v2_d_limpo_V;
reg   [63:0] wi_V;
reg   [63:0] v1_q_comp_V;
reg   [63:0] v1_d_comp_V;
reg   [63:0] w_V;
reg   [63:0] q_inv_d_V;
reg   [63:0] Amp_vneg_raw_base_V;
reg   [5:0] table_mark_V_address0;
reg    table_mark_V_ce0;
wire   [62:0] table_mark_V_q0;
reg   [5:0] table_m_V_address0;
reg    table_m_V_ce0;
wire   [48:0] table_m_V_q0;
reg   [5:0] table_n_V_address0;
reg    table_n_V_ce0;
wire   [54:0] table_n_V_q0;
reg   [63:0] pll_alfa_V;
reg   [63:0] pll_beta_V;
wire   [49:0] grp_sin_2000_fu_632_ap_return;
reg  signed [49:0] reg_639;
wire    ap_CS_fsm_state6;
wire    grp_sin_2000_fu_632_ap_ready;
wire    grp_sin_2000_fu_632_ap_done;
wire    grp_cos_2000_fu_596_ap_ready;
wire    grp_cos_2000_fu_596_ap_done;
wire    grp_cos_2000_fu_603_ap_ready;
wire    grp_cos_2000_fu_603_ap_done;
reg    ap_block_state6_on_subcall_done;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state73;
reg    ap_block_state73_on_subcall_done;
wire   [49:0] grp_cos_2000_fu_596_ap_return;
reg  signed [49:0] reg_643;
reg   [48:0] reg_647;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state59;
wire   [0:0] EN5_read_read_fu_254_p2;
wire   [0:0] EN4_read_read_fu_260_p2;
wire   [0:0] EN3_read_read_fu_266_p2;
wire   [0:0] EN2_read_read_fu_272_p2;
wire   [0:0] EN1_read_read_fu_278_p2;
wire   [0:0] xor_ln870_fu_655_p2;
reg   [0:0] xor_ln870_reg_1759;
wire   [112:0] ret_V_5_fu_733_p2;
reg  signed [112:0] ret_V_5_reg_1798;
wire   [64:0] ret_V_6_fu_739_p2;
reg  signed [64:0] ret_V_6_reg_1803;
wire    ap_CS_fsm_state2;
wire   [63:0] shl_ln703_fu_763_p2;
reg   [63:0] shl_ln703_reg_1818;
wire    ap_CS_fsm_state5;
reg  signed [63:0] trunc_ln_reg_1825;
reg  signed [63:0] trunc_ln708_1_reg_1831;
wire   [49:0] grp_cos_2000_fu_603_ap_return;
reg  signed [49:0] r_V_12_reg_1837;
wire  signed [111:0] sext_ln1115_fu_801_p1;
reg  signed [111:0] sext_ln1115_reg_1842;
wire  signed [111:0] sext_ln1118_2_fu_805_p1;
wire  signed [111:0] sext_ln1115_1_fu_814_p1;
reg  signed [111:0] sext_ln1115_1_reg_1855;
wire  signed [111:0] sext_ln1118_3_fu_818_p1;
wire    ap_CS_fsm_state8;
wire  signed [111:0] sext_ln1118_4_fu_843_p1;
wire   [111:0] grp_fu_808_p2;
reg   [111:0] r_V_35_reg_1884;
wire    ap_CS_fsm_state11;
wire   [111:0] grp_fu_821_p2;
reg   [111:0] r_V_36_reg_1890;
wire   [111:0] grp_fu_827_p2;
reg   [111:0] r_V_37_reg_1896;
wire   [111:0] grp_fu_833_p2;
reg   [111:0] r_V_38_reg_1902;
wire  signed [63:0] sub_ln703_fu_901_p2;
reg  signed [63:0] sub_ln703_reg_1908;
wire    ap_CS_fsm_state12;
wire  signed [63:0] r_V_31_fu_911_p2;
reg  signed [63:0] r_V_31_reg_1914;
wire   [111:0] grp_fu_846_p2;
reg   [111:0] r_V_11_reg_1921;
reg   [63:0] tmp_1_reg_1926;
wire   [111:0] grp_fu_855_p2;
reg   [111:0] r_V_13_reg_1931;
reg   [63:0] tmp_2_reg_1936;
reg  signed [63:0] r_V_1_reg_1941;
wire    ap_CS_fsm_state13;
reg  signed [63:0] r_V_20_reg_1946;
wire    ap_CS_fsm_state14;
wire   [149:0] grp_fu_990_p2;
reg   [149:0] r_V_14_reg_1964;
wire    ap_CS_fsm_state17;
reg   [63:0] rhs_3_reg_1969;
wire    ap_CS_fsm_state18;
wire   [111:0] grp_fu_999_p2;
reg   [111:0] r_V_15_reg_1974;
reg  signed [63:0] trunc_ln708_9_reg_1979;
wire    ap_CS_fsm_state19;
wire   [0:0] icmp_ln1496_fu_1076_p2;
reg   [0:0] icmp_ln1496_reg_1984;
wire    ap_CS_fsm_state20;
wire   [91:0] grp_fu_1084_p2;
reg   [91:0] r_V_16_reg_1994;
wire    ap_CS_fsm_state24;
wire   [63:0] select_ln1496_fu_1116_p3;
reg   [63:0] select_ln1496_reg_1999;
wire    ap_CS_fsm_state25;
wire  signed [63:0] sext_ln708_fu_1148_p1;
wire    ap_CS_fsm_state29;
wire   [63:0] grp_INV_LUT_fu_621_ap_return;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state32;
wire  signed [111:0] sext_ln1115_4_fu_1152_p1;
reg  signed [111:0] sext_ln1115_4_reg_2024;
wire    ap_CS_fsm_state33;
reg   [63:0] trunc_ln708_5_reg_2036;
wire    ap_CS_fsm_state37;
wire   [63:0] grp_ATAN_LUT_signed_fu_610_ap_return;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state40;
wire  signed [111:0] sext_ln1115_5_fu_1185_p1;
wire   [111:0] grp_fu_1181_p2;
reg   [111:0] r_V_19_reg_2057;
wire    ap_CS_fsm_state44;
wire   [111:0] grp_fu_1188_p2;
reg   [111:0] r_V_21_reg_2062;
reg   [63:0] valor_V_reg_2067;
wire    ap_CS_fsm_state45;
wire   [0:0] or_ln1159_fu_1226_p2;
reg   [0:0] or_ln1159_reg_2073;
wire   [0:0] tmp_fu_1232_p3;
reg   [0:0] tmp_reg_2077;
wire   [31:0] half_list_1_fu_1276_p2;
reg   [31:0] half_list_1_reg_2084;
wire    ap_CS_fsm_state46;
wire   [0:0] icmp_ln926_1_fu_1256_p2;
wire   [31:0] intervalo_begin_fu_1296_p3;
wire    ap_CS_fsm_state47;
wire   [31:0] intervalo_end_3_fu_1303_p3;
wire    ap_CS_fsm_state48;
reg   [54:0] rhs_6_reg_2115;
wire    ap_CS_fsm_state50;
wire   [111:0] grp_fu_1323_p2;
reg   [111:0] r_V_25_reg_2130;
wire    ap_CS_fsm_state54;
wire    ap_CS_fsm_state55;
wire   [64:0] ret_V_20_fu_1388_p2;
reg  signed [64:0] ret_V_20_reg_2145;
wire  signed [111:0] sext_ln1115_7_fu_1399_p1;
wire   [31:0] half_list_fu_1448_p2;
reg   [31:0] half_list_reg_2159;
wire    ap_CS_fsm_state56;
wire   [0:0] icmp_ln926_fu_1428_p2;
wire   [31:0] intervalo_begin_2_fu_1468_p3;
wire    ap_CS_fsm_state57;
wire   [31:0] intervalo_end_2_fu_1475_p3;
wire    ap_CS_fsm_state58;
reg   [54:0] rhs_4_reg_2190;
wire    ap_CS_fsm_state60;
wire   [111:0] grp_fu_1495_p2;
reg   [111:0] r_V_23_reg_2205;
wire    ap_CS_fsm_state64;
wire    ap_CS_fsm_state65;
wire   [64:0] ret_V_22_fu_1517_p2;
reg  signed [64:0] ret_V_22_reg_2215;
wire    ap_CS_fsm_state66;
wire   [111:0] grp_fu_1407_p2;
reg   [111:0] mul_ln1118_reg_2225;
wire    ap_CS_fsm_state68;
wire   [150:0] grp_fu_1504_p2;
reg   [150:0] r_V_26_reg_2230;
wire    ap_CS_fsm_state69;
reg   [63:0] trunc_ln708_6_reg_2235;
wire    ap_CS_fsm_state70;
wire   [152:0] grp_fu_1526_p2;
reg   [152:0] r_V_27_reg_2241;
reg  signed [63:0] r_V_28_reg_2246;
wire    ap_CS_fsm_state71;
wire   [63:0] add_ln703_1_fu_1633_p2;
reg   [63:0] add_ln703_1_reg_2252;
wire  signed [111:0] sext_ln1115_6_fu_1637_p1;
wire    ap_CS_fsm_state74;
wire    grp_cos_2000_fu_596_ap_start;
wire    grp_cos_2000_fu_596_ap_idle;
reg   [63:0] grp_cos_2000_fu_596_theta_in;
wire    grp_cos_2000_fu_603_ap_start;
wire    grp_cos_2000_fu_603_ap_idle;
wire    grp_ATAN_LUT_signed_fu_610_ap_start;
wire    grp_ATAN_LUT_signed_fu_610_ap_done;
wire    grp_ATAN_LUT_signed_fu_610_ap_idle;
wire    grp_ATAN_LUT_signed_fu_610_ap_ready;
reg   [63:0] grp_ATAN_LUT_signed_fu_610_x;
wire    grp_INV_LUT_fu_621_ap_start;
wire    grp_INV_LUT_fu_621_ap_done;
wire    grp_INV_LUT_fu_621_ap_idle;
wire    grp_INV_LUT_fu_621_ap_ready;
reg   [63:0] grp_INV_LUT_fu_621_x;
wire    grp_sin_2000_fu_632_ap_start;
wire    grp_sin_2000_fu_632_ap_idle;
reg   [63:0] grp_sin_2000_fu_632_theta_in;
reg  signed [63:0] empty_reg_437;
reg   [63:0] lhs_V_10_reg_448;
reg    ap_block_state40_on_subcall_done;
reg   [31:0] intervalo_begin_5_reg_462;
reg   [31:0] intervalo_end_1_reg_474;
reg   [31:0] intervalo_begin_4_reg_486;
reg   [31:0] intervalo_end_reg_498;
reg   [63:0] lhs_V_13_reg_510;
reg   [63:0] ap_phi_mux_theta1_V_loc_0_phi_fu_529_p4;
reg   [63:0] theta1_V_loc_0_reg_526;
wire    ap_CS_fsm_state78;
reg   [63:0] ap_phi_mux_delta_V_loc_0_phi_fu_539_p4;
reg   [63:0] delta_V_loc_0_reg_536;
reg   [63:0] ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_549_p4;
reg   [63:0] Amp_vneg_V_loc_0_reg_546;
reg   [63:0] ap_phi_mux_v_alfa_V_loc_0_phi_fu_559_p4;
reg   [63:0] v_alfa_V_loc_0_reg_556;
reg   [63:0] ap_phi_mux_v_beta_V_loc_0_phi_fu_569_p4;
reg   [63:0] v_beta_V_loc_0_reg_566;
reg   [63:0] ap_phi_mux_amp_vPos_V_loc_0_phi_fu_579_p4;
reg   [63:0] amp_vPos_V_loc_0_reg_576;
reg   [63:0] ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_589_p4;
reg   [63:0] v2_d_limpo_V_loc_0_reg_586;
reg    grp_cos_2000_fu_596_ap_start_reg;
wire    ap_CS_fsm_state72;
reg    grp_cos_2000_fu_603_ap_start_reg;
reg    grp_ATAN_LUT_signed_fu_610_ap_start_reg;
wire    ap_CS_fsm_state39;
reg    grp_INV_LUT_fu_621_ap_start_reg;
wire    ap_CS_fsm_state31;
reg    grp_sin_2000_fu_632_ap_start_reg;
wire   [63:0] zext_ln931_1_fu_1282_p1;
wire   [63:0] zext_ln1166_1_fu_1310_p1;
wire   [63:0] zext_ln931_fu_1454_p1;
wire   [63:0] zext_ln1166_fu_1482_p1;
wire  signed [64:0] sext_ln703_1_fu_699_p1;
wire  signed [64:0] sext_ln703_fu_695_p1;
wire   [64:0] ret_V_fu_703_p2;
wire   [111:0] lhs_fu_717_p3;
wire   [111:0] r_V_34_fu_709_p3;
wire  signed [112:0] sext_ln1193_fu_725_p1;
wire  signed [112:0] sext_ln1193_1_fu_729_p1;
wire   [48:0] grp_fu_748_p1;
wire   [48:0] grp_fu_757_p1;
wire   [159:0] grp_fu_748_p2;
wire   [111:0] grp_fu_757_p2;
wire  signed [63:0] grp_fu_808_p0;
wire  signed [49:0] grp_fu_808_p1;
wire  signed [63:0] grp_fu_821_p0;
wire  signed [49:0] grp_fu_821_p1;
wire  signed [49:0] grp_fu_827_p0;
wire  signed [63:0] grp_fu_827_p1;
wire  signed [63:0] grp_fu_833_p0;
wire  signed [49:0] grp_fu_833_p1;
wire  signed [63:0] sext_ln1118_4_fu_843_p0;
wire  signed [63:0] grp_fu_846_p0;
wire  signed [63:0] grp_fu_855_p0;
wire   [111:0] ret_V_7_fu_861_p2;
wire   [111:0] ret_V_8_fu_875_p2;
wire   [63:0] trunc_ln708_2_fu_865_p4;
wire   [63:0] trunc_ln708_3_fu_879_p4;
wire   [111:0] ret_V_9_fu_889_p2;
wire   [111:0] ret_V_10_fu_893_p2;
wire   [111:0] lhs_V_2_fu_937_p3;
wire   [111:0] ret_V_11_fu_944_p2;
wire   [111:0] lhs_V_3_fu_959_p3;
wire   [111:0] ret_V_12_fu_966_p2;
wire   [86:0] grp_fu_990_p1;
wire   [53:0] grp_fu_999_p1;
wire   [159:0] lhs_V_5_fu_1009_p3;
wire  signed [159:0] sext_ln703_2_fu_1017_p1;
wire   [159:0] ret_V_13_fu_1020_p2;
wire   [63:0] ret_V_24_fu_1042_p2;
wire   [111:0] lhs_V_7_fu_1047_p3;
wire   [111:0] ret_V_15_fu_1055_p2;
wire   [28:0] grp_fu_1084_p1;
wire   [111:0] lhs_V_9_fu_1090_p3;
wire  signed [111:0] sext_ln703_3_fu_1097_p1;
wire   [111:0] ret_V_16_fu_1100_p2;
wire   [63:0] trunc_ln708_s_fu_1106_p4;
wire   [45:0] grp_fu_1132_p1;
wire   [108:0] grp_fu_1132_p2;
wire   [60:0] trunc_ln708_4_fu_1138_p4;
wire   [111:0] grp_fu_1159_p2;
wire  signed [63:0] grp_fu_1181_p0;
wire  signed [63:0] grp_fu_1181_p1;
wire  signed [63:0] grp_fu_1188_p0;
wire  signed [63:0] grp_fu_1188_p1;
wire   [111:0] ret_V_17_fu_1194_p2;
wire   [0:0] tmp_8_fu_1219_p3;
wire   [0:0] xor_ln229_fu_1214_p2;
wire   [31:0] sub_ln926_1_fu_1240_p2;
wire   [30:0] tmp_10_fu_1246_p4;
wire   [30:0] div1_i_i1_fu_1262_p4;
wire   [31:0] div1_i_i1_cast_fu_1272_p1;
wire   [63:0] zext_ln1494_1_fu_1287_p1;
wire   [0:0] icmp_ln1494_10_fu_1291_p2;
wire   [48:0] grp_fu_1323_p0;
wire   [63:0] grp_fu_1323_p1;
wire   [102:0] rhs_7_fu_1329_p3;
wire   [111:0] zext_ln1192_1_fu_1336_p1;
wire   [111:0] ret_V_19_fu_1340_p2;
wire   [102:0] rhs_5_fu_1355_p3;
wire   [111:0] zext_ln1192_fu_1362_p1;
wire   [111:0] ret_V_18_fu_1366_p2;
wire  signed [63:0] sext_ln703_5_fu_1385_p0;
wire  signed [64:0] sext_ln703_4_fu_1381_p1;
wire  signed [64:0] sext_ln703_5_fu_1385_p1;
wire  signed [49:0] grp_fu_1402_p0;
wire  signed [63:0] grp_fu_1402_p1;
wire  signed [63:0] grp_fu_1407_p0;
wire  signed [49:0] grp_fu_1407_p1;
wire   [31:0] sub_ln926_fu_1412_p2;
wire   [30:0] tmp_9_fu_1418_p4;
wire   [30:0] div1_i_i_fu_1434_p4;
wire   [31:0] div1_i_i_cast_fu_1444_p1;
wire   [63:0] zext_ln1494_fu_1459_p1;
wire   [0:0] icmp_ln1494_fu_1463_p2;
wire   [48:0] grp_fu_1495_p0;
wire   [63:0] grp_fu_1495_p1;
wire   [86:0] grp_fu_1504_p1;
wire  signed [63:0] sext_ln703_8_fu_1514_p0;
wire  signed [64:0] sext_ln703_7_fu_1510_p1;
wire  signed [64:0] sext_ln703_8_fu_1514_p1;
wire   [88:0] grp_fu_1526_p1;
wire   [111:0] grp_fu_1402_p2;
wire   [111:0] r_V_33_fu_1548_p2;
wire  signed [63:0] lhs_V_12_fu_1569_p1;
wire   [159:0] lhs_V_12_fu_1569_p3;
wire  signed [159:0] sext_ln703_6_fu_1576_p1;
wire   [159:0] ret_V_21_fu_1579_p2;
wire  signed [63:0] lhs_V_15_fu_1601_p1;
wire   [159:0] lhs_V_15_fu_1601_p3;
wire  signed [159:0] sext_ln703_9_fu_1608_p1;
wire   [159:0] ret_V_23_fu_1611_p2;
wire  signed [63:0] grp_fu_1644_p1;
wire  signed [63:0] grp_fu_1654_p1;
wire   [111:0] grp_fu_1644_p2;
wire   [111:0] grp_fu_1654_p2;
reg    grp_fu_748_ce;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    grp_fu_757_ce;
reg    grp_fu_808_ce;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_fu_821_ce;
reg    grp_fu_827_ce;
reg    grp_fu_833_ce;
reg    grp_fu_1181_ce;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state43;
reg    grp_fu_1188_ce;
reg   [77:0] ap_NS_fsm;
wire   [111:0] grp_fu_1323_p00;
wire   [111:0] grp_fu_1323_p10;
wire   [111:0] grp_fu_1495_p00;
wire   [111:0] grp_fu_1495_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 78'd1;
#0 aux_sinc_V = 1'd0;
#0 theta1_V = 64'd0;
#0 delta_V = 64'd0;
#0 Amp_vneg_V = 64'd0;
#0 v_alfa_V = 64'd0;
#0 v_beta_V = 64'd0;
#0 amp_vPos_V = 64'd0;
#0 v2_d_limpo_V = 64'd0;
#0 wi_V = 64'd0;
#0 v1_q_comp_V = 64'd0;
#0 v1_d_comp_V = 64'd0;
#0 w_V = 64'd0;
#0 q_inv_d_V = 64'd0;
#0 Amp_vneg_raw_base_V = 64'd0;
#0 pll_alfa_V = 64'd0;
#0 pll_beta_V = 64'd0;
#0 grp_cos_2000_fu_596_ap_start_reg = 1'b0;
#0 grp_cos_2000_fu_603_ap_start_reg = 1'b0;
#0 grp_ATAN_LUT_signed_fu_610_ap_start_reg = 1'b0;
#0 grp_INV_LUT_fu_621_ap_start_reg = 1'b0;
#0 grp_sin_2000_fu_632_ap_start_reg = 1'b0;
end

PLL2026_x64_table_mark_V #(
    .DataWidth( 63 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
table_mark_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_mark_V_address0),
    .ce0(table_mark_V_ce0),
    .q0(table_mark_V_q0)
);

PLL2026_x64_table_m_V #(
    .DataWidth( 49 ),
    .AddressRange( 63 ),
    .AddressWidth( 6 ))
table_m_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_m_V_address0),
    .ce0(table_m_V_ce0),
    .q0(table_m_V_q0)
);

PLL2026_x64_table_n_V #(
    .DataWidth( 55 ),
    .AddressRange( 63 ),
    .AddressWidth( 6 ))
table_n_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(table_n_V_address0),
    .ce0(table_n_V_ce0),
    .q0(table_n_V_q0)
);

PLL2026_x64_cos_2000 grp_cos_2000_fu_596(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cos_2000_fu_596_ap_start),
    .ap_done(grp_cos_2000_fu_596_ap_done),
    .ap_idle(grp_cos_2000_fu_596_ap_idle),
    .ap_ready(grp_cos_2000_fu_596_ap_ready),
    .theta_in(grp_cos_2000_fu_596_theta_in),
    .ap_return(grp_cos_2000_fu_596_ap_return)
);

PLL2026_x64_cos_2000 grp_cos_2000_fu_603(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cos_2000_fu_603_ap_start),
    .ap_done(grp_cos_2000_fu_603_ap_done),
    .ap_idle(grp_cos_2000_fu_603_ap_idle),
    .ap_ready(grp_cos_2000_fu_603_ap_ready),
    .theta_in(shl_ln703_reg_1818),
    .ap_return(grp_cos_2000_fu_603_ap_return)
);

PLL2026_x64_ATAN_LUT_signed grp_ATAN_LUT_signed_fu_610(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_ATAN_LUT_signed_fu_610_ap_start),
    .ap_done(grp_ATAN_LUT_signed_fu_610_ap_done),
    .ap_idle(grp_ATAN_LUT_signed_fu_610_ap_idle),
    .ap_ready(grp_ATAN_LUT_signed_fu_610_ap_ready),
    .x(grp_ATAN_LUT_signed_fu_610_x),
    .ap_return(grp_ATAN_LUT_signed_fu_610_ap_return)
);

PLL2026_x64_INV_LUT grp_INV_LUT_fu_621(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_INV_LUT_fu_621_ap_start),
    .ap_done(grp_INV_LUT_fu_621_ap_done),
    .ap_idle(grp_INV_LUT_fu_621_ap_idle),
    .ap_ready(grp_INV_LUT_fu_621_ap_ready),
    .x(grp_INV_LUT_fu_621_x),
    .ap_return(grp_INV_LUT_fu_621_ap_return)
);

PLL2026_x64_sin_2000 grp_sin_2000_fu_632(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_632_ap_start),
    .ap_done(grp_sin_2000_fu_632_ap_done),
    .ap_idle(grp_sin_2000_fu_632_ap_idle),
    .ap_ready(grp_sin_2000_fu_632_ap_ready),
    .theta_in(grp_sin_2000_fu_632_theta_in),
    .ap_return(grp_sin_2000_fu_632_ap_return)
);

PLL2026_x64_mul_113s_49ns_160_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 113 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 160 ))
mul_113s_49ns_160_5_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_5_reg_1798),
    .din1(grp_fu_748_p1),
    .ce(grp_fu_748_ce),
    .dout(grp_fu_748_p2)
);

PLL2026_x64_mul_65s_49ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 49 ),
    .dout_WIDTH( 112 ))
mul_65s_49ns_112_5_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_6_reg_1803),
    .din1(grp_fu_757_p1),
    .ce(grp_fu_757_ce),
    .dout(grp_fu_757_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_808_p0),
    .din1(grp_fu_808_p1),
    .ce(grp_fu_808_ce),
    .dout(grp_fu_808_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U26(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_821_p0),
    .din1(grp_fu_821_p1),
    .ce(grp_fu_821_ce),
    .dout(grp_fu_821_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_827_p0),
    .din1(grp_fu_827_p1),
    .ce(grp_fu_827_ce),
    .dout(grp_fu_827_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_833_p0),
    .din1(grp_fu_833_p1),
    .ce(grp_fu_833_ce),
    .dout(grp_fu_833_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_846_p0),
    .din1(reg_639),
    .ce(1'b1),
    .dout(grp_fu_846_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_855_p0),
    .din1(r_V_12_reg_1837),
    .ce(1'b1),
    .dout(grp_fu_855_p2)
);

PLL2026_x64_mul_64s_87ns_150_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 87 ),
    .dout_WIDTH( 150 ))
mul_64s_87ns_150_5_1_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln703_reg_1908),
    .din1(grp_fu_990_p1),
    .ce(1'b1),
    .dout(grp_fu_990_p2)
);

PLL2026_x64_mul_64s_54ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 54 ),
    .dout_WIDTH( 112 ))
mul_64s_54ns_112_5_1_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(sub_ln703_reg_1908),
    .din1(grp_fu_999_p1),
    .ce(1'b1),
    .dout(grp_fu_999_p2)
);

PLL2026_x64_mul_64s_29ns_92_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 29 ),
    .dout_WIDTH( 92 ))
mul_64s_29ns_92_5_1_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(trunc_ln708_9_reg_1979),
    .din1(grp_fu_1084_p1),
    .ce(1'b1),
    .dout(grp_fu_1084_p2)
);

PLL2026_x64_mul_64s_46ns_109_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 46 ),
    .dout_WIDTH( 109 ))
mul_64s_46ns_109_5_1_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_20_reg_1946),
    .din1(grp_fu_1132_p1),
    .ce(1'b1),
    .dout(grp_fu_1132_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U35(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(r_V_1_reg_1941),
    .din1(empty_reg_437),
    .ce(1'b1),
    .dout(grp_fu_1159_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U36(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1181_p0),
    .din1(grp_fu_1181_p1),
    .ce(grp_fu_1181_ce),
    .dout(grp_fu_1181_p2)
);

PLL2026_x64_mul_64s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_64s_64s_112_5_1_U37(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1188_p0),
    .din1(grp_fu_1188_p1),
    .ce(grp_fu_1188_ce),
    .dout(grp_fu_1188_p2)
);

PLL2026_x64_mul_49ns_64ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_49ns_64ns_112_5_1_U38(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1323_p0),
    .din1(grp_fu_1323_p1),
    .ce(1'b1),
    .dout(grp_fu_1323_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U39(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1402_p0),
    .din1(grp_fu_1402_p1),
    .ce(1'b1),
    .dout(grp_fu_1402_p2)
);

PLL2026_x64_mul_64s_50s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 50 ),
    .dout_WIDTH( 112 ))
mul_64s_50s_112_5_1_U40(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1407_p0),
    .din1(grp_fu_1407_p1),
    .ce(1'b1),
    .dout(grp_fu_1407_p2)
);

PLL2026_x64_mul_49ns_64ns_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 49 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_49ns_64ns_112_5_1_U41(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1495_p0),
    .din1(grp_fu_1495_p1),
    .ce(1'b1),
    .dout(grp_fu_1495_p2)
);

PLL2026_x64_mul_65s_87ns_151_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 87 ),
    .dout_WIDTH( 151 ))
mul_65s_87ns_151_5_1_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_20_reg_2145),
    .din1(grp_fu_1504_p1),
    .ce(1'b1),
    .dout(grp_fu_1504_p2)
);

PLL2026_x64_mul_65s_89ns_153_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 65 ),
    .din1_WIDTH( 89 ),
    .dout_WIDTH( 153 ))
mul_65s_89ns_153_5_1_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(ret_V_22_reg_2215),
    .din1(grp_fu_1526_p1),
    .ce(1'b1),
    .dout(grp_fu_1526_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_639),
    .din1(grp_fu_1644_p1),
    .ce(1'b1),
    .dout(grp_fu_1644_p2)
);

PLL2026_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_643),
    .din1(grp_fu_1654_p1),
    .ce(1'b1),
    .dout(grp_fu_1654_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_ATAN_LUT_signed_fu_610_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state39) | ((1'd1 == EN5_read_read_fu_254_p2) & (1'b1 == ap_CS_fsm_state37) & (1'd0 == EN2_read_read_fu_272_p2)))) begin
            grp_ATAN_LUT_signed_fu_610_ap_start_reg <= 1'b1;
        end else if ((grp_ATAN_LUT_signed_fu_610_ap_ready == 1'b1)) begin
            grp_ATAN_LUT_signed_fu_610_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_INV_LUT_fu_621_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state31) | ((1'd1 == EN4_read_read_fu_260_p2) & (1'b1 == ap_CS_fsm_state25) & (1'd0 == EN1_read_read_fu_278_p2)))) begin
            grp_INV_LUT_fu_621_ap_start_reg <= 1'b1;
        end else if ((grp_INV_LUT_fu_621_ap_ready == 1'b1)) begin
            grp_INV_LUT_fu_621_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cos_2000_fu_596_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state5))) begin
            grp_cos_2000_fu_596_ap_start_reg <= 1'b1;
        end else if ((grp_cos_2000_fu_596_ap_ready == 1'b1)) begin
            grp_cos_2000_fu_596_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cos_2000_fu_603_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_cos_2000_fu_603_ap_start_reg <= 1'b1;
        end else if ((grp_cos_2000_fu_603_ap_ready == 1'b1)) begin
            grp_cos_2000_fu_603_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_632_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state72) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done)))) begin
            grp_sin_2000_fu_632_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_632_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_632_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        Amp_vneg_V_loc_0_reg_546 <= Amp_vneg_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        Amp_vneg_V_loc_0_reg_546 <= r_V_28_reg_2246;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        amp_vPos_V_loc_0_reg_576 <= amp_vPos_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        amp_vPos_V_loc_0_reg_576 <= r_V_31_reg_1914;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        delta_V_loc_0_reg_536 <= delta_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        delta_V_loc_0_reg_536 <= trunc_ln708_6_reg_2235;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        empty_reg_437 <= sext_ln708_fu_1148_p1;
    end else if ((((grp_INV_LUT_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32)) | ((grp_INV_LUT_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30)))) begin
        empty_reg_437 <= grp_INV_LUT_fu_621_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1232_p3 == 1'd0) & (1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state45))) begin
        intervalo_begin_4_reg_486 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        intervalo_begin_4_reg_486 <= intervalo_begin_2_fu_1468_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln1159_fu_1226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state45) & (1'd0 == EN3_read_read_fu_266_p2))) begin
        intervalo_begin_5_reg_462 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state47)) begin
        intervalo_begin_5_reg_462 <= intervalo_begin_fu_1296_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_ln1159_fu_1226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state45) & (1'd0 == EN3_read_read_fu_266_p2))) begin
        intervalo_end_1_reg_474 <= 32'd63;
    end else if ((1'b1 == ap_CS_fsm_state47)) begin
        intervalo_end_1_reg_474 <= intervalo_end_3_fu_1303_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_1232_p3 == 1'd0) & (1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state45))) begin
        intervalo_end_reg_498 <= 32'd63;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        intervalo_end_reg_498 <= intervalo_end_2_fu_1475_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state37) & (1'd0 == EN2_read_read_fu_272_p2) & (1'd0 == EN5_read_read_fu_254_p2))) begin
        lhs_V_10_reg_448 <= 64'd0;
    end else if ((((grp_ATAN_LUT_signed_fu_610_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38)) | ((1'd1 == EN2) & (1'b1 == ap_CS_fsm_state40) & (1'b0 == ap_block_state40_on_subcall_done)))) begin
        lhs_V_10_reg_448 <= grp_ATAN_LUT_signed_fu_610_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((((or_ln1159_fu_1226_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state45) & (1'd0 == EN3_read_read_fu_266_p2)) | ((tmp_fu_1232_p3 == 1'd1) & (1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state45)))) begin
        lhs_V_13_reg_510 <= 64'd0;
    end else if (((or_ln1159_reg_2073 == 1'd0) & (1'b1 == ap_CS_fsm_state55) & (1'd0 == EN3_read_read_fu_266_p2))) begin
        lhs_V_13_reg_510 <= {{ret_V_19_fu_1340_p2[111:48]}};
    end else if (((tmp_reg_2077 == 1'd0) & (1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state55))) begin
        lhs_V_13_reg_510 <= {{ret_V_18_fu_1366_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        theta1_V_loc_0_reg_526 <= theta1_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        theta1_V_loc_0_reg_526 <= select_ln1496_reg_1999;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v2_d_limpo_V_loc_0_reg_586 <= v2_d_limpo_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        v2_d_limpo_V_loc_0_reg_586 <= r_V_20_reg_1946;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v_alfa_V_loc_0_reg_556 <= v_alfa_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        v_alfa_V_loc_0_reg_556 <= trunc_ln_reg_1825;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        v_beta_V_loc_0_reg_566 <= v_beta_V;
    end else if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        v_beta_V_loc_0_reg_566 <= trunc_ln708_1_reg_1831;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state71)) begin
        Amp_vneg_V <= {{ret_V_23_fu_1611_p2[159:96]}};
        add_ln703_1_reg_2252 <= add_ln703_1_fu_1633_p2;
        r_V_28_reg_2246 <= {{ret_V_23_fu_1611_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        Amp_vneg_raw_base_V <= {{ret_V_17_fu_1194_p2[111:48]}};
        valor_V_reg_2067 <= {{ret_V_17_fu_1194_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        amp_vPos_V <= r_V_31_reg_1914;
        ret_V_20_reg_2145 <= ret_V_20_fu_1388_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        aux_sinc_V <= sinc;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        delta_V <= {{ret_V_21_fu_1579_p2[159:96]}};
        r_V_27_reg_2241 <= grp_fu_1526_p2;
        trunc_ln708_6_reg_2235 <= {{ret_V_21_fu_1579_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln926_1_fu_1256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state46))) begin
        half_list_1_reg_2084 <= half_list_1_fu_1276_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln926_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
        half_list_reg_2159 <= half_list_fu_1448_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        icmp_ln1496_reg_1984 <= icmp_ln1496_fu_1076_p2;
        trunc_ln708_9_reg_1979 <= {{ret_V_15_fu_1055_p2[111:48]}};
        w_V <= {{ret_V_15_fu_1055_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state68)) begin
        mul_ln1118_reg_2225 <= grp_fu_1407_p2;
        pll_alfa_V <= {{grp_fu_1402_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state45) & (1'd0 == EN3_read_read_fu_266_p2))) begin
        or_ln1159_reg_2073 <= or_ln1159_fu_1226_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        pll_beta_V <= {{r_V_33_fu_1548_p2[111:48]}};
        r_V_26_reg_2230 <= grp_fu_1504_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state37)) begin
        q_inv_d_V <= {{grp_fu_1159_p2[111:48]}};
        trunc_ln708_5_reg_2036 <= {{grp_fu_1159_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        r_V_11_reg_1921 <= grp_fu_846_p2;
        r_V_13_reg_1931 <= grp_fu_855_p2;
        r_V_31_reg_1914 <= r_V_31_fu_911_p2;
        sub_ln703_reg_1908 <= sub_ln703_fu_901_p2;
        tmp_1_reg_1926 <= {{ret_V_9_fu_889_p2[111:48]}};
        tmp_2_reg_1936 <= {{ret_V_10_fu_893_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        r_V_12_reg_1837 <= grp_cos_2000_fu_603_ap_return;
        trunc_ln708_1_reg_1831 <= {{grp_fu_757_p2[111:48]}};
        trunc_ln_reg_1825 <= {{grp_fu_748_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        r_V_14_reg_1964 <= grp_fu_990_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        r_V_15_reg_1974 <= grp_fu_999_p2;
        rhs_3_reg_1969 <= {{ret_V_13_fu_1020_p2[159:96]}};
        wi_V <= {{ret_V_13_fu_1020_p2[159:96]}};
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1496_reg_1984 == 1'd1) & (1'b1 == ap_CS_fsm_state24))) begin
        r_V_16_reg_1994 <= grp_fu_1084_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        r_V_19_reg_2057 <= grp_fu_1181_p2;
        r_V_21_reg_2062 <= grp_fu_1188_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        r_V_1_reg_1941 <= {{ret_V_11_fu_944_p2[111:48]}};
        r_V_20_reg_1946 <= {{ret_V_12_fu_966_p2[111:48]}};
        v2_d_limpo_V <= {{ret_V_12_fu_966_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        r_V_23_reg_2205 <= grp_fu_1495_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state54)) begin
        r_V_25_reg_2130 <= grp_fu_1323_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        r_V_35_reg_1884 <= grp_fu_808_p2;
        r_V_36_reg_1890 <= grp_fu_821_p2;
        r_V_37_reg_1896 <= grp_fu_827_p2;
        r_V_38_reg_1902 <= grp_fu_833_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_CS_fsm_state73) & (1'b0 == ap_block_state73_on_subcall_done)) | ((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1)) | ((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done)))) begin
        reg_639 <= grp_sin_2000_fu_632_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state6))) begin
        reg_643 <= grp_cos_2000_fu_596_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state49))) begin
        reg_647 <= table_m_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        ret_V_22_reg_2215 <= ret_V_22_fu_1517_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((xor_ln870_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ret_V_5_reg_1798[112 : 47] <= ret_V_5_fu_733_p2[112 : 47];
        ret_V_6_reg_1803 <= ret_V_6_fu_739_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        rhs_4_reg_2190 <= table_n_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        rhs_6_reg_2115 <= table_n_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        select_ln1496_reg_1999 <= select_ln1496_fu_1116_p3;
        theta1_V <= select_ln1496_fu_1116_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        sext_ln1115_1_reg_1855 <= sext_ln1115_1_fu_814_p1;
        sext_ln1115_reg_1842 <= sext_ln1115_fu_801_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        sext_ln1115_4_reg_2024 <= sext_ln1115_4_fu_1152_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        shl_ln703_reg_1818[63 : 1] <= shl_ln703_fu_763_p2[63 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state45))) begin
        tmp_reg_2077 <= ret_V_17_fu_1194_p2[32'd111];
    end
end

always @ (posedge ap_clk) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        v1_d_comp_V <= {{grp_fu_1654_p2[111:48]}};
        v1_q_comp_V <= {{grp_fu_1644_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
        v_alfa_V <= {{grp_fu_748_p2[159:96]}};
        v_beta_V <= {{grp_fu_757_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        xor_ln870_reg_1759 <= xor_ln870_fu_655_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        Amp_vneg_out_ap_vld = 1'b1;
    end else begin
        Amp_vneg_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        Amp_vneg_raw_base_out_ap_vld = 1'b1;
    end else begin
        Amp_vneg_raw_base_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        amp_vPos_out_ap_vld = 1'b1;
    end else begin
        amp_vPos_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_549_p4 = r_V_28_reg_2246;
    end else begin
        ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_549_p4 = Amp_vneg_V_loc_0_reg_546;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_amp_vPos_V_loc_0_phi_fu_579_p4 = r_V_31_reg_1914;
    end else begin
        ap_phi_mux_amp_vPos_V_loc_0_phi_fu_579_p4 = amp_vPos_V_loc_0_reg_576;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_delta_V_loc_0_phi_fu_539_p4 = trunc_ln708_6_reg_2235;
    end else begin
        ap_phi_mux_delta_V_loc_0_phi_fu_539_p4 = delta_V_loc_0_reg_536;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_theta1_V_loc_0_phi_fu_529_p4 = select_ln1496_reg_1999;
    end else begin
        ap_phi_mux_theta1_V_loc_0_phi_fu_529_p4 = theta1_V_loc_0_reg_526;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_589_p4 = r_V_20_reg_1946;
    end else begin
        ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_589_p4 = v2_d_limpo_V_loc_0_reg_586;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_v_alfa_V_loc_0_phi_fu_559_p4 = trunc_ln_reg_1825;
    end else begin
        ap_phi_mux_v_alfa_V_loc_0_phi_fu_559_p4 = v_alfa_V_loc_0_reg_556;
    end
end

always @ (*) begin
    if (((xor_ln870_reg_1759 == 1'd1) & (1'b1 == ap_CS_fsm_state78))) begin
        ap_phi_mux_v_beta_V_loc_0_phi_fu_569_p4 = trunc_ln708_1_reg_1831;
    end else begin
        ap_phi_mux_v_beta_V_loc_0_phi_fu_569_p4 = v_beta_V_loc_0_reg_566;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        delta_out_ap_vld = 1'b1;
    end else begin
        delta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == EN2) & (1'b1 == ap_CS_fsm_state40))) begin
        grp_ATAN_LUT_signed_fu_610_x = trunc_ln708_5_reg_2036;
    end else if ((1'b1 == ap_CS_fsm_state38)) begin
        grp_ATAN_LUT_signed_fu_610_x = in_2;
    end else begin
        grp_ATAN_LUT_signed_fu_610_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        grp_INV_LUT_fu_621_x = r_V_20_reg_1946;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_INV_LUT_fu_621_x = in_1;
    end else begin
        grp_INV_LUT_fu_621_x = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        grp_cos_2000_fu_596_theta_in = add_ln703_1_reg_2252;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_cos_2000_fu_596_theta_in = theta1_V;
    end else begin
        grp_cos_2000_fu_596_theta_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | ((1'b1 == ap_CS_fsm_state40) & (1'b0 == ap_block_state40_on_subcall_done)))) begin
        grp_fu_1181_ce = 1'b1;
    end else begin
        grp_fu_1181_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state41) | ((1'b1 == ap_CS_fsm_state40) & (1'b0 == ap_block_state40_on_subcall_done)))) begin
        grp_fu_1188_ce = 1'b1;
    end else begin
        grp_fu_1188_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done)))) begin
        grp_fu_748_ce = 1'b1;
    end else begin
        grp_fu_748_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done)))) begin
        grp_fu_757_ce = 1'b1;
    end else begin
        grp_fu_757_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1)))) begin
        grp_fu_808_ce = 1'b1;
    end else begin
        grp_fu_808_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1)))) begin
        grp_fu_821_ce = 1'b1;
    end else begin
        grp_fu_821_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1)))) begin
        grp_fu_827_ce = 1'b1;
    end else begin
        grp_fu_827_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | ((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1)))) begin
        grp_fu_833_ce = 1'b1;
    end else begin
        grp_fu_833_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        grp_sin_2000_fu_632_theta_in = add_ln703_1_reg_2252;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_sin_2000_fu_632_theta_in = shl_ln703_reg_1818;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_sin_2000_fu_632_theta_in = theta1_V;
    end else begin
        grp_sin_2000_fu_632_theta_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        pll_alpha_out_ap_vld = 1'b1;
    end else begin
        pll_alpha_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        pll_beta_out_ap_vld = 1'b1;
    end else begin
        pll_beta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        q_inv_d_out_ap_vld = 1'b1;
    end else begin
        q_inv_d_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        table_m_V_address0 = zext_ln1166_fu_1482_p1;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        table_m_V_address0 = zext_ln1166_1_fu_1310_p1;
    end else begin
        table_m_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state48))) begin
        table_m_V_ce0 = 1'b1;
    end else begin
        table_m_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state56)) begin
        table_mark_V_address0 = zext_ln931_fu_1454_p1;
    end else if ((1'b1 == ap_CS_fsm_state46)) begin
        table_mark_V_address0 = zext_ln931_1_fu_1282_p1;
    end else begin
        table_mark_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state46))) begin
        table_mark_V_ce0 = 1'b1;
    end else begin
        table_mark_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state58)) begin
        table_n_V_address0 = zext_ln1166_fu_1482_p1;
    end else if ((1'b1 == ap_CS_fsm_state48)) begin
        table_n_V_address0 = zext_ln1166_1_fu_1310_p1;
    end else begin
        table_n_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state48))) begin
        table_n_V_ce0 = 1'b1;
    end else begin
        table_n_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        theta_out_ap_vld = 1'b1;
    end else begin
        theta_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        v2_d_limpo_out_ap_vld = 1'b1;
    end else begin
        v2_d_limpo_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        v_alfa_in_ap_vld = 1'b1;
    end else begin
        v_alfa_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        v_beta_in_ap_vld = 1'b1;
    end else begin
        v_beta_in_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state78)) begin
        w_out_ap_vld = 1'b1;
    end else begin
        w_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state78;
            end else if (((ap_start == 1'b1) & (xor_ln870_fu_655_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (1'b0 == ap_block_state6_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_sin_2000_fu_632_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((1'd1 == EN4_read_read_fu_260_p2) & (1'b1 == ap_CS_fsm_state25) & (1'd0 == EN1_read_read_fu_278_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end else if (((1'b1 == ap_CS_fsm_state25) & (1'd0 == EN1_read_read_fu_278_p2) & (1'd0 == EN4_read_read_fu_260_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state26;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state30 : begin
            if (((grp_INV_LUT_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state30))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state30;
            end
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            if (((grp_INV_LUT_fu_621_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            if (((1'b1 == ap_CS_fsm_state37) & (1'd0 == EN2_read_read_fu_272_p2) & (1'd0 == EN5_read_read_fu_254_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else if (((1'd1 == EN5_read_read_fu_254_p2) & (1'b1 == ap_CS_fsm_state37) & (1'd0 == EN2_read_read_fu_272_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state39;
            end
        end
        ap_ST_fsm_state38 : begin
            if (((grp_ATAN_LUT_signed_fu_610_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state38))) begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state38;
            end
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            if (((1'b1 == ap_CS_fsm_state40) & (1'b0 == ap_block_state40_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state41;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state40;
            end
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            if (((tmp_fu_1232_p3 == 1'd0) & (1'd1 == EN3_read_read_fu_266_p2) & (1'b1 == ap_CS_fsm_state45))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else if (((or_ln1159_fu_1226_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state45) & (1'd0 == EN3_read_read_fu_266_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state46;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state46 : begin
            if (((icmp_ln926_1_fu_1256_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state46))) begin
                ap_NS_fsm = ap_ST_fsm_state47;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state48;
            end
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state56 : begin
            if (((icmp_ln926_fu_1428_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            if (((1'b1 == ap_CS_fsm_state73) & (1'b0 == ap_block_state73_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Amp_vneg_out = ap_phi_mux_Amp_vneg_V_loc_0_phi_fu_549_p4;

assign Amp_vneg_raw_base_out = Amp_vneg_raw_base_V;

assign EN1_read_read_fu_278_p2 = EN1;

assign EN2_read_read_fu_272_p2 = EN2;

assign EN3_read_read_fu_266_p2 = EN3;

assign EN4_read_read_fu_260_p2 = EN4;

assign EN5_read_read_fu_254_p2 = EN5;

assign add_ln703_1_fu_1633_p2 = (trunc_ln708_6_reg_2235 + shl_ln703_reg_1818);

assign amp_vPos_out = ap_phi_mux_amp_vPos_V_loc_0_phi_fu_579_p4;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state68 = ap_CS_fsm[32'd67];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state71 = ap_CS_fsm[32'd70];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state40_on_subcall_done = ((grp_ATAN_LUT_signed_fu_610_ap_done == 1'b0) & (1'd1 == EN2));
end

always @ (*) begin
    ap_block_state6_on_subcall_done = ((grp_cos_2000_fu_603_ap_done == 1'b0) | (grp_cos_2000_fu_596_ap_done == 1'b0) | (grp_sin_2000_fu_632_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state73_on_subcall_done = ((grp_cos_2000_fu_596_ap_done == 1'b0) | (grp_sin_2000_fu_632_ap_done == 1'b0));
end

assign delta_out = ap_phi_mux_delta_V_loc_0_phi_fu_539_p4;

assign div1_i_i1_cast_fu_1272_p1 = div1_i_i1_fu_1262_p4;

assign div1_i_i1_fu_1262_p4 = {{sub_ln926_1_fu_1240_p2[31:1]}};

assign div1_i_i_cast_fu_1444_p1 = div1_i_i_fu_1434_p4;

assign div1_i_i_fu_1434_p4 = {{sub_ln926_fu_1412_p2[31:1]}};

assign grp_ATAN_LUT_signed_fu_610_ap_start = grp_ATAN_LUT_signed_fu_610_ap_start_reg;

assign grp_INV_LUT_fu_621_ap_start = grp_INV_LUT_fu_621_ap_start_reg;

assign grp_cos_2000_fu_596_ap_start = grp_cos_2000_fu_596_ap_start_reg;

assign grp_cos_2000_fu_603_ap_start = grp_cos_2000_fu_603_ap_start_reg;

assign grp_fu_1084_p1 = 92'd140737488;

assign grp_fu_1132_p1 = 109'd28147497671065;

assign grp_fu_1181_p0 = sext_ln1115_4_reg_2024;

assign grp_fu_1181_p1 = sext_ln1115_4_reg_2024;

assign grp_fu_1188_p0 = sext_ln1115_5_fu_1185_p1;

assign grp_fu_1188_p1 = sext_ln1115_5_fu_1185_p1;

assign grp_fu_1323_p0 = grp_fu_1323_p00;

assign grp_fu_1323_p00 = reg_647;

assign grp_fu_1323_p1 = grp_fu_1323_p10;

assign grp_fu_1323_p10 = in_3;

assign grp_fu_1402_p0 = sext_ln1115_1_reg_1855;

assign grp_fu_1402_p1 = sext_ln1115_7_fu_1399_p1;

assign grp_fu_1407_p0 = sext_ln1115_7_fu_1399_p1;

assign grp_fu_1407_p1 = sext_ln1115_reg_1842;

assign grp_fu_1495_p0 = grp_fu_1495_p00;

assign grp_fu_1495_p00 = reg_647;

assign grp_fu_1495_p1 = grp_fu_1495_p10;

assign grp_fu_1495_p10 = valor_V_reg_2067;

assign grp_fu_1504_p1 = 151'd74670562277106236282987520;

assign grp_fu_1526_p1 = 153'd298683041390048068721541120;

assign grp_fu_1644_p1 = sext_ln1115_6_fu_1637_p1;

assign grp_fu_1654_p1 = sext_ln1115_6_fu_1637_p1;

assign grp_fu_748_p1 = 160'd187649984473770;

assign grp_fu_757_p1 = 112'd162509653574040;

assign grp_fu_808_p0 = sext_ln1118_2_fu_805_p1;

assign grp_fu_808_p1 = sext_ln1115_fu_801_p1;

assign grp_fu_821_p0 = sext_ln1118_3_fu_818_p1;

assign grp_fu_821_p1 = sext_ln1115_1_fu_814_p1;

assign grp_fu_827_p0 = sext_ln1115_1_fu_814_p1;

assign grp_fu_827_p1 = sext_ln1118_2_fu_805_p1;

assign grp_fu_833_p0 = sext_ln1118_3_fu_818_p1;

assign grp_fu_833_p1 = sext_ln1115_fu_801_p1;

assign grp_fu_846_p0 = sext_ln1118_4_fu_843_p1;

assign grp_fu_855_p0 = sext_ln1118_4_fu_843_p1;

assign grp_fu_990_p1 = 150'd39614081157116228272128000;

assign grp_fu_999_p1 = 112'd5629499534213120;

assign grp_sin_2000_fu_632_ap_start = grp_sin_2000_fu_632_ap_start_reg;

assign half_list_1_fu_1276_p2 = (div1_i_i1_cast_fu_1272_p1 + intervalo_begin_5_reg_462);

assign half_list_fu_1448_p2 = (div1_i_i_cast_fu_1444_p1 + intervalo_begin_4_reg_486);

assign icmp_ln1494_10_fu_1291_p2 = (($signed(zext_ln1494_1_fu_1287_p1) < $signed(in_3)) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_1463_p2 = (($signed(valor_V_reg_2067) > $signed(zext_ln1494_fu_1459_p1)) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_1076_p2 = (($signed(theta1_V) < $signed(64'd1768559438007110)) ? 1'b1 : 1'b0);

assign icmp_ln926_1_fu_1256_p2 = (($signed(tmp_10_fu_1246_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln926_fu_1428_p2 = (($signed(tmp_9_fu_1418_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign intervalo_begin_2_fu_1468_p3 = ((icmp_ln1494_fu_1463_p2[0:0] == 1'b1) ? half_list_reg_2159 : intervalo_begin_4_reg_486);

assign intervalo_begin_fu_1296_p3 = ((icmp_ln1494_10_fu_1291_p2[0:0] == 1'b1) ? half_list_1_reg_2084 : intervalo_begin_5_reg_462);

assign intervalo_end_2_fu_1475_p3 = ((icmp_ln1494_fu_1463_p2[0:0] == 1'b1) ? intervalo_end_reg_498 : half_list_reg_2159);

assign intervalo_end_3_fu_1303_p3 = ((icmp_ln1494_10_fu_1291_p2[0:0] == 1'b1) ? intervalo_end_1_reg_474 : half_list_1_reg_2084);

assign lhs_V_12_fu_1569_p1 = delta_V;

assign lhs_V_12_fu_1569_p3 = {{lhs_V_12_fu_1569_p1}, {96'd0}};

assign lhs_V_15_fu_1601_p1 = Amp_vneg_V;

assign lhs_V_15_fu_1601_p3 = {{lhs_V_15_fu_1601_p1}, {96'd0}};

assign lhs_V_2_fu_937_p3 = {{tmp_1_reg_1926}, {48'd0}};

assign lhs_V_3_fu_959_p3 = {{tmp_2_reg_1936}, {48'd0}};

assign lhs_V_5_fu_1009_p3 = {{wi_V}, {96'd0}};

assign lhs_V_7_fu_1047_p3 = {{ret_V_24_fu_1042_p2}, {48'd0}};

assign lhs_V_9_fu_1090_p3 = {{theta1_V}, {48'd0}};

assign lhs_fu_717_p3 = {{vin_a}, {48'd0}};

assign or_ln1159_fu_1226_p2 = (xor_ln229_fu_1214_p2 | tmp_8_fu_1219_p3);

assign pll_alpha_out = pll_alfa_V;

assign pll_beta_out = pll_beta_V;

assign q_inv_d_out = q_inv_d_V;

assign r_V_31_fu_911_p2 = (v1_d_comp_V + trunc_ln708_3_fu_879_p4);

assign r_V_33_fu_1548_p2 = (112'd0 - mul_ln1118_reg_2225);

assign r_V_34_fu_709_p3 = {{ret_V_fu_703_p2}, {47'd0}};

assign ret_V_10_fu_893_p2 = (r_V_38_reg_1902 + r_V_37_reg_1896);

assign ret_V_11_fu_944_p2 = (lhs_V_2_fu_937_p3 - r_V_11_reg_1921);

assign ret_V_12_fu_966_p2 = (lhs_V_3_fu_959_p3 + r_V_13_reg_1931);

assign ret_V_13_fu_1020_p2 = ($signed(lhs_V_5_fu_1009_p3) + $signed(sext_ln703_2_fu_1017_p1));

assign ret_V_15_fu_1055_p2 = (lhs_V_7_fu_1047_p3 + r_V_15_reg_1974);

assign ret_V_16_fu_1100_p2 = ($signed(lhs_V_9_fu_1090_p3) + $signed(sext_ln703_3_fu_1097_p1));

assign ret_V_17_fu_1194_p2 = (r_V_21_reg_2062 + r_V_19_reg_2057);

assign ret_V_18_fu_1366_p2 = (zext_ln1192_fu_1362_p1 + r_V_23_reg_2205);

assign ret_V_19_fu_1340_p2 = (zext_ln1192_1_fu_1336_p1 + r_V_25_reg_2130);

assign ret_V_20_fu_1388_p2 = ($signed(sext_ln703_4_fu_1381_p1) - $signed(sext_ln703_5_fu_1385_p1));

assign ret_V_21_fu_1579_p2 = ($signed(lhs_V_12_fu_1569_p3) + $signed(sext_ln703_6_fu_1576_p1));

assign ret_V_22_fu_1517_p2 = ($signed(sext_ln703_7_fu_1510_p1) - $signed(sext_ln703_8_fu_1514_p1));

assign ret_V_23_fu_1611_p2 = ($signed(lhs_V_15_fu_1601_p3) + $signed(sext_ln703_9_fu_1608_p1));

assign ret_V_24_fu_1042_p2 = (rhs_3_reg_1969 + 64'd84442493013196800);

assign ret_V_5_fu_733_p2 = ($signed(sext_ln1193_fu_725_p1) - $signed(sext_ln1193_1_fu_729_p1));

assign ret_V_6_fu_739_p2 = ($signed(sext_ln703_fu_695_p1) - $signed(sext_ln703_1_fu_699_p1));

assign ret_V_7_fu_861_p2 = (r_V_36_reg_1890 + r_V_35_reg_1884);

assign ret_V_8_fu_875_p2 = (r_V_37_reg_1896 - r_V_38_reg_1902);

assign ret_V_9_fu_889_p2 = (r_V_35_reg_1884 - r_V_36_reg_1890);

assign ret_V_fu_703_p2 = ($signed(sext_ln703_1_fu_699_p1) + $signed(sext_ln703_fu_695_p1));

assign rhs_5_fu_1355_p3 = {{rhs_4_reg_2190}, {48'd0}};

assign rhs_7_fu_1329_p3 = {{rhs_6_reg_2115}, {48'd0}};

assign select_ln1496_fu_1116_p3 = ((icmp_ln1496_reg_1984[0:0] == 1'b1) ? trunc_ln708_s_fu_1106_p4 : 64'd0);

assign sext_ln1115_1_fu_814_p1 = reg_639;

assign sext_ln1115_4_fu_1152_p1 = r_V_1_reg_1941;

assign sext_ln1115_5_fu_1185_p1 = r_V_20_reg_1946;

assign sext_ln1115_6_fu_1637_p1 = r_V_28_reg_2246;

assign sext_ln1115_7_fu_1399_p1 = r_V_31_reg_1914;

assign sext_ln1115_fu_801_p1 = reg_643;

assign sext_ln1118_2_fu_805_p1 = trunc_ln_reg_1825;

assign sext_ln1118_3_fu_818_p1 = trunc_ln708_1_reg_1831;

assign sext_ln1118_4_fu_843_p0 = amp_vPos_V;

assign sext_ln1118_4_fu_843_p1 = sext_ln1118_4_fu_843_p0;

assign sext_ln1193_1_fu_729_p1 = $signed(r_V_34_fu_709_p3);

assign sext_ln1193_fu_725_p1 = $signed(lhs_fu_717_p3);

assign sext_ln703_1_fu_699_p1 = $signed(vin_c);

assign sext_ln703_2_fu_1017_p1 = $signed(r_V_14_reg_1964);

assign sext_ln703_3_fu_1097_p1 = $signed(r_V_16_reg_1994);

assign sext_ln703_4_fu_1381_p1 = $signed(lhs_V_10_reg_448);

assign sext_ln703_5_fu_1385_p0 = delta_V;

assign sext_ln703_5_fu_1385_p1 = sext_ln703_5_fu_1385_p0;

assign sext_ln703_6_fu_1576_p1 = $signed(r_V_26_reg_2230);

assign sext_ln703_7_fu_1510_p1 = $signed(lhs_V_13_reg_510);

assign sext_ln703_8_fu_1514_p0 = Amp_vneg_V;

assign sext_ln703_8_fu_1514_p1 = sext_ln703_8_fu_1514_p0;

assign sext_ln703_9_fu_1608_p1 = $signed(r_V_27_reg_2241);

assign sext_ln703_fu_695_p1 = $signed(vin_b);

assign sext_ln708_fu_1148_p1 = $signed(trunc_ln708_4_fu_1138_p4);

assign shl_ln703_fu_763_p2 = theta1_V << 64'd1;

assign sub_ln703_fu_901_p2 = (trunc_ln708_2_fu_865_p4 - v1_q_comp_V);

assign sub_ln926_1_fu_1240_p2 = (intervalo_end_1_reg_474 - intervalo_begin_5_reg_462);

assign sub_ln926_fu_1412_p2 = (intervalo_end_reg_498 - intervalo_begin_4_reg_486);

assign theta_out = ap_phi_mux_theta1_V_loc_0_phi_fu_529_p4;

assign tmp_10_fu_1246_p4 = {{sub_ln926_1_fu_1240_p2[31:1]}};

assign tmp_8_fu_1219_p3 = in_3[32'd63];

assign tmp_9_fu_1418_p4 = {{sub_ln926_fu_1412_p2[31:1]}};

assign tmp_fu_1232_p3 = ret_V_17_fu_1194_p2[32'd111];

assign trunc_ln708_2_fu_865_p4 = {{ret_V_7_fu_861_p2[111:48]}};

assign trunc_ln708_3_fu_879_p4 = {{ret_V_8_fu_875_p2[111:48]}};

assign trunc_ln708_4_fu_1138_p4 = {{grp_fu_1132_p2[108:48]}};

assign trunc_ln708_s_fu_1106_p4 = {{ret_V_16_fu_1100_p2[111:48]}};

assign v2_d_limpo_out = ap_phi_mux_v2_d_limpo_V_loc_0_phi_fu_589_p4;

assign v_alfa_in = ap_phi_mux_v_alfa_V_loc_0_phi_fu_559_p4;

assign v_beta_in = ap_phi_mux_v_beta_V_loc_0_phi_fu_569_p4;

assign w_out = w_V;

assign xor_ln229_fu_1214_p2 = (1'd1 ^ EN6);

assign xor_ln870_fu_655_p2 = (sinc ^ aux_sinc_V);

assign zext_ln1166_1_fu_1310_p1 = intervalo_begin_5_reg_462;

assign zext_ln1166_fu_1482_p1 = intervalo_begin_4_reg_486;

assign zext_ln1192_1_fu_1336_p1 = rhs_7_fu_1329_p3;

assign zext_ln1192_fu_1362_p1 = rhs_5_fu_1355_p3;

assign zext_ln1494_1_fu_1287_p1 = table_mark_V_q0;

assign zext_ln1494_fu_1459_p1 = table_mark_V_q0;

assign zext_ln931_1_fu_1282_p1 = half_list_1_fu_1276_p2;

assign zext_ln931_fu_1454_p1 = half_list_fu_1448_p2;

always @ (posedge ap_clk) begin
    ret_V_5_reg_1798[46:0] <= 47'b00000000000000000000000000000000000000000000000;
    shl_ln703_reg_1818[0] <= 1'b0;
end

endmodule //PLL2026_x64
