#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("sinc", 1, hls_in, 0, "ap_none", "in_data", 1),
	Port_Property("vin_a", 64, hls_in, 1, "ap_none", "in_data", 1),
	Port_Property("vin_b", 64, hls_in, 2, "ap_none", "in_data", 1),
	Port_Property("vin_c", 64, hls_in, 3, "ap_none", "in_data", 1),
	Port_Property("w_out", 64, hls_out, 4, "ap_vld", "out_data", 1),
	Port_Property("w_out_ap_vld", 1, hls_out, 4, "ap_vld", "out_vld", 1),
	Port_Property("theta_out", 64, hls_out, 5, "ap_vld", "out_data", 1),
	Port_Property("theta_out_ap_vld", 1, hls_out, 5, "ap_vld", "out_vld", 1),
	Port_Property("pll_alpha_out", 64, hls_out, 6, "ap_vld", "out_data", 1),
	Port_Property("pll_alpha_out_ap_vld", 1, hls_out, 6, "ap_vld", "out_vld", 1),
	Port_Property("pll_beta_out", 64, hls_out, 7, "ap_vld", "out_data", 1),
	Port_Property("pll_beta_out_ap_vld", 1, hls_out, 7, "ap_vld", "out_vld", 1),
	Port_Property("amp_vPos_out", 64, hls_out, 8, "ap_vld", "out_data", 1),
	Port_Property("amp_vPos_out_ap_vld", 1, hls_out, 8, "ap_vld", "out_vld", 1),
	Port_Property("Amp_vneg_out", 64, hls_out, 9, "ap_vld", "out_data", 1),
	Port_Property("Amp_vneg_out_ap_vld", 1, hls_out, 9, "ap_vld", "out_vld", 1),
	Port_Property("delta_out", 64, hls_out, 10, "ap_vld", "out_data", 1),
	Port_Property("delta_out_ap_vld", 1, hls_out, 10, "ap_vld", "out_vld", 1),
};
const char* HLS_Design_Meta::dut_name = "PLL2026_x64";
