// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sin_gen_varAmp_3phi_x64_sin_gen_varAmp_3phi_x64,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.002400,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=24,HLS_SYN_DSP=0,HLS_SYN_FF=13139,HLS_SYN_LUT=11369,HLS_VERSION=2020_2}" *)

module sin_gen_varAmp_3phi_x64 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sinc,
        opt,
        f,
        A_1p,
        Ang_1p,
        A_1n,
        Ang_1n,
        A_5p,
        Ang_5p,
        A_5n,
        Ang_5n,
        A_7p,
        Ang_7p,
        A_7n,
        Ang_7n,
        vout_a,
        vout_a_ap_vld,
        vout_b,
        vout_b_ap_vld,
        vout_c,
        vout_c_ap_vld,
        wtout,
        wtout_ap_vld
);

parameter    ap_ST_fsm_state1 = 17'd1;
parameter    ap_ST_fsm_state2 = 17'd2;
parameter    ap_ST_fsm_state3 = 17'd4;
parameter    ap_ST_fsm_state4 = 17'd8;
parameter    ap_ST_fsm_state5 = 17'd16;
parameter    ap_ST_fsm_state6 = 17'd32;
parameter    ap_ST_fsm_state7 = 17'd64;
parameter    ap_ST_fsm_state8 = 17'd128;
parameter    ap_ST_fsm_state9 = 17'd256;
parameter    ap_ST_fsm_state10 = 17'd512;
parameter    ap_ST_fsm_state11 = 17'd1024;
parameter    ap_ST_fsm_state12 = 17'd2048;
parameter    ap_ST_fsm_state13 = 17'd4096;
parameter    ap_ST_fsm_state14 = 17'd8192;
parameter    ap_ST_fsm_state15 = 17'd16384;
parameter    ap_ST_fsm_state16 = 17'd32768;
parameter    ap_ST_fsm_state17 = 17'd65536;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] sinc;
input  [0:0] opt;
input  [63:0] f;
input  [63:0] A_1p;
input  [63:0] Ang_1p;
input  [63:0] A_1n;
input  [63:0] Ang_1n;
input  [63:0] A_5p;
input  [63:0] Ang_5p;
input  [63:0] A_5n;
input  [63:0] Ang_5n;
input  [63:0] A_7p;
input  [63:0] Ang_7p;
input  [63:0] A_7n;
input  [63:0] Ang_7n;
output  [63:0] vout_a;
output   vout_a_ap_vld;
output  [63:0] vout_b;
output   vout_b_ap_vld;
output  [63:0] vout_c;
output   vout_c_ap_vld;
output  [63:0] wtout;
output   wtout_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg vout_a_ap_vld;
reg vout_b_ap_vld;
reg vout_c_ap_vld;
reg wtout_ap_vld;

(* fsm_encoding = "none" *) reg   [16:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] aux_sinc_V;
reg   [63:0] wt_V;
reg   [63:0] va_V;
reg   [63:0] vb_V;
reg   [63:0] vc_V;
wire   [49:0] grp_sin_2000_fu_218_ap_return;
reg  signed [49:0] reg_246;
wire    ap_CS_fsm_state9;
wire    grp_sin_2000_fu_218_ap_ready;
wire    grp_sin_2000_fu_218_ap_done;
wire    grp_sin_2000_fu_225_ap_ready;
wire    grp_sin_2000_fu_225_ap_done;
wire    grp_sin_2000_fu_232_ap_ready;
wire    grp_sin_2000_fu_232_ap_done;
wire    grp_sin_2000_fu_239_ap_ready;
wire    grp_sin_2000_fu_239_ap_done;
reg    ap_block_state9_on_subcall_done;
wire    ap_CS_fsm_state10;
reg    ap_block_state10_on_subcall_done;
wire    ap_CS_fsm_state11;
reg    ap_block_state11_on_subcall_done;
wire   [49:0] grp_sin_2000_fu_225_ap_return;
reg  signed [49:0] reg_250;
wire   [49:0] grp_sin_2000_fu_232_ap_return;
reg  signed [49:0] reg_254;
wire   [49:0] grp_sin_2000_fu_239_ap_return;
reg  signed [49:0] reg_258;
wire   [0:0] xor_ln870_fu_266_p2;
reg   [0:0] xor_ln870_reg_750;
wire   [0:0] icmp_ln1495_fu_282_p2;
reg   [0:0] icmp_ln1495_reg_759;
wire    ap_CS_fsm_state2;
reg   [45:0] trunc_ln_reg_769;
wire    ap_CS_fsm_state6;
wire   [63:0] select_ln38_fu_315_p3;
reg   [63:0] select_ln38_reg_774;
wire    ap_CS_fsm_state7;
wire   [63:0] add_ln703_1_fu_328_p2;
reg   [63:0] add_ln703_1_reg_783;
wire   [63:0] add_ln1192_fu_333_p2;
reg   [63:0] add_ln1192_reg_789;
wire   [63:0] add_ln703_2_fu_338_p2;
reg   [63:0] add_ln703_2_reg_795;
wire    ap_CS_fsm_state8;
wire   [63:0] add_ln703_3_fu_344_p2;
reg   [63:0] add_ln703_3_reg_800;
wire   [63:0] add_ln703_4_fu_360_p2;
reg   [63:0] add_ln703_4_reg_805;
wire   [63:0] add_ln1192_4_fu_365_p2;
reg   [63:0] add_ln1192_4_reg_811;
wire   [63:0] add_ln703_10_fu_370_p2;
reg   [63:0] add_ln703_10_reg_817;
wire   [63:0] add_ln703_11_fu_376_p2;
reg   [63:0] add_ln703_11_reg_822;
wire   [63:0] add_ln703_5_fu_382_p2;
reg   [63:0] add_ln703_5_reg_827;
wire   [63:0] add_ln703_6_fu_388_p2;
reg   [63:0] add_ln703_6_reg_832;
wire   [63:0] add_ln703_7_fu_404_p2;
reg   [63:0] add_ln703_7_reg_837;
wire   [63:0] add_ln1192_7_fu_409_p2;
reg   [63:0] add_ln1192_7_reg_843;
wire   [63:0] add_ln703_12_fu_414_p2;
reg   [63:0] add_ln703_12_reg_849;
wire   [63:0] add_ln703_13_fu_420_p2;
reg   [63:0] add_ln703_13_reg_854;
wire  signed [111:0] sext_ln1115_fu_426_p1;
wire  signed [111:0] sext_ln1115_1_fu_439_p1;
wire   [63:0] add_ln703_8_fu_452_p2;
reg   [63:0] add_ln703_8_reg_881;
wire   [63:0] add_ln703_9_fu_458_p2;
reg   [63:0] add_ln703_9_reg_886;
wire   [63:0] add_ln703_14_fu_484_p2;
reg   [63:0] add_ln703_14_reg_901;
wire   [63:0] add_ln703_15_fu_490_p2;
reg   [63:0] add_ln703_15_reg_906;
wire  signed [111:0] sext_ln1115_2_fu_496_p1;
wire  signed [111:0] sext_ln1115_3_fu_509_p1;
wire  signed [111:0] sext_ln1115_4_fu_542_p1;
wire    ap_CS_fsm_state12;
wire  signed [111:0] sext_ln1115_5_fu_555_p1;
wire   [111:0] grp_fu_433_p2;
reg   [111:0] r_V_13_reg_975;
wire    ap_CS_fsm_state14;
wire   [111:0] grp_fu_446_p2;
reg   [111:0] r_V_14_reg_980;
wire   [111:0] grp_fu_468_p2;
reg   [111:0] r_V_17_reg_985;
wire   [111:0] grp_fu_478_p2;
reg   [111:0] r_V_18_reg_990;
wire   [111:0] ret_V_10_fu_588_p2;
reg   [111:0] ret_V_10_reg_995;
wire    ap_CS_fsm_state15;
wire   [111:0] grp_fu_503_p2;
reg   [111:0] r_V_15_reg_1000;
wire   [111:0] grp_fu_516_p2;
reg   [111:0] r_V_16_reg_1005;
wire   [111:0] ret_V_12_fu_592_p2;
reg   [111:0] ret_V_12_reg_1010;
wire   [111:0] grp_fu_526_p2;
reg   [111:0] r_V_19_reg_1015;
wire   [111:0] grp_fu_536_p2;
reg   [111:0] r_V_20_reg_1020;
wire   [111:0] ret_V_fu_600_p2;
reg   [111:0] ret_V_reg_1025;
wire    ap_CS_fsm_state16;
wire   [111:0] grp_fu_549_p2;
reg   [111:0] r_V_5_reg_1030;
wire   [111:0] grp_fu_562_p2;
reg   [111:0] r_V_6_reg_1035;
wire   [111:0] ret_V_7_fu_609_p2;
reg   [111:0] ret_V_7_reg_1040;
wire   [111:0] grp_fu_572_p2;
reg   [111:0] r_V_11_reg_1045;
wire   [111:0] grp_fu_582_p2;
reg   [111:0] r_V_12_reg_1050;
wire    grp_sin_2000_fu_218_ap_start;
wire    grp_sin_2000_fu_218_ap_idle;
reg   [63:0] grp_sin_2000_fu_218_theta_in;
wire    grp_sin_2000_fu_225_ap_start;
wire    grp_sin_2000_fu_225_ap_idle;
reg   [63:0] grp_sin_2000_fu_225_theta_in;
wire    grp_sin_2000_fu_232_ap_start;
wire    grp_sin_2000_fu_232_ap_idle;
reg   [63:0] grp_sin_2000_fu_232_theta_in;
wire    grp_sin_2000_fu_239_ap_start;
wire    grp_sin_2000_fu_239_ap_idle;
reg   [63:0] grp_sin_2000_fu_239_theta_in;
reg   [63:0] ap_phi_mux_wt_V_loc_0_phi_fu_211_p4;
reg   [63:0] wt_V_loc_0_reg_208;
wire    ap_CS_fsm_state17;
reg    grp_sin_2000_fu_218_ap_start_reg;
reg    grp_sin_2000_fu_225_ap_start_reg;
reg    grp_sin_2000_fu_232_ap_start_reg;
reg    grp_sin_2000_fu_239_ap_start_reg;
reg   [63:0] ap_sig_allocacmp_va_V_load;
reg   [63:0] ap_sig_allocacmp_vb_V_load;
reg   [63:0] ap_sig_allocacmp_vc_V_load;
wire   [30:0] grp_fu_291_p1;
wire   [93:0] grp_fu_291_p2;
wire  signed [63:0] sext_ln708_fu_307_p1;
wire   [63:0] add_ln703_fu_310_p2;
wire   [63:0] shl_ln1192_fu_350_p2;
wire   [63:0] add_ln1192_2_fu_355_p2;
wire   [63:0] shl_ln1192_1_fu_394_p2;
wire   [63:0] sub_ln1192_fu_399_p2;
wire  signed [63:0] grp_fu_433_p1;
wire  signed [63:0] grp_fu_446_p1;
wire  signed [63:0] grp_fu_468_p1;
wire  signed [63:0] grp_fu_478_p1;
wire  signed [63:0] grp_fu_503_p1;
wire  signed [63:0] grp_fu_516_p1;
wire  signed [63:0] grp_fu_526_p1;
wire  signed [63:0] grp_fu_536_p1;
wire  signed [63:0] grp_fu_549_p1;
wire  signed [63:0] grp_fu_562_p1;
wire  signed [63:0] grp_fu_572_p1;
wire  signed [63:0] grp_fu_582_p1;
wire   [111:0] ret_V_11_fu_596_p2;
wire   [111:0] ret_V_13_fu_605_p2;
wire   [111:0] ret_V_3_fu_614_p2;
wire   [111:0] ret_V_4_fu_618_p2;
wire   [111:0] ret_V_8_fu_645_p2;
wire   [111:0] ret_V_9_fu_649_p2;
reg    grp_fu_433_ce;
wire    ap_CS_fsm_state13;
reg    grp_fu_446_ce;
reg    grp_fu_468_ce;
reg    grp_fu_478_ce;
reg    grp_fu_503_ce;
reg    grp_fu_516_ce;
reg    grp_fu_526_ce;
reg    grp_fu_536_ce;
reg   [16:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 17'd1;
#0 aux_sinc_V = 1'd0;
#0 wt_V = 64'd0;
#0 va_V = 64'd0;
#0 vb_V = 64'd0;
#0 vc_V = 64'd0;
#0 grp_sin_2000_fu_218_ap_start_reg = 1'b0;
#0 grp_sin_2000_fu_225_ap_start_reg = 1'b0;
#0 grp_sin_2000_fu_232_ap_start_reg = 1'b0;
#0 grp_sin_2000_fu_239_ap_start_reg = 1'b0;
end

sin_gen_varAmp_3phi_x64_sin_2000 grp_sin_2000_fu_218(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_218_ap_start),
    .ap_done(grp_sin_2000_fu_218_ap_done),
    .ap_idle(grp_sin_2000_fu_218_ap_idle),
    .ap_ready(grp_sin_2000_fu_218_ap_ready),
    .theta_in(grp_sin_2000_fu_218_theta_in),
    .ap_return(grp_sin_2000_fu_218_ap_return)
);

sin_gen_varAmp_3phi_x64_sin_2000 grp_sin_2000_fu_225(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_225_ap_start),
    .ap_done(grp_sin_2000_fu_225_ap_done),
    .ap_idle(grp_sin_2000_fu_225_ap_idle),
    .ap_ready(grp_sin_2000_fu_225_ap_ready),
    .theta_in(grp_sin_2000_fu_225_theta_in),
    .ap_return(grp_sin_2000_fu_225_ap_return)
);

sin_gen_varAmp_3phi_x64_sin_2000 grp_sin_2000_fu_232(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_232_ap_start),
    .ap_done(grp_sin_2000_fu_232_ap_done),
    .ap_idle(grp_sin_2000_fu_232_ap_idle),
    .ap_ready(grp_sin_2000_fu_232_ap_ready),
    .theta_in(grp_sin_2000_fu_232_theta_in),
    .ap_return(grp_sin_2000_fu_232_ap_return)
);

sin_gen_varAmp_3phi_x64_sin_2000 grp_sin_2000_fu_239(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_2000_fu_239_ap_start),
    .ap_done(grp_sin_2000_fu_239_ap_done),
    .ap_idle(grp_sin_2000_fu_239_ap_idle),
    .ap_ready(grp_sin_2000_fu_239_ap_ready),
    .theta_in(grp_sin_2000_fu_239_theta_in),
    .ap_return(grp_sin_2000_fu_239_ap_return)
);

sin_gen_varAmp_3phi_x64_mul_64s_31ns_94_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 94 ))
mul_64s_31ns_94_5_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(f),
    .din1(grp_fu_291_p1),
    .ce(1'b1),
    .dout(grp_fu_291_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_246),
    .din1(grp_fu_433_p1),
    .ce(grp_fu_433_ce),
    .dout(grp_fu_433_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_250),
    .din1(grp_fu_446_p1),
    .ce(grp_fu_446_ce),
    .dout(grp_fu_446_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_254),
    .din1(grp_fu_468_p1),
    .ce(grp_fu_468_ce),
    .dout(grp_fu_468_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_258),
    .din1(grp_fu_478_p1),
    .ce(grp_fu_478_ce),
    .dout(grp_fu_478_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_246),
    .din1(grp_fu_503_p1),
    .ce(grp_fu_503_ce),
    .dout(grp_fu_503_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_250),
    .din1(grp_fu_516_p1),
    .ce(grp_fu_516_ce),
    .dout(grp_fu_516_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_254),
    .din1(grp_fu_526_p1),
    .ce(grp_fu_526_ce),
    .dout(grp_fu_526_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_258),
    .din1(grp_fu_536_p1),
    .ce(grp_fu_536_ce),
    .dout(grp_fu_536_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_246),
    .din1(grp_fu_549_p1),
    .ce(1'b1),
    .dout(grp_fu_549_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_250),
    .din1(grp_fu_562_p1),
    .ce(1'b1),
    .dout(grp_fu_562_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U16(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_254),
    .din1(grp_fu_572_p1),
    .ce(1'b1),
    .dout(grp_fu_572_p2)
);

sin_gen_varAmp_3phi_x64_mul_50s_64s_112_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 50 ),
    .din1_WIDTH( 64 ),
    .dout_WIDTH( 112 ))
mul_50s_64s_112_5_1_U17(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_258),
    .din1(grp_fu_582_p1),
    .ce(1'b1),
    .dout(grp_fu_582_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_218_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
            grp_sin_2000_fu_218_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_218_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_218_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_225_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
            grp_sin_2000_fu_225_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_225_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_225_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_232_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
            grp_sin_2000_fu_232_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_232_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_232_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_2000_fu_239_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state8) | ((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
            grp_sin_2000_fu_239_ap_start_reg <= 1'b1;
        end else if ((grp_sin_2000_fu_239_ap_ready == 1'b1)) begin
            grp_sin_2000_fu_239_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (xor_ln870_fu_266_p2 == 1'd0))) begin
        wt_V_loc_0_reg_208 <= wt_V;
    end else if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        wt_V_loc_0_reg_208 <= select_ln38_reg_774;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        add_ln1192_4_reg_811 <= add_ln1192_4_fu_365_p2;
        add_ln703_10_reg_817 <= add_ln703_10_fu_370_p2;
        add_ln703_11_reg_822 <= add_ln703_11_fu_376_p2;
        add_ln703_2_reg_795 <= add_ln703_2_fu_338_p2;
        add_ln703_3_reg_800 <= add_ln703_3_fu_344_p2;
        add_ln703_4_reg_805 <= add_ln703_4_fu_360_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln1192_7_reg_843 <= add_ln1192_7_fu_409_p2;
        add_ln703_12_reg_849 <= add_ln703_12_fu_414_p2;
        add_ln703_13_reg_854 <= add_ln703_13_fu_420_p2;
        add_ln703_5_reg_827 <= add_ln703_5_fu_382_p2;
        add_ln703_6_reg_832 <= add_ln703_6_fu_388_p2;
        add_ln703_7_reg_837 <= add_ln703_7_fu_404_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        add_ln1192_reg_789 <= add_ln1192_fu_333_p2;
        add_ln703_1_reg_783 <= add_ln703_1_fu_328_p2;
        select_ln38_reg_774 <= select_ln38_fu_315_p3;
        wt_V <= select_ln38_fu_315_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln703_14_reg_901 <= add_ln703_14_fu_484_p2;
        add_ln703_15_reg_906 <= add_ln703_15_fu_490_p2;
        add_ln703_8_reg_881 <= add_ln703_8_fu_452_p2;
        add_ln703_9_reg_886 <= add_ln703_9_fu_458_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (xor_ln870_fu_266_p2 == 1'd1))) begin
        aux_sinc_V <= sinc;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (xor_ln870_fu_266_p2 == 1'd1))) begin
        icmp_ln1495_reg_759 <= icmp_ln1495_fu_282_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        r_V_11_reg_1045 <= grp_fu_572_p2;
        r_V_12_reg_1050 <= grp_fu_582_p2;
        r_V_5_reg_1030 <= grp_fu_549_p2;
        r_V_6_reg_1035 <= grp_fu_562_p2;
        ret_V_7_reg_1040 <= ret_V_7_fu_609_p2;
        ret_V_reg_1025 <= ret_V_fu_600_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        r_V_13_reg_975 <= grp_fu_433_p2;
        r_V_14_reg_980 <= grp_fu_446_p2;
        r_V_17_reg_985 <= grp_fu_468_p2;
        r_V_18_reg_990 <= grp_fu_478_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        r_V_15_reg_1000 <= grp_fu_503_p2;
        r_V_16_reg_1005 <= grp_fu_516_p2;
        r_V_19_reg_1015 <= grp_fu_526_p2;
        r_V_20_reg_1020 <= grp_fu_536_p2;
        ret_V_10_reg_995 <= ret_V_10_fu_588_p2;
        ret_V_12_reg_1010 <= ret_V_12_fu_592_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9)) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
        reg_246 <= grp_sin_2000_fu_218_ap_return;
        reg_250 <= grp_sin_2000_fu_225_ap_return;
        reg_254 <= grp_sin_2000_fu_232_ap_return;
        reg_258 <= grp_sin_2000_fu_239_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln1495_reg_759 == 1'd1))) begin
        trunc_ln_reg_769 <= {{grp_fu_291_p2[93:48]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        va_V <= {{ret_V_4_fu_618_p2[111:48]}};
        vb_V <= {{ret_V_4_fu_618_p2[111:48]}};
        vc_V <= {{ret_V_9_fu_649_p2[111:48]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        xor_ln870_reg_750 <= xor_ln870_fu_266_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        ap_phi_mux_wt_V_loc_0_phi_fu_211_p4 = select_ln38_reg_774;
    end else begin
        ap_phi_mux_wt_V_loc_0_phi_fu_211_p4 = wt_V_loc_0_reg_208;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        ap_sig_allocacmp_va_V_load = {{ret_V_4_fu_618_p2[111:48]}};
    end else begin
        ap_sig_allocacmp_va_V_load = va_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        ap_sig_allocacmp_vb_V_load = {{ret_V_4_fu_618_p2[111:48]}};
    end else begin
        ap_sig_allocacmp_vb_V_load = vb_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state17) & (xor_ln870_reg_750 == 1'd1))) begin
        ap_sig_allocacmp_vc_V_load = {{ret_V_9_fu_649_p2[111:48]}};
    end else begin
        ap_sig_allocacmp_vc_V_load = vc_V;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_433_ce = 1'b1;
    end else begin
        grp_fu_433_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_446_ce = 1'b1;
    end else begin
        grp_fu_446_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_468_ce = 1'b1;
    end else begin
        grp_fu_468_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)) | ((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_478_ce = 1'b1;
    end else begin
        grp_fu_478_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_503_ce = 1'b1;
    end else begin
        grp_fu_503_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_516_ce = 1'b1;
    end else begin
        grp_fu_516_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_526_ce = 1'b1;
    end else begin
        grp_fu_526_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state12) | ((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11)))) begin
        grp_fu_536_ce = 1'b1;
    end else begin
        grp_fu_536_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_sin_2000_fu_218_theta_in = add_ln703_8_reg_881;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_sin_2000_fu_218_theta_in = add_ln703_5_reg_827;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_sin_2000_fu_218_theta_in = add_ln703_2_reg_795;
    end else begin
        grp_sin_2000_fu_218_theta_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_sin_2000_fu_225_theta_in = add_ln703_9_reg_886;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_sin_2000_fu_225_theta_in = add_ln703_6_reg_832;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_sin_2000_fu_225_theta_in = add_ln703_3_reg_800;
    end else begin
        grp_sin_2000_fu_225_theta_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_sin_2000_fu_232_theta_in = add_ln703_14_reg_901;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_sin_2000_fu_232_theta_in = add_ln703_12_reg_849;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_sin_2000_fu_232_theta_in = add_ln703_10_reg_817;
    end else begin
        grp_sin_2000_fu_232_theta_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_sin_2000_fu_239_theta_in = add_ln703_15_reg_906;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_sin_2000_fu_239_theta_in = add_ln703_13_reg_854;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_sin_2000_fu_239_theta_in = add_ln703_11_reg_822;
    end else begin
        grp_sin_2000_fu_239_theta_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        vout_a_ap_vld = 1'b1;
    end else begin
        vout_a_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        vout_b_ap_vld = 1'b1;
    end else begin
        vout_b_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        vout_c_ap_vld = 1'b1;
    end else begin
        vout_c_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        wtout_ap_vld = 1'b1;
    end else begin
        wtout_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (xor_ln870_fu_266_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state17;
            end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (xor_ln870_fu_266_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((1'b0 == ap_block_state9_on_subcall_done) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b0 == ap_block_state10_on_subcall_done) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1192_2_fu_355_p2 = (shl_ln1192_fu_350_p2 + select_ln38_reg_774);

assign add_ln1192_4_fu_365_p2 = (add_ln1192_2_fu_355_p2 + Ang_5n);

assign add_ln1192_7_fu_409_p2 = (sub_ln1192_fu_399_p2 + Ang_7n);

assign add_ln1192_fu_333_p2 = (select_ln38_fu_315_p3 + Ang_1n);

assign add_ln703_10_fu_370_p2 = (add_ln703_1_reg_783 + 64'd589519812668137);

assign add_ln703_11_fu_376_p2 = ($signed(add_ln1192_reg_789) + $signed(64'd18446154553896883479));

assign add_ln703_12_fu_414_p2 = (add_ln703_4_reg_805 + 64'd589519812668137);

assign add_ln703_13_fu_420_p2 = ($signed(add_ln1192_4_reg_811) + $signed(64'd18446154553896883479));

assign add_ln703_14_fu_484_p2 = (add_ln703_7_reg_837 + 64'd589519812668137);

assign add_ln703_15_fu_490_p2 = ($signed(add_ln1192_7_reg_843) + $signed(64'd18446154553896883479));

assign add_ln703_1_fu_328_p2 = (select_ln38_fu_315_p3 + Ang_1p);

assign add_ln703_2_fu_338_p2 = ($signed(add_ln703_1_reg_783) + $signed(64'd18446154553896883479));

assign add_ln703_3_fu_344_p2 = (add_ln1192_reg_789 + 64'd589519812668137);

assign add_ln703_4_fu_360_p2 = (add_ln1192_2_fu_355_p2 + Ang_5p);

assign add_ln703_5_fu_382_p2 = ($signed(add_ln703_4_reg_805) + $signed(64'd18446154553896883479));

assign add_ln703_6_fu_388_p2 = (add_ln1192_4_reg_811 + 64'd589519812668137);

assign add_ln703_7_fu_404_p2 = (sub_ln1192_fu_399_p2 + Ang_7p);

assign add_ln703_8_fu_452_p2 = ($signed(add_ln703_7_reg_837) + $signed(64'd18446154553896883479));

assign add_ln703_9_fu_458_p2 = (add_ln1192_7_reg_843 + 64'd589519812668137);

assign add_ln703_fu_310_p2 = ($signed(wt_V) + $signed(sext_ln708_fu_307_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state10_on_subcall_done = ((grp_sin_2000_fu_239_ap_done == 1'b0) | (grp_sin_2000_fu_232_ap_done == 1'b0) | (grp_sin_2000_fu_225_ap_done == 1'b0) | (grp_sin_2000_fu_218_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state11_on_subcall_done = ((grp_sin_2000_fu_239_ap_done == 1'b0) | (grp_sin_2000_fu_232_ap_done == 1'b0) | (grp_sin_2000_fu_225_ap_done == 1'b0) | (grp_sin_2000_fu_218_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state9_on_subcall_done = ((grp_sin_2000_fu_239_ap_done == 1'b0) | (grp_sin_2000_fu_232_ap_done == 1'b0) | (grp_sin_2000_fu_225_ap_done == 1'b0) | (grp_sin_2000_fu_218_ap_done == 1'b0));
end

assign grp_fu_291_p1 = 94'd884279719;

assign grp_fu_433_p1 = sext_ln1115_fu_426_p1;

assign grp_fu_446_p1 = sext_ln1115_1_fu_439_p1;

assign grp_fu_468_p1 = sext_ln1115_fu_426_p1;

assign grp_fu_478_p1 = sext_ln1115_1_fu_439_p1;

assign grp_fu_503_p1 = sext_ln1115_2_fu_496_p1;

assign grp_fu_516_p1 = sext_ln1115_3_fu_509_p1;

assign grp_fu_526_p1 = sext_ln1115_2_fu_496_p1;

assign grp_fu_536_p1 = sext_ln1115_3_fu_509_p1;

assign grp_fu_549_p1 = sext_ln1115_4_fu_542_p1;

assign grp_fu_562_p1 = sext_ln1115_5_fu_555_p1;

assign grp_fu_572_p1 = sext_ln1115_4_fu_542_p1;

assign grp_fu_582_p1 = sext_ln1115_5_fu_555_p1;

assign grp_sin_2000_fu_218_ap_start = grp_sin_2000_fu_218_ap_start_reg;

assign grp_sin_2000_fu_225_ap_start = grp_sin_2000_fu_225_ap_start_reg;

assign grp_sin_2000_fu_232_ap_start = grp_sin_2000_fu_232_ap_start_reg;

assign grp_sin_2000_fu_239_ap_start = grp_sin_2000_fu_239_ap_start_reg;

assign icmp_ln1495_fu_282_p2 = (($signed(wt_V) < $signed(64'd1768559438007110)) ? 1'b1 : 1'b0);

assign ret_V_10_fu_588_p2 = (r_V_14_reg_980 + r_V_13_reg_975);

assign ret_V_11_fu_596_p2 = (ret_V_10_reg_995 + r_V_15_reg_1000);

assign ret_V_12_fu_592_p2 = (r_V_18_reg_990 + r_V_17_reg_985);

assign ret_V_13_fu_605_p2 = (ret_V_12_reg_1010 + r_V_19_reg_1015);

assign ret_V_3_fu_614_p2 = (ret_V_reg_1025 + r_V_5_reg_1030);

assign ret_V_4_fu_618_p2 = (ret_V_3_fu_614_p2 + r_V_6_reg_1035);

assign ret_V_7_fu_609_p2 = (ret_V_13_fu_605_p2 + r_V_20_reg_1020);

assign ret_V_8_fu_645_p2 = (ret_V_7_reg_1040 + r_V_11_reg_1045);

assign ret_V_9_fu_649_p2 = (ret_V_8_fu_645_p2 + r_V_12_reg_1050);

assign ret_V_fu_600_p2 = (ret_V_11_fu_596_p2 + r_V_16_reg_1005);

assign select_ln38_fu_315_p3 = ((icmp_ln1495_reg_759[0:0] == 1'b1) ? add_ln703_fu_310_p2 : 64'd0);

assign sext_ln1115_1_fu_439_p1 = $signed(A_1n);

assign sext_ln1115_2_fu_496_p1 = $signed(A_5p);

assign sext_ln1115_3_fu_509_p1 = $signed(A_5n);

assign sext_ln1115_4_fu_542_p1 = $signed(A_7p);

assign sext_ln1115_5_fu_555_p1 = $signed(A_7n);

assign sext_ln1115_fu_426_p1 = $signed(A_1p);

assign sext_ln708_fu_307_p1 = $signed(trunc_ln_reg_769);

assign shl_ln1192_1_fu_394_p2 = select_ln38_reg_774 << 64'd3;

assign shl_ln1192_fu_350_p2 = select_ln38_reg_774 << 64'd2;

assign sub_ln1192_fu_399_p2 = (shl_ln1192_1_fu_394_p2 - select_ln38_reg_774);

assign vout_a = ap_sig_allocacmp_va_V_load;

assign vout_b = ap_sig_allocacmp_vb_V_load;

assign vout_c = ap_sig_allocacmp_vc_V_load;

assign wtout = ap_phi_mux_wt_V_loc_0_phi_fu_211_p4;

assign xor_ln870_fu_266_p2 = (sinc ^ aux_sinc_V);

endmodule //sin_gen_varAmp_3phi_x64
