-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sin_gen_varAmp2_3phi_x64 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sinc : IN STD_LOGIC_VECTOR (0 downto 0);
    opt : IN STD_LOGIC_VECTOR (0 downto 0);
    f : IN STD_LOGIC_VECTOR (63 downto 0);
    A_1p : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_1p : IN STD_LOGIC_VECTOR (63 downto 0);
    A_1n : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_1n : IN STD_LOGIC_VECTOR (63 downto 0);
    A_5p : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_5p : IN STD_LOGIC_VECTOR (63 downto 0);
    A_5n : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_5n : IN STD_LOGIC_VECTOR (63 downto 0);
    A_7p : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_7p : IN STD_LOGIC_VECTOR (63 downto 0);
    A_7n : IN STD_LOGIC_VECTOR (63 downto 0);
    Ang_7n : IN STD_LOGIC_VECTOR (63 downto 0);
    vout_a : OUT STD_LOGIC_VECTOR (63 downto 0);
    vout_a_ap_vld : OUT STD_LOGIC;
    vout_b : OUT STD_LOGIC_VECTOR (63 downto 0);
    vout_b_ap_vld : OUT STD_LOGIC;
    vout_c : OUT STD_LOGIC_VECTOR (63 downto 0);
    vout_c_ap_vld : OUT STD_LOGIC;
    wtout : OUT STD_LOGIC_VECTOR (63 downto 0);
    wtout_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sin_gen_varAmp2_3phi_x64 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "sin_gen_varAmp2_3phi_x64_sin_gen_varAmp2_3phi_x64,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200t-fbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.885150,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=54,HLS_SYN_DSP=0,HLS_SYN_FF=16971,HLS_SYN_LUT=13594,HLS_VERSION=2020_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (16 downto 0) := "00000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (16 downto 0) := "00000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (16 downto 0) := "00000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (16 downto 0) := "00000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (16 downto 0) := "00000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (16 downto 0) := "00000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (16 downto 0) := "00001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (16 downto 0) := "00010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (16 downto 0) := "00100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (16 downto 0) := "01000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv64_6487ED5110B46 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000110010010000111111011010101000100010000101101000110";
    constant ap_const_lv94_34B509A7 : STD_LOGIC_VECTOR (93 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000110100101101010000100110100111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_5D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011101";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv64_FFFDE7D5B8FA5517 : STD_LOGIC_VECTOR (63 downto 0) := "1111111111111101111001111101010110111000111110100101010100010111";
    constant ap_const_lv64_2182A4705AAE9 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000010000110000010101001000111000001011010101011101001";
    constant ap_const_lv64_3 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000011";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal aux_sinc_V : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal wt_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal va_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal vb_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal vc_V : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal grp_sin_2000_fu_218_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_260 : STD_LOGIC_VECTOR (49 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal grp_sin_2000_fu_218_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_218_ap_done : STD_LOGIC;
    signal grp_sin_2000_fu_225_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_225_ap_done : STD_LOGIC;
    signal grp_sin_2000_fu_232_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_232_ap_done : STD_LOGIC;
    signal grp_sin_2000_fu_239_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_239_ap_done : STD_LOGIC;
    signal grp_sin_2000_fu_246_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_246_ap_done : STD_LOGIC;
    signal grp_sin_2000_fu_253_ap_ready : STD_LOGIC;
    signal grp_sin_2000_fu_253_ap_done : STD_LOGIC;
    signal ap_block_state9_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_block_state10_on_subcall_done : BOOLEAN;
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_block_state11_on_subcall_done : BOOLEAN;
    signal grp_sin_2000_fu_225_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_264 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_sin_2000_fu_232_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_268 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_sin_2000_fu_239_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_272 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_sin_2000_fu_246_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_276 : STD_LOGIC_VECTOR (49 downto 0);
    signal grp_sin_2000_fu_253_ap_return : STD_LOGIC_VECTOR (49 downto 0);
    signal reg_280 : STD_LOGIC_VECTOR (49 downto 0);
    signal xor_ln870_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln870_reg_864 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1495_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1495_reg_873 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln_reg_883 : STD_LOGIC_VECTOR (45 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal select_ln38_fu_337_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln38_reg_888 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln703_1_fu_350_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_1_reg_897 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_2_fu_355_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_2_reg_904 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_3_fu_370_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_3_reg_911 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal add_ln703_4_fu_375_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_4_reg_918 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_7_fu_380_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_7_reg_925 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_8_fu_386_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_8_reg_930 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_13_fu_392_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_13_reg_935 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_14_fu_398_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_14_reg_940 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_5_fu_414_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_5_reg_945 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_6_fu_419_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_6_reg_952 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_9_fu_424_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_9_reg_959 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_10_fu_430_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_10_reg_964 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_15_fu_436_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_15_reg_969 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_16_fu_442_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_16_reg_974 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1115_fu_448_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal sext_ln1115_1_fu_461_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal add_ln703_11_fu_494_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_11_reg_1013 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_12_fu_500_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_12_reg_1018 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_17_fu_526_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_17_reg_1033 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_18_fu_532_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_18_reg_1038 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln1115_2_fu_538_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal sext_ln1115_3_fu_551_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal sext_ln1115_4_fu_604_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal sext_ln1115_5_fu_617_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_455_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_19_reg_1131 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal grp_fu_468_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_20_reg_1136 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_478_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_23_reg_1141 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_488_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_24_reg_1146 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_510_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_27_reg_1151 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_520_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_28_reg_1156 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_15_fu_670_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_15_reg_1161 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal grp_fu_545_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_21_reg_1166 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_558_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_22_reg_1171 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_17_fu_674_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_17_reg_1176 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_568_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_25_reg_1181 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_578_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_26_reg_1186 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_19_fu_678_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_19_reg_1191 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_588_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_29_reg_1196 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_598_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_30_reg_1201 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_fu_686_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_reg_1206 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal grp_fu_611_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_5_reg_1211 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_624_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_6_reg_1216 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_7_fu_695_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_7_reg_1221 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_634_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_11_reg_1226 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_644_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_12_reg_1231 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_12_fu_704_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_12_reg_1236 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_654_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_17_reg_1241 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_664_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_18_reg_1246 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_sin_2000_fu_218_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_218_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_218_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_sin_2000_fu_225_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_225_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_225_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_sin_2000_fu_232_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_232_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_232_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_sin_2000_fu_239_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_239_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_239_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_sin_2000_fu_246_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_246_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_246_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_sin_2000_fu_253_ap_start : STD_LOGIC;
    signal grp_sin_2000_fu_253_ap_idle : STD_LOGIC;
    signal grp_sin_2000_fu_253_theta_in : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_phi_mux_wt_V_loc_0_phi_fu_211_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal wt_V_loc_0_reg_208 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal grp_sin_2000_fu_218_ap_start_reg : STD_LOGIC := '0';
    signal grp_sin_2000_fu_225_ap_start_reg : STD_LOGIC := '0';
    signal grp_sin_2000_fu_232_ap_start_reg : STD_LOGIC := '0';
    signal grp_sin_2000_fu_239_ap_start_reg : STD_LOGIC := '0';
    signal grp_sin_2000_fu_246_ap_start_reg : STD_LOGIC := '0';
    signal grp_sin_2000_fu_253_ap_start_reg : STD_LOGIC := '0';
    signal ap_sig_allocacmp_va_V_load : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_vb_V_load : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_sig_allocacmp_vc_V_load : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_313_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal grp_fu_313_p2 : STD_LOGIC_VECTOR (93 downto 0);
    signal sext_ln708_fu_329_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln703_fu_332_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln1192_fu_360_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln1192_fu_365_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln1192_1_fu_404_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln1192_fu_409_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_455_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_468_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_478_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_488_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_510_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_520_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_545_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_558_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_568_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_578_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_588_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_598_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_611_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_624_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_634_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_644_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_654_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_664_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ret_V_16_fu_682_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_18_fu_691_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_20_fu_700_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_3_fu_709_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_4_fu_713_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_8_fu_734_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_9_fu_738_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_13_fu_759_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_14_fu_763_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal grp_fu_455_ce : STD_LOGIC;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal grp_fu_468_ce : STD_LOGIC;
    signal grp_fu_478_ce : STD_LOGIC;
    signal grp_fu_488_ce : STD_LOGIC;
    signal grp_fu_510_ce : STD_LOGIC;
    signal grp_fu_520_ce : STD_LOGIC;
    signal grp_fu_545_ce : STD_LOGIC;
    signal grp_fu_558_ce : STD_LOGIC;
    signal grp_fu_568_ce : STD_LOGIC;
    signal grp_fu_578_ce : STD_LOGIC;
    signal grp_fu_588_ce : STD_LOGIC;
    signal grp_fu_598_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component sin_gen_varAmp2_3phi_x64_sin_2000 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        theta_in : IN STD_LOGIC_VECTOR (63 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (49 downto 0) );
    end component;


    component sin_gen_varAmp2_3phi_x64_mul_64s_31ns_94_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (30 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (93 downto 0) );
    end component;


    component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (49 downto 0);
        din1 : IN STD_LOGIC_VECTOR (63 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (111 downto 0) );
    end component;



begin
    grp_sin_2000_fu_218 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_218_ap_start,
        ap_done => grp_sin_2000_fu_218_ap_done,
        ap_idle => grp_sin_2000_fu_218_ap_idle,
        ap_ready => grp_sin_2000_fu_218_ap_ready,
        theta_in => grp_sin_2000_fu_218_theta_in,
        ap_return => grp_sin_2000_fu_218_ap_return);

    grp_sin_2000_fu_225 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_225_ap_start,
        ap_done => grp_sin_2000_fu_225_ap_done,
        ap_idle => grp_sin_2000_fu_225_ap_idle,
        ap_ready => grp_sin_2000_fu_225_ap_ready,
        theta_in => grp_sin_2000_fu_225_theta_in,
        ap_return => grp_sin_2000_fu_225_ap_return);

    grp_sin_2000_fu_232 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_232_ap_start,
        ap_done => grp_sin_2000_fu_232_ap_done,
        ap_idle => grp_sin_2000_fu_232_ap_idle,
        ap_ready => grp_sin_2000_fu_232_ap_ready,
        theta_in => grp_sin_2000_fu_232_theta_in,
        ap_return => grp_sin_2000_fu_232_ap_return);

    grp_sin_2000_fu_239 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_239_ap_start,
        ap_done => grp_sin_2000_fu_239_ap_done,
        ap_idle => grp_sin_2000_fu_239_ap_idle,
        ap_ready => grp_sin_2000_fu_239_ap_ready,
        theta_in => grp_sin_2000_fu_239_theta_in,
        ap_return => grp_sin_2000_fu_239_ap_return);

    grp_sin_2000_fu_246 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_246_ap_start,
        ap_done => grp_sin_2000_fu_246_ap_done,
        ap_idle => grp_sin_2000_fu_246_ap_idle,
        ap_ready => grp_sin_2000_fu_246_ap_ready,
        theta_in => grp_sin_2000_fu_246_theta_in,
        ap_return => grp_sin_2000_fu_246_ap_return);

    grp_sin_2000_fu_253 : component sin_gen_varAmp2_3phi_x64_sin_2000
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_sin_2000_fu_253_ap_start,
        ap_done => grp_sin_2000_fu_253_ap_done,
        ap_idle => grp_sin_2000_fu_253_ap_idle,
        ap_ready => grp_sin_2000_fu_253_ap_ready,
        theta_in => grp_sin_2000_fu_253_theta_in,
        ap_return => grp_sin_2000_fu_253_ap_return);

    mul_64s_31ns_94_5_1_U5 : component sin_gen_varAmp2_3phi_x64_mul_64s_31ns_94_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 31,
        dout_WIDTH => 94)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => f,
        din1 => grp_fu_313_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_313_p2);

    mul_50s_64s_112_5_1_U6 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_260,
        din1 => grp_fu_455_p1,
        ce => grp_fu_455_ce,
        dout => grp_fu_455_p2);

    mul_50s_64s_112_5_1_U7 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_264,
        din1 => grp_fu_468_p1,
        ce => grp_fu_468_ce,
        dout => grp_fu_468_p2);

    mul_50s_64s_112_5_1_U8 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_268,
        din1 => grp_fu_478_p1,
        ce => grp_fu_478_ce,
        dout => grp_fu_478_p2);

    mul_50s_64s_112_5_1_U9 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_272,
        din1 => grp_fu_488_p1,
        ce => grp_fu_488_ce,
        dout => grp_fu_488_p2);

    mul_50s_64s_112_5_1_U10 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_276,
        din1 => grp_fu_510_p1,
        ce => grp_fu_510_ce,
        dout => grp_fu_510_p2);

    mul_50s_64s_112_5_1_U11 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_280,
        din1 => grp_fu_520_p1,
        ce => grp_fu_520_ce,
        dout => grp_fu_520_p2);

    mul_50s_64s_112_5_1_U12 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_260,
        din1 => grp_fu_545_p1,
        ce => grp_fu_545_ce,
        dout => grp_fu_545_p2);

    mul_50s_64s_112_5_1_U13 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_264,
        din1 => grp_fu_558_p1,
        ce => grp_fu_558_ce,
        dout => grp_fu_558_p2);

    mul_50s_64s_112_5_1_U14 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_268,
        din1 => grp_fu_568_p1,
        ce => grp_fu_568_ce,
        dout => grp_fu_568_p2);

    mul_50s_64s_112_5_1_U15 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_272,
        din1 => grp_fu_578_p1,
        ce => grp_fu_578_ce,
        dout => grp_fu_578_p2);

    mul_50s_64s_112_5_1_U16 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_276,
        din1 => grp_fu_588_p1,
        ce => grp_fu_588_ce,
        dout => grp_fu_588_p2);

    mul_50s_64s_112_5_1_U17 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_280,
        din1 => grp_fu_598_p1,
        ce => grp_fu_598_ce,
        dout => grp_fu_598_p2);

    mul_50s_64s_112_5_1_U18 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_260,
        din1 => grp_fu_611_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_611_p2);

    mul_50s_64s_112_5_1_U19 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_264,
        din1 => grp_fu_624_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_624_p2);

    mul_50s_64s_112_5_1_U20 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_268,
        din1 => grp_fu_634_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_634_p2);

    mul_50s_64s_112_5_1_U21 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_272,
        din1 => grp_fu_644_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_644_p2);

    mul_50s_64s_112_5_1_U22 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_276,
        din1 => grp_fu_654_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_654_p2);

    mul_50s_64s_112_5_1_U23 : component sin_gen_varAmp2_3phi_x64_mul_50s_64s_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 50,
        din1_WIDTH => 64,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_280,
        din1 => grp_fu_664_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_664_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_sin_2000_fu_218_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_218_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_218_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_218_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_218_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sin_2000_fu_225_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_225_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_225_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_225_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_225_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sin_2000_fu_232_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_232_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_232_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_232_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_232_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sin_2000_fu_239_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_239_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_239_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_239_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_239_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sin_2000_fu_246_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_246_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_246_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_246_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_246_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_sin_2000_fu_253_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_sin_2000_fu_253_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state8) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
                    grp_sin_2000_fu_253_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_sin_2000_fu_253_ap_ready = ap_const_logic_1)) then 
                    grp_sin_2000_fu_253_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    wt_V_loc_0_reg_208_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (xor_ln870_fu_288_p2 = ap_const_lv1_0))) then 
                wt_V_loc_0_reg_208 <= wt_V;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then 
                wt_V_loc_0_reg_208 <= select_ln38_reg_888;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                add_ln703_10_reg_964 <= add_ln703_10_fu_430_p2;
                add_ln703_15_reg_969 <= add_ln703_15_fu_436_p2;
                add_ln703_16_reg_974 <= add_ln703_16_fu_442_p2;
                add_ln703_5_reg_945 <= add_ln703_5_fu_414_p2;
                add_ln703_6_reg_952 <= add_ln703_6_fu_419_p2;
                add_ln703_9_reg_959 <= add_ln703_9_fu_424_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln703_11_reg_1013 <= add_ln703_11_fu_494_p2;
                add_ln703_12_reg_1018 <= add_ln703_12_fu_500_p2;
                add_ln703_17_reg_1033 <= add_ln703_17_fu_526_p2;
                add_ln703_18_reg_1038 <= add_ln703_18_fu_532_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                add_ln703_13_reg_935 <= add_ln703_13_fu_392_p2;
                add_ln703_14_reg_940 <= add_ln703_14_fu_398_p2;
                add_ln703_3_reg_911 <= add_ln703_3_fu_370_p2;
                add_ln703_4_reg_918 <= add_ln703_4_fu_375_p2;
                add_ln703_7_reg_925 <= add_ln703_7_fu_380_p2;
                add_ln703_8_reg_930 <= add_ln703_8_fu_386_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln703_1_reg_897 <= add_ln703_1_fu_350_p2;
                add_ln703_2_reg_904 <= add_ln703_2_fu_355_p2;
                select_ln38_reg_888 <= select_ln38_fu_337_p3;
                wt_V <= select_ln38_fu_337_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (xor_ln870_fu_288_p2 = ap_const_lv1_1))) then
                aux_sinc_V <= sinc;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (xor_ln870_fu_288_p2 = ap_const_lv1_1))) then
                icmp_ln1495_reg_873 <= icmp_ln1495_fu_304_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                r_V_11_reg_1226 <= grp_fu_634_p2;
                r_V_12_reg_1231 <= grp_fu_644_p2;
                r_V_17_reg_1241 <= grp_fu_654_p2;
                r_V_18_reg_1246 <= grp_fu_664_p2;
                r_V_5_reg_1211 <= grp_fu_611_p2;
                r_V_6_reg_1216 <= grp_fu_624_p2;
                ret_V_12_reg_1236 <= ret_V_12_fu_704_p2;
                ret_V_7_reg_1221 <= ret_V_7_fu_695_p2;
                ret_V_reg_1206 <= ret_V_fu_686_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state14)) then
                r_V_19_reg_1131 <= grp_fu_455_p2;
                r_V_20_reg_1136 <= grp_fu_468_p2;
                r_V_23_reg_1141 <= grp_fu_478_p2;
                r_V_24_reg_1146 <= grp_fu_488_p2;
                r_V_27_reg_1151 <= grp_fu_510_p2;
                r_V_28_reg_1156 <= grp_fu_520_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                r_V_21_reg_1166 <= grp_fu_545_p2;
                r_V_22_reg_1171 <= grp_fu_558_p2;
                r_V_25_reg_1181 <= grp_fu_568_p2;
                r_V_26_reg_1186 <= grp_fu_578_p2;
                r_V_29_reg_1196 <= grp_fu_588_p2;
                r_V_30_reg_1201 <= grp_fu_598_p2;
                ret_V_15_reg_1161 <= ret_V_15_fu_670_p2;
                ret_V_17_reg_1176 <= ret_V_17_fu_674_p2;
                ret_V_19_reg_1191 <= ret_V_19_fu_678_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)) or ((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then
                reg_260 <= grp_sin_2000_fu_218_ap_return;
                reg_264 <= grp_sin_2000_fu_225_ap_return;
                reg_268 <= grp_sin_2000_fu_232_ap_return;
                reg_272 <= grp_sin_2000_fu_239_ap_return;
                reg_276 <= grp_sin_2000_fu_246_ap_return;
                reg_280 <= grp_sin_2000_fu_253_ap_return;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln1495_reg_873 = ap_const_lv1_1))) then
                trunc_ln_reg_883 <= grp_fu_313_p2(93 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then
                va_V <= ret_V_4_fu_713_p2(111 downto 48);
                vb_V <= ret_V_9_fu_738_p2(111 downto 48);
                vc_V <= ret_V_14_fu_763_p2(111 downto 48);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                xor_ln870_reg_864 <= xor_ln870_fu_288_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state9, ap_block_state9_on_subcall_done, ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, xor_ln870_fu_288_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (xor_ln870_fu_288_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state17;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (xor_ln870_fu_288_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((ap_const_boolean_0 = ap_block_state9_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                if (((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state15;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state16;
            when ap_ST_fsm_state16 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state17 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln1192_fu_365_p2 <= std_logic_vector(unsigned(shl_ln1192_fu_360_p2) + unsigned(select_ln38_reg_888));
    add_ln703_10_fu_430_p2 <= std_logic_vector(unsigned(add_ln703_4_reg_918) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_11_fu_494_p2 <= std_logic_vector(unsigned(add_ln703_5_reg_945) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_12_fu_500_p2 <= std_logic_vector(unsigned(add_ln703_6_reg_952) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_13_fu_392_p2 <= std_logic_vector(unsigned(add_ln703_1_reg_897) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_14_fu_398_p2 <= std_logic_vector(unsigned(add_ln703_2_reg_904) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_15_fu_436_p2 <= std_logic_vector(unsigned(add_ln703_3_reg_911) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_16_fu_442_p2 <= std_logic_vector(unsigned(add_ln703_4_reg_918) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_17_fu_526_p2 <= std_logic_vector(unsigned(add_ln703_5_reg_945) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_18_fu_532_p2 <= std_logic_vector(unsigned(add_ln703_6_reg_952) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_1_fu_350_p2 <= std_logic_vector(unsigned(select_ln38_fu_337_p3) + unsigned(Ang_1p));
    add_ln703_2_fu_355_p2 <= std_logic_vector(unsigned(select_ln38_fu_337_p3) + unsigned(Ang_1n));
    add_ln703_3_fu_370_p2 <= std_logic_vector(unsigned(add_ln1192_fu_365_p2) + unsigned(Ang_5p));
    add_ln703_4_fu_375_p2 <= std_logic_vector(unsigned(add_ln1192_fu_365_p2) + unsigned(Ang_5n));
    add_ln703_5_fu_414_p2 <= std_logic_vector(unsigned(sub_ln1192_fu_409_p2) + unsigned(Ang_7p));
    add_ln703_6_fu_419_p2 <= std_logic_vector(unsigned(sub_ln1192_fu_409_p2) + unsigned(Ang_7n));
    add_ln703_7_fu_380_p2 <= std_logic_vector(unsigned(add_ln703_1_reg_897) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_8_fu_386_p2 <= std_logic_vector(unsigned(add_ln703_2_reg_904) + unsigned(ap_const_lv64_2182A4705AAE9));
    add_ln703_9_fu_424_p2 <= std_logic_vector(unsigned(add_ln703_3_reg_911) + unsigned(ap_const_lv64_FFFDE7D5B8FA5517));
    add_ln703_fu_332_p2 <= std_logic_vector(unsigned(wt_V) + unsigned(sext_ln708_fu_329_p1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state10_on_subcall_done_assign_proc : process(grp_sin_2000_fu_218_ap_done, grp_sin_2000_fu_225_ap_done, grp_sin_2000_fu_232_ap_done, grp_sin_2000_fu_239_ap_done, grp_sin_2000_fu_246_ap_done, grp_sin_2000_fu_253_ap_done)
    begin
                ap_block_state10_on_subcall_done <= ((grp_sin_2000_fu_253_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_246_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_239_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_232_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_225_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_218_ap_done = ap_const_logic_0));
    end process;


    ap_block_state11_on_subcall_done_assign_proc : process(grp_sin_2000_fu_218_ap_done, grp_sin_2000_fu_225_ap_done, grp_sin_2000_fu_232_ap_done, grp_sin_2000_fu_239_ap_done, grp_sin_2000_fu_246_ap_done, grp_sin_2000_fu_253_ap_done)
    begin
                ap_block_state11_on_subcall_done <= ((grp_sin_2000_fu_253_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_246_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_239_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_232_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_225_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_218_ap_done = ap_const_logic_0));
    end process;


    ap_block_state9_on_subcall_done_assign_proc : process(grp_sin_2000_fu_218_ap_done, grp_sin_2000_fu_225_ap_done, grp_sin_2000_fu_232_ap_done, grp_sin_2000_fu_239_ap_done, grp_sin_2000_fu_246_ap_done, grp_sin_2000_fu_253_ap_done)
    begin
                ap_block_state9_on_subcall_done <= ((grp_sin_2000_fu_253_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_246_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_239_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_232_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_225_ap_done = ap_const_logic_0) or (grp_sin_2000_fu_218_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_wt_V_loc_0_phi_fu_211_p4_assign_proc : process(xor_ln870_reg_864, select_ln38_reg_888, wt_V_loc_0_reg_208, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then 
            ap_phi_mux_wt_V_loc_0_phi_fu_211_p4 <= select_ln38_reg_888;
        else 
            ap_phi_mux_wt_V_loc_0_phi_fu_211_p4 <= wt_V_loc_0_reg_208;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_va_V_load_assign_proc : process(va_V, xor_ln870_reg_864, ap_CS_fsm_state17, ret_V_4_fu_713_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_va_V_load <= ret_V_4_fu_713_p2(111 downto 48);
        else 
            ap_sig_allocacmp_va_V_load <= va_V;
        end if; 
    end process;


    ap_sig_allocacmp_vb_V_load_assign_proc : process(vb_V, xor_ln870_reg_864, ap_CS_fsm_state17, ret_V_9_fu_738_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_vb_V_load <= ret_V_9_fu_738_p2(111 downto 48);
        else 
            ap_sig_allocacmp_vb_V_load <= vb_V;
        end if; 
    end process;


    ap_sig_allocacmp_vc_V_load_assign_proc : process(vc_V, xor_ln870_reg_864, ap_CS_fsm_state17, ret_V_14_fu_763_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) and (xor_ln870_reg_864 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_vc_V_load <= ret_V_14_fu_763_p2(111 downto 48);
        else 
            ap_sig_allocacmp_vc_V_load <= vc_V;
        end if; 
    end process;

    grp_fu_313_p1 <= ap_const_lv94_34B509A7(31 - 1 downto 0);

    grp_fu_455_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_455_ce <= ap_const_logic_1;
        else 
            grp_fu_455_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_455_p1 <= sext_ln1115_fu_448_p1(64 - 1 downto 0);

    grp_fu_468_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_468_ce <= ap_const_logic_1;
        else 
            grp_fu_468_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_468_p1 <= sext_ln1115_1_fu_461_p1(64 - 1 downto 0);

    grp_fu_478_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_478_ce <= ap_const_logic_1;
        else 
            grp_fu_478_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_478_p1 <= sext_ln1115_fu_448_p1(64 - 1 downto 0);

    grp_fu_488_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_488_ce <= ap_const_logic_1;
        else 
            grp_fu_488_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_488_p1 <= sext_ln1115_1_fu_461_p1(64 - 1 downto 0);

    grp_fu_510_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_510_ce <= ap_const_logic_1;
        else 
            grp_fu_510_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_510_p1 <= sext_ln1115_fu_448_p1(64 - 1 downto 0);

    grp_fu_520_ce_assign_proc : process(ap_CS_fsm_state10, ap_block_state10_on_subcall_done, ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)) or ((ap_const_boolean_0 = ap_block_state10_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_520_ce <= ap_const_logic_1;
        else 
            grp_fu_520_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_520_p1 <= sext_ln1115_1_fu_461_p1(64 - 1 downto 0);

    grp_fu_545_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_545_ce <= ap_const_logic_1;
        else 
            grp_fu_545_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_545_p1 <= sext_ln1115_2_fu_538_p1(64 - 1 downto 0);

    grp_fu_558_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_558_ce <= ap_const_logic_1;
        else 
            grp_fu_558_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_558_p1 <= sext_ln1115_3_fu_551_p1(64 - 1 downto 0);

    grp_fu_568_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_568_ce <= ap_const_logic_1;
        else 
            grp_fu_568_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_568_p1 <= sext_ln1115_2_fu_538_p1(64 - 1 downto 0);

    grp_fu_578_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_578_ce <= ap_const_logic_1;
        else 
            grp_fu_578_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_578_p1 <= sext_ln1115_3_fu_551_p1(64 - 1 downto 0);

    grp_fu_588_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_588_ce <= ap_const_logic_1;
        else 
            grp_fu_588_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_588_p1 <= sext_ln1115_2_fu_538_p1(64 - 1 downto 0);

    grp_fu_598_ce_assign_proc : process(ap_CS_fsm_state11, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state14, ap_CS_fsm_state15, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state15) or (ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state12) or ((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11)))) then 
            grp_fu_598_ce <= ap_const_logic_1;
        else 
            grp_fu_598_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_598_p1 <= sext_ln1115_3_fu_551_p1(64 - 1 downto 0);
    grp_fu_611_p1 <= sext_ln1115_4_fu_604_p1(64 - 1 downto 0);
    grp_fu_624_p1 <= sext_ln1115_5_fu_617_p1(64 - 1 downto 0);
    grp_fu_634_p1 <= sext_ln1115_4_fu_604_p1(64 - 1 downto 0);
    grp_fu_644_p1 <= sext_ln1115_5_fu_617_p1(64 - 1 downto 0);
    grp_fu_654_p1 <= sext_ln1115_4_fu_604_p1(64 - 1 downto 0);
    grp_fu_664_p1 <= sext_ln1115_5_fu_617_p1(64 - 1 downto 0);
    grp_sin_2000_fu_218_ap_start <= grp_sin_2000_fu_218_ap_start_reg;

    grp_sin_2000_fu_218_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_1_reg_897, add_ln703_3_reg_911, add_ln703_5_reg_945)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_218_theta_in <= add_ln703_5_reg_945;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_218_theta_in <= add_ln703_3_reg_911;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_218_theta_in <= add_ln703_1_reg_897;
        else 
            grp_sin_2000_fu_218_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sin_2000_fu_225_ap_start <= grp_sin_2000_fu_225_ap_start_reg;

    grp_sin_2000_fu_225_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_2_reg_904, add_ln703_4_reg_918, add_ln703_6_reg_952)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_225_theta_in <= add_ln703_6_reg_952;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_225_theta_in <= add_ln703_4_reg_918;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_225_theta_in <= add_ln703_2_reg_904;
        else 
            grp_sin_2000_fu_225_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sin_2000_fu_232_ap_start <= grp_sin_2000_fu_232_ap_start_reg;

    grp_sin_2000_fu_232_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_7_reg_925, add_ln703_9_reg_959, add_ln703_11_reg_1013)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_232_theta_in <= add_ln703_11_reg_1013;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_232_theta_in <= add_ln703_9_reg_959;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_232_theta_in <= add_ln703_7_reg_925;
        else 
            grp_sin_2000_fu_232_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sin_2000_fu_239_ap_start <= grp_sin_2000_fu_239_ap_start_reg;

    grp_sin_2000_fu_239_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_8_reg_930, add_ln703_10_reg_964, add_ln703_12_reg_1018)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_239_theta_in <= add_ln703_12_reg_1018;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_239_theta_in <= add_ln703_10_reg_964;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_239_theta_in <= add_ln703_8_reg_930;
        else 
            grp_sin_2000_fu_239_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sin_2000_fu_246_ap_start <= grp_sin_2000_fu_246_ap_start_reg;

    grp_sin_2000_fu_246_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_13_reg_935, add_ln703_15_reg_969, add_ln703_17_reg_1033)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_246_theta_in <= add_ln703_17_reg_1033;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_246_theta_in <= add_ln703_15_reg_969;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_246_theta_in <= add_ln703_13_reg_935;
        else 
            grp_sin_2000_fu_246_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    grp_sin_2000_fu_253_ap_start <= grp_sin_2000_fu_253_ap_start_reg;

    grp_sin_2000_fu_253_theta_in_assign_proc : process(ap_CS_fsm_state9, ap_CS_fsm_state10, ap_CS_fsm_state11, add_ln703_14_reg_940, add_ln703_16_reg_974, add_ln703_18_reg_1038)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            grp_sin_2000_fu_253_theta_in <= add_ln703_18_reg_1038;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            grp_sin_2000_fu_253_theta_in <= add_ln703_16_reg_974;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            grp_sin_2000_fu_253_theta_in <= add_ln703_14_reg_940;
        else 
            grp_sin_2000_fu_253_theta_in <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln1495_fu_304_p2 <= "1" when (signed(wt_V) < signed(ap_const_lv64_6487ED5110B46)) else "0";
    ret_V_12_fu_704_p2 <= std_logic_vector(unsigned(ret_V_20_fu_700_p2) + unsigned(r_V_30_reg_1201));
    ret_V_13_fu_759_p2 <= std_logic_vector(unsigned(ret_V_12_reg_1236) + unsigned(r_V_17_reg_1241));
    ret_V_14_fu_763_p2 <= std_logic_vector(unsigned(ret_V_13_fu_759_p2) + unsigned(r_V_18_reg_1246));
    ret_V_15_fu_670_p2 <= std_logic_vector(unsigned(r_V_20_reg_1136) + unsigned(r_V_19_reg_1131));
    ret_V_16_fu_682_p2 <= std_logic_vector(unsigned(ret_V_15_reg_1161) + unsigned(r_V_21_reg_1166));
    ret_V_17_fu_674_p2 <= std_logic_vector(unsigned(r_V_24_reg_1146) + unsigned(r_V_23_reg_1141));
    ret_V_18_fu_691_p2 <= std_logic_vector(unsigned(ret_V_17_reg_1176) + unsigned(r_V_25_reg_1181));
    ret_V_19_fu_678_p2 <= std_logic_vector(unsigned(r_V_28_reg_1156) + unsigned(r_V_27_reg_1151));
    ret_V_20_fu_700_p2 <= std_logic_vector(unsigned(ret_V_19_reg_1191) + unsigned(r_V_29_reg_1196));
    ret_V_3_fu_709_p2 <= std_logic_vector(unsigned(ret_V_reg_1206) + unsigned(r_V_5_reg_1211));
    ret_V_4_fu_713_p2 <= std_logic_vector(unsigned(ret_V_3_fu_709_p2) + unsigned(r_V_6_reg_1216));
    ret_V_7_fu_695_p2 <= std_logic_vector(unsigned(ret_V_18_fu_691_p2) + unsigned(r_V_26_reg_1186));
    ret_V_8_fu_734_p2 <= std_logic_vector(unsigned(ret_V_7_reg_1221) + unsigned(r_V_11_reg_1226));
    ret_V_9_fu_738_p2 <= std_logic_vector(unsigned(ret_V_8_fu_734_p2) + unsigned(r_V_12_reg_1231));
    ret_V_fu_686_p2 <= std_logic_vector(unsigned(ret_V_16_fu_682_p2) + unsigned(r_V_22_reg_1171));
    select_ln38_fu_337_p3 <= 
        add_ln703_fu_332_p2 when (icmp_ln1495_reg_873(0) = '1') else 
        ap_const_lv64_0;
        sext_ln1115_1_fu_461_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_1n),112));

        sext_ln1115_2_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_5p),112));

        sext_ln1115_3_fu_551_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_5n),112));

        sext_ln1115_4_fu_604_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_7p),112));

        sext_ln1115_5_fu_617_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_7n),112));

        sext_ln1115_fu_448_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(A_1p),112));

        sext_ln708_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_883),64));

    shl_ln1192_1_fu_404_p2 <= std_logic_vector(shift_left(unsigned(select_ln38_reg_888),to_integer(unsigned('0' & ap_const_lv64_3(31-1 downto 0)))));
    shl_ln1192_fu_360_p2 <= std_logic_vector(shift_left(unsigned(select_ln38_reg_888),to_integer(unsigned('0' & ap_const_lv64_2(31-1 downto 0)))));
    sub_ln1192_fu_409_p2 <= std_logic_vector(unsigned(shl_ln1192_1_fu_404_p2) - unsigned(select_ln38_reg_888));
    vout_a <= ap_sig_allocacmp_va_V_load;

    vout_a_ap_vld_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            vout_a_ap_vld <= ap_const_logic_1;
        else 
            vout_a_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    vout_b <= ap_sig_allocacmp_vb_V_load;

    vout_b_ap_vld_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            vout_b_ap_vld <= ap_const_logic_1;
        else 
            vout_b_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    vout_c <= ap_sig_allocacmp_vc_V_load;

    vout_c_ap_vld_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            vout_c_ap_vld <= ap_const_logic_1;
        else 
            vout_c_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    wtout <= ap_phi_mux_wt_V_loc_0_phi_fu_211_p4;

    wtout_ap_vld_assign_proc : process(ap_CS_fsm_state17)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            wtout_ap_vld <= ap_const_logic_1;
        else 
            wtout_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    xor_ln870_fu_288_p2 <= (sinc xor aux_sinc_V);
end behav;
