-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity PLL2026_x64_SQRT_LUT is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (63 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of PLL2026_x64_SQRT_LUT is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv48_0 : STD_LOGIC_VECTOR (47 downto 0) := "000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal table_mark_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal table_mark_V_ce0 : STD_LOGIC;
    signal table_mark_V_q0 : STD_LOGIC_VECTOR (62 downto 0);
    signal table_m_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal table_m_V_ce0 : STD_LOGIC;
    signal table_m_V_q0 : STD_LOGIC_VECTOR (48 downto 0);
    signal table_n_V_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal table_n_V_ce0 : STD_LOGIC;
    signal table_n_V_q0 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_fu_134_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_273 : STD_LOGIC_VECTOR (0 downto 0);
    signal half_list_fu_178_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal half_list_reg_280 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln986_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal intervalo_begin_1_fu_198_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal intervalo_end_1_fu_205_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ret_V_fu_223_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ret_V_reg_316 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal r_V_reg_321 : STD_LOGIC_VECTOR (48 downto 0);
    signal rhs_1_reg_326 : STD_LOGIC_VECTOR (54 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_fu_234_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal r_V_1_reg_341 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal intervalo_begin_reg_99 : STD_LOGIC_VECTOR (31 downto 0);
    signal intervalo_end_reg_111 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_y_V_phi_fu_127_p4 : STD_LOGIC_VECTOR (63 downto 0);
    signal y_V_reg_123 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal zext_ln991_fu_184_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln1227_fu_212_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln986_fu_142_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_148_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal div1_i_fu_164_p4 : STD_LOGIC_VECTOR (30 downto 0);
    signal div1_i_cast_fu_174_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln1494_fu_189_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln1494_fu_193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln1193_fu_219_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_234_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal rhs_2_fu_240_p3 : STD_LOGIC_VECTOR (102 downto 0);
    signal zext_ln1192_fu_247_p1 : STD_LOGIC_VECTOR (111 downto 0);
    signal ret_V_5_fu_251_p2 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_return_preg : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_234_p10 : STD_LOGIC_VECTOR (111 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component PLL2026_x64_mul_64s_49ns_112_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (63 downto 0);
        din1 : IN STD_LOGIC_VECTOR (48 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (111 downto 0) );
    end component;


    component PLL2026_x64_SQRT_LUT_table_mark_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component PLL2026_x64_SQRT_LUT_table_m_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (48 downto 0) );
    end component;


    component PLL2026_x64_SQRT_LUT_table_n_V IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (54 downto 0) );
    end component;



begin
    table_mark_V_U : component PLL2026_x64_SQRT_LUT_table_mark_V
    generic map (
        DataWidth => 63,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_mark_V_address0,
        ce0 => table_mark_V_ce0,
        q0 => table_mark_V_q0);

    table_m_V_U : component PLL2026_x64_SQRT_LUT_table_m_V
    generic map (
        DataWidth => 49,
        AddressRange => 63,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_m_V_address0,
        ce0 => table_m_V_ce0,
        q0 => table_m_V_q0);

    table_n_V_U : component PLL2026_x64_SQRT_LUT_table_n_V
    generic map (
        DataWidth => 55,
        AddressRange => 63,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => table_n_V_address0,
        ce0 => table_n_V_ce0,
        q0 => table_n_V_q0);

    mul_64s_49ns_112_5_1_U27 : component PLL2026_x64_mul_64s_49ns_112_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 64,
        din1_WIDTH => 49,
        dout_WIDTH => 112)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => ret_V_reg_316,
        din1 => grp_fu_234_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_234_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_return_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_preg <= ap_const_lv64_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    ap_return_preg <= ap_phi_mux_y_V_phi_fu_127_p4;
                end if; 
            end if;
        end if;
    end process;


    intervalo_begin_reg_99_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_134_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                intervalo_begin_reg_99 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                intervalo_begin_reg_99 <= intervalo_begin_1_fu_198_p3;
            end if; 
        end if;
    end process;

    intervalo_end_reg_111_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_134_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                intervalo_end_reg_111 <= ap_const_lv32_3F;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                intervalo_end_reg_111 <= intervalo_end_1_fu_205_p3;
            end if; 
        end if;
    end process;

    y_V_reg_123_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_fu_134_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                y_V_reg_123 <= ap_const_lv64_0;
            elsif (((tmp_reg_273 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                y_V_reg_123 <= ret_V_5_fu_251_p2(111 downto 48);
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln986_fu_158_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                half_list_reg_280 <= half_list_fu_178_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                r_V_1_reg_341 <= grp_fu_234_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                r_V_reg_321 <= table_m_V_q0;
                ret_V_reg_316 <= ret_V_fu_223_p2;
                rhs_1_reg_326 <= table_n_V_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                tmp_reg_273 <= x(63 downto 63);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, tmp_fu_134_p3, ap_CS_fsm_state2, icmp_ln986_fu_158_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((tmp_fu_134_p3 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((tmp_fu_134_p3 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln986_fu_158_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_y_V_phi_fu_127_p4_assign_proc : process(tmp_reg_273, y_V_reg_123, ap_CS_fsm_state11, ret_V_5_fu_251_p2)
    begin
        if (((tmp_reg_273 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_phi_mux_y_V_phi_fu_127_p4 <= ret_V_5_fu_251_p2(111 downto 48);
        else 
            ap_phi_mux_y_V_phi_fu_127_p4 <= y_V_reg_123;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_assign_proc : process(ap_phi_mux_y_V_phi_fu_127_p4, ap_CS_fsm_state11, ap_return_preg)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_return <= ap_phi_mux_y_V_phi_fu_127_p4;
        else 
            ap_return <= ap_return_preg;
        end if; 
    end process;

    div1_i_cast_fu_174_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(div1_i_fu_164_p4),32));
    div1_i_fu_164_p4 <= sub_ln986_fu_142_p2(31 downto 1);
    grp_fu_234_p1 <= grp_fu_234_p10(49 - 1 downto 0);
    grp_fu_234_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_reg_321),112));
    half_list_fu_178_p2 <= std_logic_vector(unsigned(div1_i_cast_fu_174_p1) + unsigned(intervalo_begin_reg_99));
    icmp_ln1494_fu_193_p2 <= "1" when (signed(zext_ln1494_fu_189_p1) < signed(x)) else "0";
    icmp_ln986_fu_158_p2 <= "1" when (signed(tmp_8_fu_148_p4) > signed(ap_const_lv31_0)) else "0";
    intervalo_begin_1_fu_198_p3 <= 
        half_list_reg_280 when (icmp_ln1494_fu_193_p2(0) = '1') else 
        intervalo_begin_reg_99;
    intervalo_end_1_fu_205_p3 <= 
        intervalo_end_reg_111 when (icmp_ln1494_fu_193_p2(0) = '1') else 
        half_list_reg_280;
    ret_V_5_fu_251_p2 <= std_logic_vector(unsigned(zext_ln1192_fu_247_p1) + unsigned(r_V_1_reg_341));
    ret_V_fu_223_p2 <= std_logic_vector(unsigned(x) - unsigned(zext_ln1193_fu_219_p1));
    rhs_2_fu_240_p3 <= (rhs_1_reg_326 & ap_const_lv48_0);
    sub_ln986_fu_142_p2 <= std_logic_vector(unsigned(intervalo_end_reg_111) - unsigned(intervalo_begin_reg_99));
    table_m_V_address0 <= zext_ln1227_fu_212_p1(6 - 1 downto 0);

    table_m_V_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            table_m_V_ce0 <= ap_const_logic_1;
        else 
            table_m_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    table_mark_V_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4, zext_ln991_fu_184_p1, zext_ln1227_fu_212_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            table_mark_V_address0 <= zext_ln1227_fu_212_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            table_mark_V_address0 <= zext_ln991_fu_184_p1(6 - 1 downto 0);
        else 
            table_mark_V_address0 <= "XXXXXX";
        end if; 
    end process;


    table_mark_V_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            table_mark_V_ce0 <= ap_const_logic_1;
        else 
            table_mark_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    table_n_V_address0 <= zext_ln1227_fu_212_p1(6 - 1 downto 0);

    table_n_V_ce0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            table_n_V_ce0 <= ap_const_logic_1;
        else 
            table_n_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_8_fu_148_p4 <= sub_ln986_fu_142_p2(31 downto 1);
    tmp_fu_134_p3 <= x(63 downto 63);
    zext_ln1192_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(rhs_2_fu_240_p3),112));
    zext_ln1193_fu_219_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(table_mark_V_q0),64));
    zext_ln1227_fu_212_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(intervalo_begin_reg_99),64));
    zext_ln1494_fu_189_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(table_mark_V_q0),64));
    zext_ln991_fu_184_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(half_list_fu_178_p2),64));
end behav;
